//! Integration tests for the generated `curl-config` helper script.
//!
//! # What this guards (QA finding F7-CLI Issue 11 / AAP §0.5 curl-config parity)
//!
//! `curl-rs/build.rs` generates an executable `curl-config` (from the committed
//! `curl-config.in` template) next to the compiled `curl-rs` binary in the
//! Cargo target profile directory. These tests:
//!
//!  1. prove that `curl-config` is actually produced by the workspace build and
//!     answers the in-scope queries (`--features`, `--protocols`, `--version`,
//!     `--vernum`, `--ssl-backends`, `--help`); and
//!  2. **pin it in lock-step with `curl-rs --version`** — the QA-validated
//!     single source of truth for the capability sets (AAP §0.7.3). Because
//!     `build.rs` bakes the feature/protocol lists while
//!     `curl-rs-lib::version` produces `--version`, any future divergence
//!     between the two is turned into a hard test failure here, so the two can
//!     never silently drift apart.
//!
//! The script is `#!/bin/sh`, so these tests are unix-only; the workspace CI
//! build/test target is Linux.
#![cfg(unix)]

use std::path::PathBuf;
use std::process::Command;

/// Absolute path to the compiled `curl-rs` binary (Cargo sets this for
/// integration tests; the bin target is named `curl-rs`).
const CURL_RS: &str = env!("CARGO_BIN_EXE_curl-rs");

/// Resolve the generated `curl-config`, co-located with the `curl-rs` binary in
/// the active target profile directory (`target/<profile>/curl-config`).
fn curl_config_path() -> PathBuf {
    PathBuf::from(CURL_RS)
        .parent()
        .expect("the curl-rs binary always has a parent profile directory")
        .join("curl-config")
}

/// Run `curl-config <args...>` through `/bin/sh` (robust regardless of the
/// execute bit) and return `(stdout, exit_code)`. stderr is merged is *not*
/// needed for these assertions, so only stdout is captured here.
fn run_curl_config(args: &[&str]) -> (String, i32) {
    let path = curl_config_path();
    assert!(
        path.is_file(),
        "curl-config was not generated by build.rs at {} — the build script must emit it next to \
         the curl-rs binary",
        path.display()
    );
    let output = Command::new("sh")
        .arg(&path)
        .args(args)
        .output()
        .expect("failed to spawn /bin/sh to run curl-config");
    let stdout = String::from_utf8(output.stdout).expect("curl-config stdout must be valid UTF-8");
    let code = output.status.code().expect("curl-config exited via a signal");
    (stdout, code)
}

/// Extract the whitespace-separated tokens following a `"<Prefix>: "` line in
/// `curl-rs --version` output (e.g. `Protocols:` / `Features:`).
fn version_line_tokens(prefix: &str) -> Vec<String> {
    let output = Command::new(CURL_RS)
        .arg("--version")
        .output()
        .expect("failed to spawn curl-rs --version");
    let stdout =
        String::from_utf8(output.stdout).expect("curl-rs --version stdout must be valid UTF-8");
    let needle = format!("{prefix}: ");
    stdout
        .lines()
        .find_map(|line| line.strip_prefix(&needle))
        .unwrap_or_else(|| panic!("curl-rs --version did not contain a '{prefix}:' line"))
        .split_whitespace()
        .map(str::to_string)
        .collect()
}

/// Helper: split curl-config stdout into trimmed, non-empty lines.
fn nonempty_lines(stdout: &str) -> Vec<String> {
    stdout
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .map(str::to_string)
        .collect()
}

#[test]
fn curl_config_is_generated_and_runnable() {
    // `--help` exits 0 and prints the usage banner enumerating the options.
    let (stdout, code) = run_curl_config(&["--help"]);
    assert_eq!(code, 0, "curl-config --help must exit 0");
    assert!(
        stdout.contains("Usage: curl-config"),
        "curl-config --help must print the usage banner; got:\n{stdout}"
    );
    for opt in ["--features", "--protocols", "--version", "--vernum"] {
        assert!(
            stdout.contains(opt),
            "curl-config --help usage must list {opt}; got:\n{stdout}"
        );
    }
}

#[test]
fn curl_config_features_match_version() {
    let (stdout, code) = run_curl_config(&["--features"]);
    assert_eq!(code, 0, "curl-config --features must exit 0");

    // curl-config prints one feature per line; --version lists them space-separated.
    let mut from_config = nonempty_lines(&stdout);
    let mut from_version = version_line_tokens("Features");

    // Equivalence is set equality (independent of ordering).
    from_config.sort();
    from_version.sort();
    assert_eq!(
        from_config, from_version,
        "curl-config --features must equal the curl-rs --version Features set (single source of \
         truth, AAP §0.7.3)"
    );
    // The curl 8.x default build advertises exactly 17 features.
    assert_eq!(
        from_config.len(),
        17,
        "expected exactly 17 features; got {from_config:?}"
    );
}

#[test]
fn curl_config_protocols_match_version_uppercased() {
    let (stdout, code) = run_curl_config(&["--protocols"]);
    assert_eq!(code, 0, "curl-config --protocols must exit 0");

    let config_lines = nonempty_lines(&stdout);

    // curl-config emits UPPERCASE protocol names (the curl-config convention),
    // while `curl --version` emits the lowercase variant of the same set.
    for proto in &config_lines {
        assert_eq!(
            proto.to_ascii_uppercase(),
            *proto,
            "curl-config --protocols must be UPPERCASE; offending token: {proto}"
        );
    }

    let mut config_lower: Vec<String> =
        config_lines.iter().map(|p| p.to_ascii_lowercase()).collect();
    let mut from_version = version_line_tokens("Protocols");
    config_lower.sort();
    from_version.sort();
    assert_eq!(
        config_lower, from_version,
        "curl-config --protocols (lowercased) must equal the curl-rs --version Protocols set \
         (single source of truth, AAP §0.7.3)"
    );
    // The curl 8.x default build advertises exactly 27 protocols.
    assert_eq!(
        config_lower.len(),
        27,
        "expected exactly 27 protocols; got {config_lower:?}"
    );
}

#[test]
fn curl_config_version_and_vernum() {
    let (version_out, vcode) = run_curl_config(&["--version"]);
    assert_eq!(vcode, 0, "curl-config --version must exit 0");
    assert_eq!(
        version_out.trim(),
        "libcurl 8.19.0-DEV",
        "curl-config --version must print 'libcurl <CURLVERSION>'"
    );

    let (vernum_out, ncode) = run_curl_config(&["--vernum"]);
    assert_eq!(ncode, 0, "curl-config --vernum must exit 0");
    assert_eq!(
        vernum_out.trim(),
        "081300",
        "curl-config --vernum must print the hex LIBCURL_VERSION_NUM digits (0x081300)"
    );
}

#[test]
fn curl_config_ssl_backends_is_rustls() {
    let (stdout, code) = run_curl_config(&["--ssl-backends"]);
    assert_eq!(code, 0, "curl-config --ssl-backends must exit 0");
    assert_eq!(
        stdout.trim(),
        "rustls",
        "curl-config --ssl-backends must report the exclusive rustls backend (AAP §0.8.1)"
    );
}

#[test]
fn curl_config_no_args_and_unknown_option_exit_nonzero() {
    // No arguments → usage to stderr/stdout with exit status 1 (curl-config.in).
    let (_stdout, code) = run_curl_config(&[]);
    assert_eq!(code, 1, "curl-config with no args must exit 1");

    // Unknown option → diagnostic + usage, exit status 1.
    let (stdout, ucode) = run_curl_config(&["--nope"]);
    assert_eq!(ucode, 1, "curl-config with an unknown option must exit 1");
    assert!(
        stdout.contains("unknown option"),
        "curl-config must report 'unknown option'; got:\n{stdout}"
    );
}
