/*
 * formadd_trampoline.c — the variadic shim for the deprecated `curl_formadd`.
 *
 * `curl_formadd` is a true C-variadic terminated by `CURLFORM_END`. Stable Rust
 * cannot define a variadic `extern "C"` function, and (unlike `curl_easy_setopt`)
 * a single call carries an arbitrary number of option/value pairs, so the
 * "read one trailing argument" trick does not apply. This trampoline therefore
 * owns the exported `curl_formadd` symbol: it walks the `va_list`, normalizes it
 * into a `curl_forms[]` array (each entry an {option, value} pair, with length
 * options carried as the integer reinterpreted into the pointer slot), and
 * hands that array to the non-variadic Rust implementation
 * `curlrs_formadd_impl` (see `curl-rs-ffi/src/mime.rs`), which mirrors `FormAdd`
 * in `lib/formdata.c`.
 *
 * AAP §0.7.2 (variadic FFI) and §0.8.2/§0.8.3 document this C-linkage exception:
 * it is the single, minimal piece of C required to reproduce curl's variadic
 * ABI faithfully. The trampoline does NOT interpret `CURLFORM_ARRAY`; it records
 * the array pointer verbatim and lets the Rust side walk it, exactly as curl's
 * `FormAdd` switches between its `va_list` and array cursors.
 *
 * The build wires this file in via `curl-rs-ffi/build.rs` (a `cc` step) and
 * forces whole-archive linkage so the exported `curl_formadd` symbol is retained
 * even though nothing on the Rust side references it.
 */

#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 * Stable `CURLformoption` integers from include/curl/curl.h. We hard-code them
 * rather than #include <curl/curl.h>, because that header is regenerated by
 * cbindgen from the Rust crate and is not guaranteed present (or final) when
 * this translation unit is compiled. These values are part of the frozen public
 * ABI and are verified against the header.
 */
#define TR_CURLFORM_NOTHING         0
#define TR_CURLFORM_COPYNAME        1
#define TR_CURLFORM_PTRNAME         2
#define TR_CURLFORM_NAMELENGTH      3
#define TR_CURLFORM_COPYCONTENTS    4
#define TR_CURLFORM_PTRCONTENTS     5
#define TR_CURLFORM_CONTENTSLENGTH  6
#define TR_CURLFORM_FILECONTENT     7
#define TR_CURLFORM_ARRAY           8
#define TR_CURLFORM_FILE            10
#define TR_CURLFORM_BUFFER          11
#define TR_CURLFORM_BUFFERPTR       12
#define TR_CURLFORM_BUFFERLENGTH    13
#define TR_CURLFORM_CONTENTTYPE     14
#define TR_CURLFORM_CONTENTHEADER   15
#define TR_CURLFORM_FILENAME        16
#define TR_CURLFORM_END             17
#define TR_CURLFORM_STREAM          19
#define TR_CURLFORM_CONTENTLEN      20

/* CURL_FORMADD_MEMORY (error_codes.rs / include/curl/curl.h). */
#define TR_CURL_FORMADD_MEMORY      1

/*
 * Layout-compatible with the Rust `#[repr(C)] curl_forms` (and curl's
 * `struct curl_forms`): an `int` option followed by a `const char *` value.
 */
struct tr_curl_forms {
  int option;
  const char *value;
};

/* Opaque to this translation unit; only ever used through pointers. */
struct curl_httppost;

/*
 * The non-variadic Rust implementation. Returns a CURLFORMcode (int).
 * Defined as `#[no_mangle] pub extern "C" fn curlrs_formadd_impl(...)`.
 */
extern int curlrs_formadd_impl(struct curl_httppost **httppost,
                               struct curl_httppost **last_post,
                               const struct tr_curl_forms *forms,
                               size_t count);

/* Ensure `*forms` has room for at least `need` entries; grows geometrically.
   Returns 1 on success, 0 on allocation failure. */
static int tr_ensure(struct tr_curl_forms **forms, size_t *cap, size_t need)
{
  struct tr_curl_forms *grown;
  size_t ncap;

  if(need <= *cap)
    return 1;

  ncap = *cap ? *cap : 8;
  while(ncap < need)
    ncap *= 2;

  grown = (struct tr_curl_forms *)realloc(*forms, ncap * sizeof(*grown));
  if(!grown)
    return 0;

  *forms = grown;
  *cap = ncap;
  return 1;
}

/*
 * curl_formadd() — the exported, ABI-compatible variadic entry point.
 *
 * Signature matches include/curl/curl.h exactly:
 *   CURLFORMcode curl_formadd(struct curl_httppost **httppost,
 *                             struct curl_httppost **last_post, ...);
 */
int curl_formadd(struct curl_httppost **httppost,
                 struct curl_httppost **last_post, ...)
{
  va_list args;
  struct tr_curl_forms *forms = NULL;
  size_t count = 0;
  size_t cap = 0;
  int option;
  int result;

  va_start(args, last_post);

  for(;;) {
    option = va_arg(args, int);

    if(!tr_ensure(&forms, &cap, count + 1))
      goto oom;

    forms[count].option = option;
    forms[count].value = NULL;

    if(option == TR_CURLFORM_END) {
      count++;
      goto done;
    }

    switch(option) {
    case TR_CURLFORM_NOTHING:
      /* no value */
      break;

    /* Length options are passed as `long` (curl's form_int_arg(long)). */
    case TR_CURLFORM_NAMELENGTH:
    case TR_CURLFORM_CONTENTSLENGTH:
    case TR_CURLFORM_BUFFERLENGTH:
      forms[count].value = (const char *)(uintptr_t)va_arg(args, long);
      break;

    /* CURLFORM_CONTENTLEN is a curl_off_t (64-bit) length. */
    case TR_CURLFORM_CONTENTLEN:
      forms[count].value = (const char *)(uintptr_t)va_arg(args, long long);
      break;

    /* Every other known option takes a single pointer-sized value. */
    case TR_CURLFORM_COPYNAME:
    case TR_CURLFORM_PTRNAME:
    case TR_CURLFORM_COPYCONTENTS:
    case TR_CURLFORM_PTRCONTENTS:
    case TR_CURLFORM_FILECONTENT:
    case TR_CURLFORM_ARRAY:
    case TR_CURLFORM_FILE:
    case TR_CURLFORM_BUFFER:
    case TR_CURLFORM_BUFFERPTR:
    case TR_CURLFORM_STREAM:
    case TR_CURLFORM_CONTENTTYPE:
    case TR_CURLFORM_CONTENTHEADER:
    case TR_CURLFORM_FILENAME:
      forms[count].value = va_arg(args, const char *);
      break;

    default:
      /*
       * Unknown option: we cannot know how many further arguments it would
       * consume, so we stop reading the va_list (exactly as curl's FormAdd
       * stops on an unknown option). Record the option with a NULL value and
       * append CURLFORM_END; the Rust side reports CURL_FORMADD_UNKNOWN_OPTION.
       */
      count++;
      if(!tr_ensure(&forms, &cap, count + 1))
        goto oom;
      forms[count].option = TR_CURLFORM_END;
      forms[count].value = NULL;
      count++;
      goto done;
    }

    count++;
  }

done:
  va_end(args);
  result = curlrs_formadd_impl(httppost, last_post, forms, count);
  free(forms);
  return result;

oom:
  va_end(args);
  free(forms);
  return TR_CURL_FORMADD_MEMORY;
}
