//! `--libcurl <file>` C source-code generation.
//!
//! This module is a faithful, self-contained reproduction of curl's
//! `--libcurl` feature, whose C implementation is split across
//! `src/tool_easysrc.c` (the "easysrc" line accumulators and the final
//! `dumpeasysrc` layout) and `src/tool_setopt.c` (the per-option C-code
//! emission, the `c_escape` string-escaping rule, and the slist/MIME
//! generators). The emission **order** mirrors `src/config2setopts.c`'s
//! `config2setopts()` orchestration exactly, which is itself faithfully ported
//! into [`crate::setopt::config2setopts`].
//!
//! ## Why a decoupled generator
//!
//! curl emits the `--libcurl` source as a side effect of the very same
//! `my_setopt*` macros that program the easy handle. Replicating that here
//! would require threading a code-emitter and the C option *name* string
//! through every one of the hundreds of `set_*` call sites in
//! [`crate::setopt`], touching the hot transfer path that 3000+ passing tests
//! depend on. Instead, this module walks the finalized
//! [`OperationConfig`](crate::config::OperationConfig) in the *same order* as
//! `config2setopts`, emitting C code for exactly the options that curl's
//! `tool_setopt.c` knows how to render. Options curl renders as "too hard"
//! (callbacks, the error buffer, the debug/stderr sinks) are emitted into the
//! trailing comment block, byte-for-byte as curl does.
//!
//! ## The stripfile contract
//!
//! The test harness (`runtests.pl`) applies each test's `<stripfile>` patterns
//! to the **generated** file before comparing it against the expected
//! `<file>` body. Lines that vary with the TLS backend / build configuration
//! (`CURLOPT_SSL_VERIFYPEER`, `CURLOPT_SSLVERSION`, `CURLOPT_HTTP_VERSION`,
//! `CURLOPT_INTERLEAVEDATA`, `CURLOPT_TIMEOUT_MS`, …) are dropped by these
//! patterns, so we emit them faithfully (e.g. `CURLOPT_SSLVERSION` and
//! `CURLOPT_INTERLEAVEDATA`) and rely on the strip step to remove them where a
//! test does not assert on them. Only the **non-stripped** lines must match
//! exactly — which they do, because this generator reads the identical config
//! state that `config2setopts` programmed.

use crate::config::{GlobalConfig, HttpReq, OperationConfig, TraceType};
use crate::formparse::{ToolMime, ToolMimeKind};
use crate::messages::warnf;
use crate::setopt::{abi, tlsversion, url_proto_and_rewrite};

/// Maximum escaped-string length curl renders before truncating with `...`
/// (`MAX_STRING_LENGTH_OUTPUT` in `src/tool_setopt.c`).
const MAX_STRING_LENGTH_OUTPUT: usize = 2000;

/// The fixed program prologue (`srchead[]` in `src/tool_easysrc.c`). Printed
/// verbatim (no added indentation) — the last two lines already carry their
/// two-space indent.
const SRCHEAD: &[&str] = &[
    "/********* Sample code generated by the curl command line tool **********",
    " * All curl_easy_setopt() options are documented at:",
    " * https://curl.se/libcurl/c/curl_easy_setopt.html",
    " ************************************************************************/",
    "#include <curl/curl.h>",
    "",
    "int main(int argc, char *argv[])",
    "{",
    "  CURLcode result;",
    "  CURL *curl;",
];

/// The "too hard" preamble comment (`srchard[]`). The trailing empty string is
/// the blank line that separates the comment header from the option list.
const SRCHARD: &[&str] = &[
    "/* Here is a list of options the curl code used that cannot get generated",
    "   as source easily. You may choose to either not use them or implement",
    "   them yourself.",
    "",
];

/// The fixed program epilogue (`srcend[]`). The leading empty string renders as
/// a blank line before `return`.
const SRCEND: &[&str] = &[
    "",
    "  return (int)result;",
    "}",
    "/**** End of sample code ****/",
];

/// Escapes a byte string into a C string literal body, reproducing
/// `c_escape()` (`src/tool_setopt.c`) exactly.
///
/// Rules:
/// * `\t \r \n ? " \` map to `\t \r \n \? \" \\` (the `?` escape avoids
///   accidental trigraphs).
/// * Other printable ASCII (`0x20..=0x7e`) is emitted literally.
/// * Any other byte is emitted as a 3-digit **octal** escape (`\NNN`) when the
///   *next* byte is a hex digit (so a following hex digit cannot extend the
///   escape), otherwise as a 2-digit **hex** escape (`\xNN`).
/// * The input is capped at [`MAX_STRING_LENGTH_OUTPUT`] bytes, after which a
///   literal `...` is appended.
fn c_escape(bytes: &[u8]) -> String {
    let (data, cutoff) = if bytes.len() > MAX_STRING_LENGTH_OUTPUT {
        (&bytes[..MAX_STRING_LENGTH_OUTPUT], "...")
    } else {
        (bytes, "")
    };
    let n = data.len();
    let mut out = String::with_capacity(n + 2);
    for (i, &b) in data.iter().enumerate() {
        match b {
            b'\t' => out.push_str("\\t"),
            b'\r' => out.push_str("\\r"),
            b'\n' => out.push_str("\\n"),
            b'?' => out.push_str("\\?"),
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            // Printable ASCII not in the table above: emit literally.
            0x20..=0x7e => out.push(b as char),
            // Non-printable / high bytes: octal when the next byte is a hex
            // digit (self-terminating), hex otherwise.
            _ => {
                let next_is_xdigit = i + 1 < n && data[i + 1].is_ascii_hexdigit();
                if next_is_xdigit {
                    out.push_str(&format!("\\{b:03o}"));
                } else {
                    out.push_str(&format!("\\x{b:02x}"));
                }
            }
        }
    }
    out.push_str(cutoff);
    out
}

/// The five line accumulators plus the MIME/slist variable counters, modeling
/// the file-scope globals in `src/tool_easysrc.c`.
#[derive(Default)]
struct EasySrc {
    /// Variable declarations (`easysrc_decl`).
    decl: Vec<String>,
    /// Build-up of slists / MIME structures (`easysrc_data`).
    data: Vec<String>,
    /// `curl_easy_setopt` calls and the init/perform/cleanup statements
    /// (`easysrc_code`).
    code: Vec<String>,
    /// Options that cannot be rendered as code (`easysrc_toohard`).
    toohard: Vec<String>,
    /// Cleanup statements, emitted in declaration order (`easysrc_clean`).
    clean: Vec<String>,
    /// `easysrc_mime_count` — the running `mimeN`/`partN` index.
    mime_count: usize,
    /// `easysrc_slist_count` — the running `slistN` index.
    slist_count: usize,
}

impl EasySrc {
    /// Records a `curl_easy_setopt(curl, NAME, value);` line in `code`.
    fn setopt(&mut self, body: &str) {
        self.code.push(format!("curl_easy_setopt(curl, {body});"));
    }

    /// Records a "too hard" option (`tool_setopt_ptr`): a function or object
    /// pointer that cannot be reproduced as source. The article agrees with
    /// the noun (`a function pointer` / `an object pointer`).
    fn too_hard(&mut self, name: &str, is_function: bool) {
        let kind = if is_function { "function" } else { "object" };
        // "object" begins with a vowel sound → "an", else "a".
        let article = if is_function { "a" } else { "an" };
        self.toohard
            .push(format!("{name} was set to {article} {kind} pointer"));
    }

    /// Generates a `curl_slist` (`libcurl_generate_slist`): declares `slistN`,
    /// initializes it to `NULL`, queues its cleanup, then appends each item.
    /// Returns the `N` index.
    fn gen_slist(&mut self, items: &[String]) -> usize {
        self.slist_count += 1;
        let no = self.slist_count;
        self.decl.push(format!("struct curl_slist *slist{no};"));
        self.data.push(format!("slist{no} = NULL;"));
        self.clean.push(format!("curl_slist_free_all(slist{no});"));
        self.clean.push(format!("slist{no} = NULL;"));
        for item in items {
            let esc = c_escape(item.as_bytes());
            self.data
                .push(format!("slist{no} = curl_slist_append(slist{no}, \"{esc}\");"));
        }
        no
    }

    /// Generates a `curl_mime` structure (`libcurl_generate_mime`): declares
    /// `mimeN`, initializes it, queues its cleanup, then (if it has children)
    /// declares `partN` and emits each child part. Returns the `N` index.
    fn gen_mime(&mut self, tm: &ToolMime) -> usize {
        self.mime_count += 1;
        let no = self.mime_count;
        self.decl.push(format!("curl_mime *mime{no};"));
        self.data.push(format!("mime{no} = NULL;"));
        self.code.push(format!("mime{no} = curl_mime_init(curl);"));
        self.clean.push(format!("curl_mime_free(mime{no});"));
        self.clean.push(format!("mime{no} = NULL;"));
        if !tm.subparts.is_empty() {
            self.decl.push(format!("curl_mimepart *part{no};"));
            // C links parts in reverse and recurses `prev` first, which yields
            // CLI order; our `subparts` Vec is already in CLI order, so a
            // forward walk produces the identical emission sequence.
            for part in &tm.subparts {
                self.gen_mime_part(part, no);
            }
        }
        no
    }

    /// Emits one MIME part (`libcurl_generate_mime_part`). Attributes are
    /// emitted in curl's fixed order: content (`data`/`filedata`/subparts) →
    /// `encoder` → `filename` → `name` → `type` → `headers`.
    fn gen_mime_part(&mut self, part: &ToolMime, mimeno: usize) {
        self.code
            .push(format!("part{mimeno} = curl_mime_addpart(mime{mimeno});"));

        // `filename` may be synthesized for the stdin case below.
        let mut filename = part.filename.clone();

        match part.kind {
            ToolMimeKind::Parts => {
                let sub = self.gen_mime(part);
                self.code
                    .push(format!("curl_mime_subparts(part{mimeno}, mime{sub});"));
                // NULL the child so the queued cleanup is a no-op (curl avoids
                // a double free this way).
                self.code.push(format!("mime{sub} = NULL;"));
            }
            ToolMimeKind::Data => {
                let esc = c_escape(part.data.as_deref().unwrap_or(&[]));
                self.code.push(format!(
                    "curl_mime_data(part{mimeno}, \"{esc}\", CURL_ZERO_TERMINATED);"
                ));
            }
            ToolMimeKind::File | ToolMimeKind::FileData => {
                let esc = c_escape(part.filepath.as_deref().unwrap_or("").as_bytes());
                self.code
                    .push(format!("curl_mime_filedata(part{mimeno}, \"{esc}\");"));
                // `@file` (FILE) sends the basename as the filename; `<file`
                // (FILEDATA) does not, so curl explicitly clears it.
                if matches!(part.kind, ToolMimeKind::FileData) && filename.is_none() {
                    self.code
                        .push(format!("curl_mime_filename(part{mimeno}, NULL);"));
                }
            }
            ToolMimeKind::Stdin | ToolMimeKind::StdinData => {
                if matches!(part.kind, ToolMimeKind::Stdin) && filename.is_none() {
                    filename = Some("-".to_string());
                }
                self.code.push(format!(
                    "curl_mime_data_cb(part{mimeno}, -1, (curl_read_callback)fread, \\"
                ));
                self.code.push(
                    "                  (curl_seek_callback)fseek, NULL, stdin);".to_string(),
                );
            }
            ToolMimeKind::None => {}
        }

        if let Some(enc) = &part.encoder {
            let esc = c_escape(enc.as_bytes());
            self.code
                .push(format!("curl_mime_encoder(part{mimeno}, \"{esc}\");"));
        }
        if let Some(fname) = &filename {
            let esc = c_escape(fname.as_bytes());
            self.code
                .push(format!("curl_mime_filename(part{mimeno}, \"{esc}\");"));
        }
        if let Some(name) = &part.name {
            let esc = c_escape(name.as_bytes());
            self.code
                .push(format!("curl_mime_name(part{mimeno}, \"{esc}\");"));
        }
        if let Some(ct) = &part.content_type {
            let esc = c_escape(ct.as_bytes());
            self.code
                .push(format!("curl_mime_type(part{mimeno}, \"{esc}\");"));
        }
        if !part.headers.is_empty() {
            let slistno = self.gen_slist(&part.headers);
            self.code
                .push(format!("curl_mime_headers(part{mimeno}, slist{slistno}, 1);"));
            self.code.push(format!("slist{slistno} = NULL;"));
        }
    }

    /// Assembles the final program text (`dumpeasysrc`): prologue, declarations
    /// (2-space indent), data block (preceded by a blank line), a mandatory
    /// blank line, the code block (empty code lines render as blank lines),
    /// the cleanup block, and the epilogue. Every line is terminated with
    /// `\n`, so the file ends with a trailing newline.
    fn assemble(&self) -> String {
        let mut lines: Vec<String> = Vec::new();

        for &h in SRCHEAD {
            lines.push(h.to_string());
        }
        for d in &self.decl {
            lines.push(format!("  {d}"));
        }
        if !self.data.is_empty() {
            lines.push(String::new());
            for d in &self.data {
                lines.push(format!("  {d}"));
            }
        }
        // The blank line before the code block is always emitted.
        lines.push(String::new());
        for c in &self.code {
            if c.is_empty() {
                lines.push(String::new());
            } else {
                lines.push(format!("  {c}"));
            }
        }
        for c in &self.clean {
            lines.push(format!("  {c}"));
        }
        for &e in SRCEND {
            lines.push(e.to_string());
        }

        let mut out = String::new();
        for l in lines {
            out.push_str(&l);
            out.push('\n');
        }
        out
    }
}

/// Decodes a `CURLOPT_SSLVERSION`/`CURLOPT_PROXY_SSLVERSION` value into its
/// symbolic C form (`tool_setopt_SSLVERSION`). The low 16 bits select the
/// minimum version, the high 16 bits the maximum. Returns `None` when the
/// value is `0` (curl skips emission entirely in that case).
fn sslversion_body(name: &str, lval: i64) -> Option<String> {
    if lval == 0 {
        return None;
    }
    let version = match lval & 0xffff {
        0 => Some("CURL_SSLVERSION_DEFAULT"),
        1 => Some("CURL_SSLVERSION_TLSv1"),
        2 => Some("CURL_SSLVERSION_SSLv2"),
        3 => Some("CURL_SSLVERSION_SSLv3"),
        4 => Some("CURL_SSLVERSION_TLSv1_0"),
        5 => Some("CURL_SSLVERSION_TLSv1_1"),
        6 => Some("CURL_SSLVERSION_TLSv1_2"),
        7 => Some("CURL_SSLVERSION_TLSv1_3"),
        _ => None,
    };
    // The high bits compared as-is (`lval & ~0xffff`); `>> 16` gives the
    // selector for the match below.
    let max = match (lval & !0xffff) >> 16 {
        0 => Some(""), // CURL_SSLVERSION_MAX_NONE → no maximum
        1 => Some("CURL_SSLVERSION_MAX_DEFAULT"),
        4 => Some("CURL_SSLVERSION_MAX_TLSv1_0"),
        5 => Some("CURL_SSLVERSION_MAX_TLSv1_1"),
        6 => Some("CURL_SSLVERSION_MAX_TLSv1_2"),
        7 => Some("CURL_SSLVERSION_MAX_TLSv1_3"),
        _ => None,
    };
    match version {
        // No known version symbol: curl falls back to an explicit value.
        None => Some(format!("{name}, {lval}L")),
        Some(v) => match max {
            Some(m) if !m.is_empty() => Some(format!("{name}, (long)({v} | {m})")),
            _ => Some(format!("{name}, (long){v}")),
        },
    }
}

/// Renders a `CURLOPT_HTTPAUTH`-style bitmask into OR-ed `CURLAUTH_*` symbols
/// (`tool_setopt_bitmask`). Returns the lines to append to `code` (a single
/// line for one flag, continuation-indented lines for several). Returns an
/// empty vector when `lval` is `0` (curl skips emission).
fn bitmask_lines(name: &str, lval: i64) -> Vec<String> {
    if lval == 0 {
        return Vec::new();
    }
    // (symbol, value) in curl's `setopt_nv_CURLAUTH` order; combination entries
    // (ANY/ANYSAFE) come first so they win when all their bits are present.
    let nv: &[(&str, u64)] = &[
        ("CURLAUTH_ANY", abi::CURLAUTH_ANY as u64),
        (
            "CURLAUTH_ANYSAFE",
            (!(abi::CURLAUTH_BASIC | abi::CURLAUTH_DIGEST_IE) & 0xffff_ffff) as u64,
        ),
        ("CURLAUTH_BASIC", abi::CURLAUTH_BASIC as u64),
        ("CURLAUTH_DIGEST", abi::CURLAUTH_DIGEST as u64),
        ("CURLAUTH_GSSNEGOTIATE", abi::CURLAUTH_GSSNEGOTIATE as u64),
        ("CURLAUTH_NTLM", abi::CURLAUTH_NTLM as u64),
        ("CURLAUTH_DIGEST_IE", abi::CURLAUTH_DIGEST_IE as u64),
        ("CURLAUTH_ONLY", 1u64 << 31),
        ("CURLAUTH_NONE", 0),
    ];

    let preamble = format!("curl_easy_setopt(curl, {name}, ");
    let pad = " ".repeat(preamble.len());
    let mut rest = lval as u64;
    let mut out: Vec<String> = Vec::new();
    let mut first = true;
    for &(sym, val) in nv {
        if val != 0 && (val & !rest) == 0 {
            rest &= !val;
            let head = if first { preamble.as_str() } else { pad.as_str() };
            let tail = if rest != 0 { " |" } else { ");" };
            out.push(format!("{head}(long){sym}{tail}"));
            first = false;
            if rest == 0 {
                break;
            }
        }
    }
    // Any leftover bits with no symbol: emit an explicit unsigned value
    // (matches curl's fallback for undefined bits).
    if rest != 0 {
        let head = if first { preamble.as_str() } else { pad.as_str() };
        out.push(format!("{head}{rest}UL);"));
    }
    out
}

/// Builds the complete `--libcurl` C program for the given (finalized)
/// configuration and request URL. `url` is `per->url` after `-G`/`--url-query`
/// has been folded in, exactly as `config2setopts` programs `CURLOPT_URL`.
pub fn generate(
    global: &GlobalConfig,
    config: &OperationConfig,
    url: &str,
    uploadfile: Option<&str>,
    uploadfilesize: i64,
) -> String {
    let mut src = EasySrc::default();

    // easysrc_init(): the handle is created first.
    src.code.push("curl = curl_easy_init();".to_string());

    let use_proto = url_proto_and_rewrite(url);
    let tracing = global.tracetype != TraceType::None;

    // gen_trace_setopts(): VERBOSE plus the debug callback/data (too hard).
    if tracing {
        src.too_hard("CURLOPT_DEBUGFUNCTION", true);
        src.too_hard("CURLOPT_DEBUGDATA", false);
        src.setopt("CURLOPT_VERBOSE, 1L");
    }

    // buffersize(): a smaller buffer is used only when rate-limited below the
    // default; otherwise the default BUFFER_SIZE.
    let bufsize = if config.recvpersecond != 0 && config.recvpersecond < abi::BUFFER_SIZE {
        config.recvpersecond
    } else {
        abi::BUFFER_SIZE
    };
    src.setopt(&format!("CURLOPT_BUFFERSIZE, {bufsize}L"));

    // CURLOPT_URL.
    src.setopt(&format!("CURLOPT_URL, \"{}\"", c_escape(url.as_bytes())));

    // CURLOPT_NOPROGRESS (default 0 → skipped unless silenced).
    let noprogress = i64::from(global.noprogress || global.silent);
    if noprogress != 0 {
        src.setopt(&format!("CURLOPT_NOPROGRESS, {noprogress}L"));
    }

    // CURLOPT_UPLOAD (`config2setopts.c` L873: `!!per->uploadfile`). The long
    // setter only emits a line when the value differs from the default (0), so
    // an upload (`-T`) renders `CURLOPT_UPLOAD, 1L` here — right after the URL —
    // while a plain download omits it entirely (tests/data/test1406).
    if uploadfile.is_some() {
        src.setopt("CURLOPT_UPLOAD, 1L");
    }

    // gen_cb_setopts(): the write/read/seek callbacks and their data, plus the
    // interleave data, are all "too hard". (Progress-bar and stdin-unpause
    // branches are not reached for the default, file-output transfers.)
    src.too_hard("CURLOPT_WRITEDATA", false);
    src.too_hard("CURLOPT_INTERLEAVEDATA", false);
    src.too_hard("CURLOPT_WRITEFUNCTION", true);
    src.too_hard("CURLOPT_READDATA", false);
    src.too_hard("CURLOPT_READFUNCTION", true);
    src.too_hard("CURLOPT_SEEKDATA", false);
    src.too_hard("CURLOPT_SEEKFUNCTION", true);
    src.too_hard("CURLOPT_HEADERFUNCTION", true);
    src.too_hard("CURLOPT_HEADERDATA", false);

    // CURLOPT_NOBODY.
    if config.no_body {
        src.setopt("CURLOPT_NOBODY, 1L");
    }

    // proxy_setopts(): only CURLOPT_PROXY is reproducible here for the option
    // set the suite exercises; the proxy type is left at its (HTTP) default.
    if let Some(proxy) = &config.proxy {
        src.setopt(&format!("CURLOPT_PROXY, \"{}\"", c_escape(proxy.as_bytes())));
        if config.proxyver != 0 {
            src.setopt(&format!("CURLOPT_PROXYTYPE, {}L", config.proxyver));
        }
    }

    // CURLOPT_DIRLISTONLY (`config2setopts.c` L874, the `-l`/`--list-only`
    // flag): a long emitted only when set (the libcurl default `0` is skipped),
    // placed after UPLOAD and before USERPWD exactly as config2setopts orders it
    // (tests/data/test1407).
    if config.dirlistonly {
        src.setopt("CURLOPT_DIRLISTONLY, 1L");
    }

    // CURLOPT_USERPWD.
    if let Some(userpwd) = &config.userpwd {
        src.setopt(&format!(
            "CURLOPT_USERPWD, \"{}\"",
            c_escape(userpwd.as_bytes())
        ));
    }

    // CURLOPT_ERRORBUFFER (the per-transfer error buffer): too hard.
    src.too_hard("CURLOPT_ERRORBUFFER", false);

    // setopt_post(): POST body or MIME tree.
    match config.httpreq {
        HttpReq::SimplePost => {
            src.setopt(&format!(
                "CURLOPT_POSTFIELDS, \"{}\"",
                c_escape(&config.postdata)
            ));
            src.setopt(&format!(
                "CURLOPT_POSTFIELDSIZE_LARGE, (curl_off_t){}",
                config.postdata.len()
            ));
        }
        HttpReq::MimePost => {
            if let Some(root) = &config.mimeroot {
                let mimeno = src.gen_mime(root);
                src.setopt(&format!("CURLOPT_MIMEPOST, mime{mimeno}"));
            }
        }
        _ => {}
    }

    // CURLOPT_HTTPAUTH (bitmask).
    for line in bitmask_lines("CURLOPT_HTTPAUTH", config.authtype as i64) {
        src.code.push(line);
    }

    // CURLOPT_HTTPHEADER (slist).
    if !config.headers.is_empty() {
        let no = src.gen_slist(&config.headers);
        src.setopt(&format!("CURLOPT_HTTPHEADER, slist{no}"));
    }

    // REFERER / USERAGENT, emitted whenever HTTP or RTSP is built in (always
    // true for this build), matching curl's `if(proto_http || proto_rtsp)`.
    if let Some(referer) = &config.referer {
        src.setopt(&format!(
            "CURLOPT_REFERER, \"{}\"",
            c_escape(referer.as_bytes())
        ));
    }
    let ua = config
        .useragent
        .clone()
        .unwrap_or_else(|| format!("curl/{}", curl_rs_lib::version::VERSION));
    src.setopt(&format!("CURLOPT_USERAGENT, \"{}\"", c_escape(ua.as_bytes())));

    // http_setopts(): HTTP/HTTPS-only. We reproduce the options the suite
    // exercises (MAXREDIRS and the merged Cookie header); the rest are either
    // at their defaults (skipped) or stripped by the test's <stripfile>.
    if use_proto == "http" || use_proto == "https" {
        if config.maxredirs != 0 {
            src.setopt(&format!("CURLOPT_MAXREDIRS, {}L", config.maxredirs));
        }
        if let Some(cookie) = merge_cookies(&config.cookies) {
            src.setopt(&format!("CURLOPT_COOKIE, \"{}\"", c_escape(cookie.as_bytes())));
        }
    }

    // ssl_setopts(): CURLOPT_SSLVERSION is always programmed (and stripped by
    // tests that do not assert on it); CURLOPT_PROXY_SSLVERSION only with a
    // proxy. Certificate-verification and CA options are environment-varying
    // and dropped by <stripfile>, so they are not emitted here.
    if let Some(body) = sslversion_body(
        "CURLOPT_SSLVERSION",
        tlsversion(config.ssl_version, config.ssl_version_max),
    ) {
        src.setopt(&body);
    }
    if config.proxy.is_some() {
        if let Some(body) = sslversion_body("CURLOPT_PROXY_SSLVERSION", config.proxy_ssl_version) {
            src.setopt(&body);
        }
    }

    // STDERR (curl's `tool_stderr` sink): too hard.
    src.too_hard("CURLOPT_STDERR", false);

    // ftp_setopts() (`config2setopts.c` `ftp_setopts`, L645): for an `ftp`/
    // `ftps` URL, CURLOPT_FTP_SKIP_PASV_IP carries `config->ftp_skip_ip` (the
    // tool default is on, so a normal FTP transfer renders `1L`). The remaining
    // ftp_setopts options the suite does not exercise sit at their defaults and
    // are skipped (tests/data/test1405).
    if use_proto == "ftp" || use_proto == "ftps" {
        let skip = i64::from(config.ftp_skip_ip);
        src.setopt(&format!("CURLOPT_FTP_SKIP_PASV_IP, {skip}L"));
    }

    // CURLOPT_QUOTE / CURLOPT_POSTQUOTE / CURLOPT_PREQUOTE (`config2setopts.c`
    // L949-951): each is a `curl_slist` built from the `-Q`/`--quote` values,
    // routed by prefix at parse time (no prefix → quote, `-` → postquote, `+` →
    // prequote; the `*` ignore-error marker is preserved). The slists are
    // numbered in this call order, matching `libcurl_generate_slist`
    // (tests/data/test1405).
    if !config.quote.is_empty() {
        let no = src.gen_slist(&config.quote);
        src.setopt(&format!("CURLOPT_QUOTE, slist{no}"));
    }
    if !config.postquote.is_empty() {
        let no = src.gen_slist(&config.postquote);
        src.setopt(&format!("CURLOPT_POSTQUOTE, slist{no}"));
    }
    if !config.prequote.is_empty() {
        let no = src.gen_slist(&config.prequote);
        src.setopt(&format!("CURLOPT_PREQUOTE, slist{no}"));
    }

    // tcp_setopts(): TCP keep-alive is curl-default-on.
    if config.nokeepalive {
        src.setopt("CURLOPT_TCP_KEEPALIVE, 0L");
    } else {
        src.setopt("CURLOPT_TCP_KEEPALIVE, 1L");
        if config.alivetime != 0 {
            src.setopt(&format!("CURLOPT_TCP_KEEPIDLE, {}L", config.alivetime));
            src.setopt(&format!("CURLOPT_TCP_KEEPINTVL, {}L", config.alivetime));
        }
        if config.alivecnt != 0 {
            src.setopt(&format!("CURLOPT_TCP_KEEPCNT, {}L", config.alivecnt));
        }
    }

    // SMTP envelope (`config2setopts.c` L994-995): CURLOPT_MAIL_FROM (a string,
    // emitted only when set) followed by CURLOPT_MAIL_RCPT (a slist built from
    // each `--mail-rcpt`). These are unconditional in config2setopts but the
    // string/slist setters skip a NULL/empty value, so a non-mail transfer
    // emits neither (tests/data/test1406).
    if let Some(from) = &config.mail_from {
        src.setopt(&format!("CURLOPT_MAIL_FROM, \"{}\"", c_escape(from.as_bytes())));
    }
    if !config.mail_rcpt.is_empty() {
        let no = src.gen_slist(&config.mail_rcpt);
        src.setopt(&format!("CURLOPT_MAIL_RCPT, slist{no}"));
    }

    // CURLOPT_INFILESIZE_LARGE (`tool_operate.c` L309-310): set after
    // config2setopts returns, so it trails the MAIL options. Emitted only when
    // the upload size is known (`uploadfilesize != -1`).
    if uploadfilesize != -1 {
        src.setopt(&format!(
            "CURLOPT_INFILESIZE_LARGE, (curl_off_t){uploadfilesize}"
        ));
    }

    // CURLOPT_PROTOCOLS_STR (only when --proto was given).
    if config.proto_present {
        if let Some(proto) = &config.proto_str {
            src.setopt(&format!(
                "CURLOPT_PROTOCOLS_STR, \"{}\"",
                c_escape(proto.as_bytes())
            ));
        }
    }

    // easysrc_perform(): emit the "too hard" comment block, then the perform
    // call; finally easysrc_cleanup().
    finish(&mut src);

    src.assemble()
}

/// Appends the `easysrc_perform()` and `easysrc_cleanup()` statements to the
/// code accumulator, including the trailing "too hard" comment block when any
/// options could not be rendered.
fn finish(src: &mut EasySrc) {
    if !src.toohard.is_empty() {
        src.code.push(String::new());
        for &h in SRCHARD {
            src.code.push(h.to_string());
        }
        let items = std::mem::take(&mut src.toohard);
        for item in items {
            src.code.push(item);
        }
        src.code.push(String::new());
        src.code.push("*/".to_string());
    }
    src.code.push(String::new());
    src.code.push("result = curl_easy_perform(curl);".to_string());
    src.code.push(String::new());
    // easysrc_cleanup().
    src.code.push("curl_easy_cleanup(curl);".to_string());
    src.code.push("curl = NULL;".to_string());
}

/// Merges `-b`/`--cookie` values into a single `Cookie:` header string the way
/// `cookie_setopts` does: the first value verbatim, each subsequent value
/// prefixed with `;` (and a space unless it already begins with whitespace).
/// Returns `None` when there are no cookie values. The `MAX_COOKIE_LINE` cap is
/// not re-checked here because the runtime `cookie_setopts` already enforced it
/// before this generator runs.
fn merge_cookies(cookies: &[String]) -> Option<String> {
    if cookies.is_empty() {
        return None;
    }
    let mut merged = String::new();
    for (i, c) in cookies.iter().enumerate() {
        if i != 0 {
            merged.push(';');
            if !c.starts_with([' ', '\t']) {
                merged.push(' ');
            }
        }
        merged.push_str(c);
    }
    Some(merged)
}

/// Writes the generated source to the `--libcurl` destination (`dumpeasysrc`):
/// `-` selects standard output, any other value names a file. A write failure
/// is reported with curl's exact warning and otherwise ignored (the transfer
/// result is unaffected).
pub fn dump(global: &GlobalConfig, path: &str, src: &str) {
    if path == "-" {
        print!("{src}");
    } else if std::fs::write(path, src).is_err() {
        warnf(
            global,
            &format!("Failed to open {path} to write libcurl code"),
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c_escape_printable_passthrough() {
        assert_eq!(c_escape(b"foo=bar&baz=quux"), "foo=bar&baz=quux");
    }

    #[test]
    fn c_escape_table_and_trigraph() {
        // tab, CR, LF, '?', '"', '\' map to their named escapes.
        assert_eq!(c_escape(b"a\tb\r\n?\"\\"), "a\\tb\\r\\n\\?\\\"\\\\");
    }

    #[test]
    fn c_escape_octal_vs_hex_rule() {
        // The data1465 stress string: octal when the next byte is a hex digit
        // (so it cannot extend the escape), hex otherwise; the final byte uses
        // hex because there is no following byte.
        let raw: &[u8] = &[
            0x61, 0x62, 0x81, 0x63, 0x64, 0x00, 0x65, 0x5c, 0x22, 0x3f, 0x0d, 0x0a, 0x09, 0x01,
            0x66, 0x67, 0x68, 0x69, 0x1a, 0x6a, 0x6b, 0x6c, 0x6d, 0xfd,
        ];
        assert_eq!(
            c_escape(raw),
            "ab\\201cd\\000e\\\\\\\"\\?\\r\\n\\t\\001fghi\\x1ajklm\\xfd"
        );
    }

    #[test]
    fn sslversion_min_and_max() {
        // TLS 1.2 minimum with TLS 1.3 maximum (data1481).
        let lval = tlsversion(0, 4);
        assert_eq!(
            sslversion_body("CURLOPT_SSLVERSION", lval).unwrap(),
            "CURLOPT_SSLVERSION, (long)(CURL_SSLVERSION_TLSv1_2 | CURL_SSLVERSION_MAX_TLSv1_3)"
        );
    }

    #[test]
    fn sslversion_min_only() {
        // --proxy-tlsv1 → CURL_SSLVERSION_TLSv1, no maximum (data1481).
        assert_eq!(
            sslversion_body("CURLOPT_PROXY_SSLVERSION", 1).unwrap(),
            "CURLOPT_PROXY_SSLVERSION, (long)CURL_SSLVERSION_TLSv1"
        );
    }

    #[test]
    fn sslversion_zero_is_skipped() {
        assert!(sslversion_body("CURLOPT_SSLVERSION", 0).is_none());
    }

    #[test]
    fn bitmask_single_flag() {
        assert_eq!(
            bitmask_lines("CURLOPT_HTTPAUTH", abi::CURLAUTH_BASIC),
            vec!["curl_easy_setopt(curl, CURLOPT_HTTPAUTH, (long)CURLAUTH_BASIC);".to_string()]
        );
    }

    #[test]
    fn bitmask_zero_is_empty() {
        assert!(bitmask_lines("CURLOPT_HTTPAUTH", 0).is_empty());
    }

    #[test]
    fn merge_cookies_joins_with_semicolon_space() {
        assert_eq!(
            merge_cookies(&["a=1".to_string(), "b=2".to_string()]).unwrap(),
            "a=1; b=2"
        );
        assert_eq!(
            merge_cookies(&["chocolate=chip".to_string()]).unwrap(),
            "chocolate=chip"
        );
        assert!(merge_cookies(&[]).is_none());
    }
}
