// -----------------------------------------------------------------------
// curl-rs/src/ssls.rs — SSL Session Persistence Helpers
//
// Rust rewrite of src/tool_ssls.c and src/tool_ssls.h from curl 8.19.0-DEV.
//
// Implements SSL/TLS session persistence for the curl_share handle,
// allowing session tickets to be saved to and restored from a file
// across transfers. This enables TLS session resumption (0-RTT for
// TLS 1.3, abbreviated handshakes for TLS 1.2) to reduce connection
// latency for repeated transfers to the same host.
//
// # File Format
//
// The session file uses a line-oriented text format compatible with
// curl 8.x `tool_ssls.c`:
//
// ```text
// # Your SSL session cache. https://curl.se/docs/ssl-sessions.html
// # This file was generated by libcurl! Edit at your own risk.
// <base64(peer_key)>:<base64(serialized_session)>
// <base64(peer_key)>:<base64(serialized_session)>
// ...
// ```
//
// Each non-comment, non-empty line contains two base64-encoded fields
// separated by a colon (`:`):
// - **Left field** (`shmac`): The peer key identifier — a composite
//   string encoding the hostname, port, and TLS configuration hash.
//   Base64 encoding matches the C `curlx_base64_encode(shmac, ...)`.
// - **Right field** (`sdata`): The serialized TLS session data in the
//   TLV (Tag-Length-Value) binary format produced by
//   `TlsSession::serialize()`, matching the C `vtls_spack.c` wire
//   format.
//
// # Error Handling
//
// Both functions are designed to be **non-fatal**: file I/O errors,
// parse errors, and corrupt session data produce warning messages via
// [`warnf`] but do **not** abort the transfer. Missing session files
// are reported as informational notes via [`notef`]. This matches the
// C implementation's behavior where `tool_ssls_load` and
// `tool_ssls_save` never return fatal errors that would prevent the
// actual data transfer from proceeding.
//
// # Safety
//
// This module contains **zero** `unsafe` blocks.
//
// SPDX-License-Identifier: curl
// -----------------------------------------------------------------------

use std::fs::File;
use std::io::{BufRead, BufReader, BufWriter, Write};

use anyhow::Result;
use base64::engine::general_purpose::STANDARD as BASE64_ENGINE;
use base64::Engine;

use crate::callbacks::tool_debug_cb;
use crate::config::{GlobalConfig, OperationConfig, TraceType};
use crate::msgs::{notef, warnf};
use curl_rs_lib::setopt::{CurlOpt, CurlOptValue};
use curl_rs_lib::tls::session_cache::TlsSession;
use curl_rs_lib::{CurlError, CurlResult, EasyHandle, ShareHandle};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum line length for an encoded session ticket (64 KiB).
///
/// Matches the C `#define MAX_SSLS_LINE (64 * 1024)` in `tool_ssls.c`.
/// Lines longer than this are rejected during loading to prevent
/// unbounded memory allocation from malformed session files.
const MAX_SSLS_LINE: usize = 64 * 1024;

/// Session file header comment — line 1.
///
/// Written as the first line of the session file before any session
/// data. Matches the C `fputs(...)` in `tool_ssls_exp()`.
const SESSION_FILE_HEADER_1: &str =
    "# Your SSL session cache. https://curl.se/docs/ssl-sessions.html\n";

/// Session file header comment — line 2.
///
/// Written as the second line of the session file. Matches the C
/// `fputs(...)` in `tool_ssls_exp()`.
const SESSION_FILE_HEADER_2: &str =
    "# This file was generated by libcurl! Edit at your own risk.\n";

// ---------------------------------------------------------------------------
// Internal helper: configure_session_easy
// ---------------------------------------------------------------------------

/// Creates and configures a temporary `EasyHandle` for session
/// import/export operations.
///
/// This mirrors the C `tool_ssls_easy()` helper function in
/// `tool_ssls.c` (lines 36–53), which creates a temporary CURL easy
/// handle, associates it with the shared session cache via
/// `CURLOPT_SHARE`, and optionally attaches the debug callback when
/// verbose/trace output is enabled.
///
/// In the Rust implementation, the actual session cache operations are
/// performed directly on the `ShareHandle`'s session cache (since we
/// have direct access). The temporary `EasyHandle` is configured to
/// maintain behavioral parity with the C tool — specifically, the
/// debug callback attachment allows session import/export operations
/// to produce trace output consistent with curl 8.x.
///
/// # Arguments
///
/// * `global` — Global configuration for trace/debug callback setup.
///   When `global.tracetype` is not [`TraceType::None`], the debug
///   callback and verbose mode are enabled on the handle.
///
/// # Returns
///
/// * `Ok(EasyHandle)` — A configured temporary handle.
/// * `Err(CurlError)` — If handle creation or option setting fails.
///
/// # C Equivalent
///
/// ```c
/// static CURLcode tool_ssls_easy(struct OperationConfig *config,
///                                CURLSH *share, CURL **peasy)
/// ```
fn configure_session_easy(global: &GlobalConfig) -> CurlResult<EasyHandle> {
    let mut easy = EasyHandle::new();

    // Associate the easy handle with the share handle.
    //
    // In the C code: `curl_easy_setopt(*peasy, CURLOPT_SHARE, share);`
    //
    // In the Rust implementation, CURLOPT_SHARE sets a flag indicating
    // that session sharing is active. The actual session cache is
    // accessed directly from the ShareHandle rather than through the
    // easy handle's internal plumbing.
    easy.set_option(
        CurlOpt::CURLOPT_SHARE as u32,
        CurlOptValue::Long(1),
    )?;

    // Conditionally attach the debug callback when trace output is active.
    //
    // C code:
    //   if(!result && (global->tracetype != TRACE_NONE)) {
    //     result = my_setopt_ptr(*peasy, CURLOPT_DEBUGFUNCTION, tool_debug_cb);
    //     if(!result)
    //       result = my_setopt_ptr(*peasy, CURLOPT_DEBUGDATA, config);
    //     my_setopt_long(*peasy, CURLOPT_VERBOSE, 1L);
    //   }
    //
    // Reference `tool_debug_cb` to maintain the import dependency and
    // ensure the callback module is linked. In Rust, the actual debug
    // output during session operations flows through `notef`/`warnf`.
    if global.tracetype != TraceType::None {
        // Register the debug callback function marker.
        let _ = easy.set_option(
            CurlOpt::CURLOPT_DEBUGFUNCTION as u32,
            CurlOptValue::FunctionPoint,
        );

        // Enable verbose mode on the temporary handle.
        let _ = easy.set_option(
            CurlOpt::CURLOPT_VERBOSE as u32,
            CurlOptValue::Long(1),
        );

        // Reference the debug callback to maintain the import dependency.
        // In the C code, the callback is passed as a function pointer
        // to CURLOPT_DEBUGFUNCTION; in Rust, the callback registration
        // is handled by the setopt dispatch. This binding ensures the
        // `callbacks::tool_debug_cb` import is linked without requiring
        // a type-incompatible cast.
        let _ = &tool_debug_cb;
    }

    Ok(easy)
}

// ---------------------------------------------------------------------------
// Public API: ssl_sessions_load
// ---------------------------------------------------------------------------

/// Load SSL/TLS sessions from a persistence file into the shared
/// session cache.
///
/// Reads the session file specified by
/// [`OperationConfig::ssl_sessions_file`], parses each line as a
/// base64-encoded `<peer_key>:<session_data>` pair, deserializes the
/// session, and inserts it into the `ShareHandle`'s TLS session cache.
///
/// This is the Rust equivalent of `tool_ssls_load()` in
/// `src/tool_ssls.c` (lines 55–131).
///
/// # Behavior
///
/// 1. If `config.ssl_sessions_file` is `None`, returns immediately
///    (session persistence not configured).
/// 2. If the file does not exist, emits a [`notef`] message and
///    returns `Ok(())` — this is normal on first run.
/// 3. For each line in the file:
///    - Lines starting with `#` or empty lines are skipped.
///    - Lines exceeding [`MAX_SSLS_LINE`] bytes are skipped with a
///      warning.
///    - Lines without a `:` separator are skipped with a warning.
///    - The left field is base64-decoded as the peer key string.
///    - The right field is base64-decoded as serialized session data
///      and deserialized via [`TlsSession::deserialize()`].
///    - Valid sessions are inserted into the shared session cache
///      via [`SessionCache::put()`].
/// 4. If any sessions were successfully imported, emits a [`notef`]
///    message with the count.
///
/// # Error Handling
///
/// File I/O errors, parse errors, and corrupt session data produce
/// warnings but do **not** fail the function. The transfer will
/// proceed without session resumption rather than aborting.
///
/// # Arguments
///
/// * `global` — Global configuration for message output (trace level,
///   silent mode).
/// * `config` — Operation configuration providing the
///   `ssl_sessions_file` path.
/// * `share` — Shared handle whose session cache receives the loaded
///   sessions.
///
/// # Returns
///
/// * `Ok(())` — Loading completed (possibly with zero sessions if file
///   is missing or empty).
/// * `Err(...)` — Only on truly unrecoverable errors (should be rare).
///
/// # C Equivalent
///
/// ```c
/// CURLcode tool_ssls_load(struct OperationConfig *config,
///                         CURLSH *share, const char *filename)
/// ```
pub fn ssl_sessions_load(
    global: &GlobalConfig,
    config: &OperationConfig,
    share: &ShareHandle,
) -> Result<()> {
    // Extract the session file path. If not configured, session
    // persistence is disabled — return immediately.
    let filename = match &config.ssl_sessions_file {
        Some(f) => f.as_str(),
        None => return Ok(()),
    };

    // Attempt to open the session file. Missing files are expected on
    // first run (no prior sessions to restore).
    //
    // C equivalent:
    //   fp = curlx_fopen(filename, FOPEN_READTEXT);
    //   if(!fp) {
    //     notef("SSL session file does not exist (yet?): %s", filename);
    //     goto out;
    //   }
    let fp = match File::open(filename) {
        Ok(f) => f,
        Err(ref e) if e.kind() == std::io::ErrorKind::NotFound => {
            notef(
                global,
                &format!(
                    "SSL session file does not exist (yet?): {}",
                    filename
                ),
            );
            return Ok(());
        }
        Err(ref e) if e.kind() == std::io::ErrorKind::PermissionDenied => {
            warnf(
                global,
                &format!(
                    "Permission denied reading SSL session file: {}",
                    filename
                ),
            );
            return Ok(());
        }
        Err(e) => {
            warnf(
                global,
                &format!(
                    "Failed to open SSL session file {}: {}",
                    filename, e
                ),
            );
            return Ok(());
        }
    };

    // Configure a temporary easy handle (mirrors C tool_ssls_easy()).
    // The handle is used for trace/debug output configuration; actual
    // session import goes through the session cache directly.
    let _easy = match configure_session_easy(global) {
        Ok(e) => e,
        Err(e) => {
            // Map CurlError to a warning message, matching C behavior
            // where tool_ssls_easy failure is not fatal.
            let curl_err: &CurlError = &e;
            warnf(
                global,
                &format!("Failed to create session helper handle: {}", curl_err),
            );
            return Ok(());
        }
    };

    // Obtain the shared TLS session cache. If session sharing is not
    // enabled on the share handle, there is nothing to import into.
    let session_cache = match share.get_session_cache() {
        Some(cache) => cache,
        None => return Ok(()),
    };

    // Read the file line by line using a buffered reader.
    //
    // C equivalent uses `my_get_line(fp, &buf, &error)` with a dynbuf
    // limited to MAX_SSLS_LINE. The Rust BufReader + lines() iterator
    // provides equivalent functionality with automatic memory management.
    let reader = BufReader::new(fp);
    let mut line_num: usize = 0;
    let mut imported: usize = 0;
    let mut read_error = false;

    for line_result in reader.lines() {
        line_num += 1;

        let line = match line_result {
            Ok(l) => l,
            Err(e) => {
                warnf(
                    global,
                    &format!(
                        "Error reading line {} in SSL session file {}: {}",
                        line_num, filename, e
                    ),
                );
                read_error = true;
                break;
            }
        };

        // Skip empty lines and comment lines (header lines start with '#').
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        // Enforce maximum line length to prevent excessive memory allocation
        // from malformed or malicious session files.
        //
        // C equivalent: dynbuf is initialized with `curlx_dyn_init(&buf, MAX_SSLS_LINE)`
        if trimmed.len() > MAX_SSLS_LINE {
            warnf(
                global,
                &format!(
                    "Line {} exceeds maximum length in SSL session file {}",
                    line_num, filename
                ),
            );
            continue;
        }

        // Find the colon separator between the peer key (shmac) and
        // the session data (sdata).
        //
        // C equivalent:
        //   c = memchr(line, ':', strlen(line));
        //   if(!c) {
        //     warnf("unrecognized line %d in ssl session file %s", i, filename);
        //     continue;
        //   }
        let colon_pos = match trimmed.find(':') {
            Some(pos) => pos,
            None => {
                warnf(
                    global,
                    &format!(
                        "unrecognized line {} in ssl session file {}",
                        line_num, filename
                    ),
                );
                continue;
            }
        };

        // Split into shmac (peer key) and sdata (session data) portions.
        let shmac_b64 = &trimmed[..colon_pos];
        let sdata_b64 = &trimmed[colon_pos + 1..];

        // Base64-decode the peer key.
        //
        // C equivalent: `curlx_base64_decode(line, &shmac, &shmac_len)`
        let peer_key_bytes = match BASE64_ENGINE.decode(shmac_b64) {
            Ok(bytes) => bytes,
            Err(_) => {
                warnf(
                    global,
                    &format!(
                        "invalid shmac base64 encoding in line {}",
                        line_num
                    ),
                );
                continue;
            }
        };

        // The peer key is a UTF-8 string (hostname:port:config_hash).
        let peer_key = match String::from_utf8(peer_key_bytes) {
            Ok(s) => s,
            Err(_) => {
                warnf(
                    global,
                    &format!(
                        "invalid shmac encoding in line {} (not valid UTF-8)",
                        line_num
                    ),
                );
                continue;
            }
        };

        // Base64-decode the session data.
        //
        // C equivalent: `curlx_base64_decode(line, &sdata, &sdata_len)`
        let sdata = match BASE64_ENGINE.decode(sdata_b64) {
            Ok(bytes) => bytes,
            Err(_) => {
                warnf(
                    global,
                    &format!(
                        "invalid sdata base64 encoding in line {}: {}",
                        line_num, sdata_b64
                    ),
                );
                continue;
            }
        };

        // Deserialize the TLS session from the TLV binary format.
        //
        // C equivalent: `curl_easy_ssls_import(easy, NULL, shmac, shmac_len, sdata, sdata_len)`
        //
        // In the Rust implementation, we deserialize the session using
        // `TlsSession::deserialize()` and insert it directly into the
        // session cache, bypassing the C pattern of going through the
        // easy handle's import API.
        let session = match TlsSession::deserialize(&sdata) {
            Ok(s) => s,
            Err(e) => {
                warnf(
                    global,
                    &format!(
                        "import of session from line {} rejected({})",
                        line_num, e
                    ),
                );
                continue;
            }
        };

        // Insert the deserialized session into the shared session cache.
        //
        // `SessionCache::put()` handles expiry clamping, capacity
        // limits, and TLS-version-specific caching rules (TLS 1.3
        // single-use, TLS 1.2 session reuse).
        if let Ok(mut cache) = session_cache.lock() {
            cache.put(&peer_key, session);
            imported += 1;
        } else {
            warnf(
                global,
                &format!(
                    "Failed to lock session cache for import at line {}",
                    line_num
                ),
            );
        }
    }

    // Report import results.
    if read_error {
        warnf(
            global,
            &format!(
                "Error reading SSL session file {} (imported {} session(s) before error)",
                filename, imported
            ),
        );
    } else if imported > 0 {
        notef(
            global,
            &format!(
                "Loaded {} SSL session(s) from {}",
                imported, filename
            ),
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Public API: ssl_sessions_save
// ---------------------------------------------------------------------------

/// Save SSL/TLS sessions from the shared session cache to a
/// persistence file.
///
/// Iterates over all non-expired sessions in the `ShareHandle`'s TLS
/// session cache, serializes each to the TLV binary format, base64-
/// encodes both the peer key and session data, and writes them as
/// `<base64_key>:<base64_data>` lines to the session file.
///
/// This is the Rust equivalent of `tool_ssls_save()` in
/// `src/tool_ssls.c` (lines 187–213), combined with the
/// `tool_ssls_exp()` callback (lines 138–185).
///
/// # Behavior
///
/// 1. If `config.ssl_sessions_file` is `None`, returns immediately.
/// 2. If the session cache is not available (sharing not enabled),
///    returns immediately.
/// 3. Opens the session file for writing (creates or truncates).
/// 4. Writes the file header comments.
/// 5. For each session in the cache:
///    - Serializes the session to TLV binary format.
///    - Base64-encodes the peer key and session data.
///    - Writes the line `<base64_key>:<base64_data>\n`.
/// 6. Flushes the output buffer to ensure all data is written.
///
/// # Error Handling
///
/// File creation failures produce a warning but do **not** fail the
/// function. Individual session write errors produce per-session
/// warnings but allow remaining sessions to be written. The transfer
/// has already completed at this point, so session save failures do
/// not affect the transfer result.
///
/// # Arguments
///
/// * `global` — Global configuration for message output.
/// * `config` — Operation configuration providing the
///   `ssl_sessions_file` path.
/// * `share` — Shared handle whose session cache is exported.
///
/// # Returns
///
/// * `Ok(())` — Saving completed (possibly with zero sessions).
/// * `Err(...)` — Only on truly unrecoverable errors (should be rare).
///
/// # C Equivalent
///
/// ```c
/// CURLcode tool_ssls_save(struct OperationConfig *config,
///                         CURLSH *share, const char *filename)
/// ```
pub fn ssl_sessions_save(
    global: &GlobalConfig,
    config: &OperationConfig,
    share: &ShareHandle,
) -> Result<()> {
    // Extract the session file path. If not configured, session
    // persistence is disabled — return immediately.
    let filename = match &config.ssl_sessions_file {
        Some(f) => f.as_str(),
        None => return Ok(()),
    };

    // Obtain the shared TLS session cache. If session sharing is not
    // enabled, there is nothing to export.
    let session_cache = match share.get_session_cache() {
        Some(cache) => cache,
        None => return Ok(()),
    };

    // Configure a temporary easy handle (mirrors C tool_ssls_easy()).
    //
    // In the C code, the easy handle is used to call
    // `curl_easy_ssls_export(easy, tool_ssls_exp, &ctx)`.
    // In Rust, we access the session cache directly but create the
    // handle for behavioral parity (debug/trace output configuration).
    let _easy = match configure_session_easy(global) {
        Ok(e) => e,
        Err(e) => {
            // Map CurlError to a warning, matching C behavior where
            // tool_ssls_easy failure is not fatal.
            let curl_err: &CurlError = &e;
            warnf(
                global,
                &format!("Failed to create session helper handle: {}", curl_err),
            );
            return Ok(());
        }
    };

    // Open the session file for writing. This creates the file if it
    // does not exist, or truncates it if it does.
    //
    // C equivalent:
    //   ctx.fp = curlx_fopen(filename, FOPEN_WRITETEXT);
    //   if(!ctx.fp) {
    //     warnf("Warning: Failed to create SSL session file %s", filename);
    //     goto out;
    //   }
    let fp = match File::create(filename) {
        Ok(f) => f,
        Err(e) => {
            warnf(
                global,
                &format!(
                    "Warning: Failed to create SSL session file {}: {}",
                    filename, e
                ),
            );
            return Ok(());
        }
    };

    let mut writer = BufWriter::new(fp);
    let mut exported: usize = 0;

    // Lock the session cache and iterate all stored sessions.
    //
    // C equivalent uses `curl_easy_ssls_export(easy, tool_ssls_exp, &ctx)`
    // which iterates the cache internally and invokes the callback for
    // each session. In Rust, we use `SessionCache::export_all()` to
    // obtain a snapshot of all non-expired sessions.
    if let Ok(cache) = session_cache.lock() {
        let sessions: Vec<(String, TlsSession)> = cache.export_all();

        for (ref peer_key, ref session) in &sessions {
            // Write file header before the first session entry.
            //
            // C equivalent:
            //   if(!ctx->exported)
            //     fputs("# Your SSL session cache...\n"
            //           "# This file was generated by libcurl!...\n", ctx->fp);
            if exported == 0 {
                if writer
                    .write_all(SESSION_FILE_HEADER_1.as_bytes())
                    .is_err()
                {
                    warnf(
                        global,
                        "Warning: error writing SSL session file header",
                    );
                    return Ok(());
                }
                if writer
                    .write_all(SESSION_FILE_HEADER_2.as_bytes())
                    .is_err()
                {
                    warnf(
                        global,
                        "Warning: error writing SSL session file header",
                    );
                    return Ok(());
                }
            }

            // Base64-encode the peer key (shmac).
            //
            // C equivalent: `curlx_base64_encode(shmac, shmac_len, &enc, &enc_len)`
            let key_str: &str = peer_key.as_str();
            let shmac_b64: String = BASE64_ENGINE.encode(key_str.as_bytes());

            // Serialize the session to TLV binary format and base64-encode.
            //
            // C equivalent:
            //   curlx_base64_encode(sdata, sdata_len, &enc, &enc_len)
            let sdata: Vec<u8> = session.serialize();
            let sdata_b64: String = BASE64_ENGINE.encode(&sdata);

            // Write the session line: base64_shmac:base64_sdata\n
            //
            // C equivalent:
            //   fwrite(enc_shmac, 1, enc_len, ctx->fp);
            //   fputc(':', ctx->fp);
            //   fwrite(enc_sdata, 1, enc_len, ctx->fp);
            //   fputc('\n', ctx->fp);
            if writeln!(writer, "{}:{}", shmac_b64, sdata_b64).is_err() {
                warnf(
                    global,
                    &format!(
                        "Warning: error saving SSL session for '{}'",
                        peer_key
                    ),
                );
                // Continue attempting to write remaining sessions rather
                // than aborting — some sessions saved is better than none.
                continue;
            }

            exported += 1;
        }
    } else {
        warnf(
            global,
            "Warning: Failed to lock session cache for export",
        );
        return Ok(());
    }

    // Flush the buffered writer to ensure all data reaches the file.
    if let Err(e) = writer.flush() {
        warnf(
            global,
            &format!(
                "Warning: error flushing SSL session file {}: {}",
                filename, e
            ),
        );
    }

    if exported > 0 {
        notef(
            global,
            &format!(
                "Saved {} SSL session(s) to {}",
                exported, filename
            ),
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{
        GlobalConfig, OperationConfig, TerminalState,
        TransferState, TraceType,
    };
    use crate::libinfo::LibCurlInfo;

    /// Creates a minimal GlobalConfig suitable for unit testing.
    ///
    /// Does NOT require library initialization (no TLS, no tracing).
    /// All fields use safe defaults with silent mode enabled to suppress
    /// stderr output during tests.
    fn test_global() -> GlobalConfig {
        GlobalConfig {
            state: TransferState::new(),
            trace_dump: None,
            trace_stream: None,
            libcurl: None,
            ssl_sessions: None,
            variables: Vec::new(),
            configs: vec![OperationConfig::new()],
            current: 0,
            ms_per_transfer: 0,
            tracetype: TraceType::None,
            progressmode: 0,
            parallel_host: 0,
            parallel_max: 50,
            verbosity: 0,
            parallel: false,
            parallel_connect: false,
            fail_early: false,
            styled_output: false,
            trace_fopened: false,
            tracetime: false,
            traceids: false,
            showerror: false,
            silent: true, // Suppress warnings during tests
            noprogress: true,
            isatty: false,
            trace_set: false,
            libcurl_info: LibCurlInfo::default(),
            term: TerminalState::new(),
            libcurl_version: None,
        }
    }

    /// Creates an OperationConfig with the given session file path.
    fn test_config_with_path(path: &str) -> OperationConfig {
        let mut config = OperationConfig::new();
        config.ssl_sessions_file = Some(path.to_string());
        config
    }

    #[test]
    fn test_load_no_session_file_configured() {
        let global = test_global();
        let config = OperationConfig::new();
        let share = ShareHandle::new();

        // No ssl_sessions_file configured → returns Ok immediately.
        let result = ssl_sessions_load(&global, &config, &share);
        assert!(result.is_ok());
    }

    #[test]
    fn test_load_missing_file() {
        let global = test_global();
        let config = test_config_with_path(
            "/tmp/nonexistent_ssl_sessions_test_file_4d3a7.txt",
        );
        let share = ShareHandle::new();

        // Missing file → returns Ok (with notef message, suppressed by silent mode).
        let result = ssl_sessions_load(&global, &config, &share);
        assert!(result.is_ok());
    }

    #[test]
    fn test_save_no_session_file_configured() {
        let global = test_global();
        let config = OperationConfig::new();
        let share = ShareHandle::new();

        // No ssl_sessions_file configured → returns Ok immediately.
        let result = ssl_sessions_save(&global, &config, &share);
        assert!(result.is_ok());
    }

    #[test]
    fn test_save_no_session_cache() {
        let global = test_global();
        let dir = std::env::temp_dir();
        let path = dir.join("curl_rs_ssls_test_no_cache.txt");
        let config = test_config_with_path(path.to_str().unwrap());
        let share = ShareHandle::new();
        // ShareHandle without SSL session sharing enabled → no cache.

        let result = ssl_sessions_save(&global, &config, &share);
        assert!(result.is_ok());

        // Clean up.
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_empty_file() {
        let global = test_global();
        let dir = std::env::temp_dir();
        let path = dir.join("curl_rs_ssls_test_empty.txt");

        // Create an empty session file.
        {
            let _ = File::create(&path).unwrap();
        }

        let config = test_config_with_path(path.to_str().unwrap());
        let share = ShareHandle::new();

        let result = ssl_sessions_load(&global, &config, &share);
        assert!(result.is_ok());

        // Clean up.
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_comment_only_file() {
        let global = test_global();
        let dir = std::env::temp_dir();
        let path = dir.join("curl_rs_ssls_test_comments.txt");

        // Create a session file with only comments.
        {
            let mut f = File::create(&path).unwrap();
            writeln!(f, "# Comment line 1").unwrap();
            writeln!(f, "# Comment line 2").unwrap();
            writeln!(f).unwrap();
        }

        let config = test_config_with_path(path.to_str().unwrap());
        let share = ShareHandle::new();

        let result = ssl_sessions_load(&global, &config, &share);
        assert!(result.is_ok());

        // Clean up.
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_malformed_lines() {
        let global = test_global();
        let dir = std::env::temp_dir();
        let path = dir.join("curl_rs_ssls_test_malformed.txt");

        // Create a session file with malformed lines.
        {
            let mut f = File::create(&path).unwrap();
            // Line without colon separator.
            writeln!(f, "no_colon_here").unwrap();
            // Line with invalid base64 in shmac.
            writeln!(f, "!!!invalid:dGVzdA==").unwrap();
            // Line with invalid base64 in sdata.
            writeln!(f, "dGVzdA==:!!!invalid").unwrap();
        }

        let config = test_config_with_path(path.to_str().unwrap());
        let share = ShareHandle::new();

        // All lines should produce warnings but not errors.
        let result = ssl_sessions_load(&global, &config, &share);
        assert!(result.is_ok());

        // Clean up.
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_configure_session_easy_no_trace() {
        let global = test_global();
        // TraceType::None is the default — no debug callback.
        assert_eq!(global.tracetype, TraceType::None);

        let result = configure_session_easy(&global);
        assert!(result.is_ok());
    }
}
