// SPDX-License-Identifier: curl
// SPDX-FileCopyrightText: the blitzy-curl project contributors

//! Renders the four documents.
//!
//! Rendering is deterministic: the same tree produces the same bytes, which is
//! what lets continuous integration diff the committed documents against the
//! generator instead of trusting them.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::contract::Index;
use crate::forward::Forward;
use crate::hazards::Hazard;
use crate::oracle::Survey;
use crate::reverse::Reverse;

/// Document names the index declares.
pub const PROVENANCE: &str = "provenance";
/// Document name of the bidirectional matrix.
pub const TRACEABILITY: &str = "traceability";
/// Document name of the public-surface coverage matrix.
pub const COVERAGE: &str = "coverage";
/// Document name of the hazard register.
pub const QUIRKS: &str = "quirks";

const HEADER: &str = "<!--\nSPDX-FileCopyrightText: the blitzy-curl project contributors\nSPDX-License-Identifier: curl\n-->\n";

const GENERATED: &str = "Generated by `cargo run --bin curl-audit-traceability`. Run it with\n`--check` to compare this file against the tree; a difference, a gap in either\ndirection, an unresolved locator or a dangling pointer fails the run. Do not\nedit this file by hand. Rationale lives in `refactor/docs/DECISION-LOG.md`.\n";

/// Replaces the cell separator so a value cannot break the table.
fn cell(value: &str) -> String {
    value.replace('|', "\\|")
}

/// Whether an owner's crate is present in the tree yet.
fn status(present: &BTreeMap<String, bool>, owner: &str) -> &'static str {
    for name in owner.split(", ") {
        if present.get(name).copied().unwrap_or(false) {
            return "present";
        }
    }
    "planned"
}

fn preamble(out: &mut String, title: &str, summary: &str) {
    out.push_str(HEADER);
    let _ = writeln!(out, "\n# {title}\n");
    out.push_str(GENERATED);
    let _ = writeln!(out, "\n{summary}");
}

fn counts_table(out: &mut String, survey: &Survey) {
    out.push_str("\n| Family | Enumerated from the oracle |\n|---|---:|\n");
    for (family, count) in survey.counts() {
        let _ = writeln!(out, "| `{family}` | {count} |");
    }
}

/// Renders `refactor/docs/PROVENANCE.md`.
fn provenance(survey: &Survey, forward: &Forward, present: &BTreeMap<String, bool>) -> String {
    let units = forward.family("translation-unit");
    let headers = forward.family("internal-header");
    let excluded = forward.excluded();
    let owned_units = units
        .iter()
        .filter(|row| row.disposition == "owned")
        .count();
    let mut out = String::new();
    preamble(
        &mut out,
        "Provenance",
        &format!(
            "Every translation unit and internal header the vendored oracle carries, mapped to\nthe crate that replaces it or to the reason no crate does. The denominator is\nenumerated from `original/` on every run: **{} translation unit(s)** and **{}\ninternal header(s)** at the pinned tag, of which **{}** unit(s) carry an owner\nand **{}** path(s) are excluded with a written justification.",
            survey.units.len(),
            survey.headers.len(),
            owned_units,
            excluded.len()
        ),
    );
    counts_table(&mut out, survey);

    out.push_str(
        "\n## Translation units\n\n| # | Baseline unit | Owner | Status |\n|---:|---|---|---|\n",
    );
    for (index, row) in units.iter().enumerate() {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {} |",
            index + 1,
            cell(&row.source),
            if row.target == "none" {
                format!("_none, {}_", cell(&row.disposition))
            } else {
                format!("`{}`", cell(&row.target))
            },
            if row.target == "none" {
                "excluded"
            } else {
                status(present, &row.target)
            }
        );
    }

    out.push_str("\n## Internal headers\n\nA header with a same-stem source inherits that source's owner; the rest are\ndeclared.\n\n| # | Baseline header | Owner | Status |\n|---:|---|---|---|\n");
    for (index, row) in headers.iter().enumerate() {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {} |",
            index + 1,
            cell(&row.source),
            if row.target == "none" {
                format!("_none, {}_", cell(&row.disposition))
            } else {
                format!("`{}`", cell(&row.target))
            },
            if row.target == "none" {
                "excluded"
            } else {
                status(present, &row.target)
            }
        );
    }

    out.push_str("\n## Exclusions\n\n| # | Path | Disposition | Justification | Decision |\n|---:|---|---|---|---|\n");
    for (index, row) in excluded.iter().enumerate() {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {} | {} |",
            index + 1,
            cell(&row.source),
            cell(row.disposition.trim_start_matches("excluded:")),
            cell(&row.detail),
            cell(&row.decision)
        );
    }

    let orphans = forward.family("orphan-declaration");
    out.push_str("\n## Orphan declarations\n\nA declaration with no definition and no caller takes a row here and no Rust\ncounterpart.\n\n| # | Locator | What exists instead | Decision |\n|---:|---|---|---|\n");
    for (index, row) in orphans.iter().enumerate() {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {} |",
            index + 1,
            cell(&row.source),
            cell(&row.detail),
            cell(&row.decision)
        );
    }
    out
}

/// Renders `refactor/docs/TRACEABILITY-MATRIX.md`.
fn traceability(
    survey: &Survey,
    forward: &Forward,
    reverse: &Reverse,
    present: &BTreeMap<String, bool>,
) -> String {
    let families = [
        ("translation-unit", "Translation units"),
        ("internal-header", "Internal headers"),
        ("public-header", "Public headers"),
        ("exported-symbol", "Exported symbols"),
        ("symbol-register", "Symbol register"),
        ("cli-option", "Command-line options"),
        ("writeout-variable", "Output-format variables"),
        ("build-flag", "Build flags and build-system options"),
        ("internal-surface-case", "Internal-surface cases"),
        ("orphan-declaration", "Orphan declarations"),
    ];
    let mut out = String::new();
    preamble(
        &mut out,
        "Traceability Matrix",
        &format!(
            "Bidirectional. The forward direction maps every construct the oracle carries to\nthe target that owns it: **{} row(s)** across **{} families**, with **{}\ngap(s)**. The reverse direction maps every project-authored file back to the\noracle construct it derives from, or to the decision that owns it outright:\n**{} row(s)**, with **{} gap(s)**. Both directions are gates, so a non-empty\ngap column cannot be committed.",
            forward.rows.len(),
            families.len(),
            forward.gaps.len(),
            reverse.rows.len(),
            reverse.gaps.len()
        ),
    );
    counts_table(&mut out, survey);

    out.push_str("\n## Forward: baseline construct to target\n");
    for (family, title) in families {
        let rows = forward.family(family);
        let _ = writeln!(
            out,
            "\n### {title} (`{family}`, {} row(s))\n\n| # | Baseline construct | Detail | Target | Disposition | Status | Decision |\n|---:|---|---|---|---|---|---|",
            rows.len()
        );
        for (index, row) in rows.iter().enumerate() {
            let _ = writeln!(
                out,
                "| {} | `{}` | {} | {} | {} | {} | {} |",
                index + 1,
                cell(&row.source),
                if row.detail.is_empty() {
                    "-".to_owned()
                } else {
                    cell(&row.detail)
                },
                if row.target == "none" {
                    "_none_".to_owned()
                } else {
                    format!("`{}`", cell(&row.target))
                },
                cell(&row.disposition),
                if row.target == "none" {
                    "-"
                } else {
                    status(present, &row.target)
                },
                if row.decision.is_empty() {
                    "-".to_owned()
                } else {
                    cell(&row.decision)
                }
            );
        }
    }

    let _ = writeln!(
        out,
        "\n## Reverse: project-authored file to baseline construct\n\n| # | Project file | Derives from | Disposition | Decision |\n|---:|---|---|---|---|"
    );
    for (index, row) in reverse.rows.iter().enumerate() {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {} | {} |",
            index + 1,
            cell(&row.path),
            cell(&row.derivation),
            row.disposition,
            if row.decision.is_empty() {
                "-".to_owned()
            } else {
                cell(&row.decision)
            }
        );
    }

    out.push_str("\n## Gaps\n\n");
    if forward.gaps.is_empty() && reverse.gaps.is_empty() {
        out.push_str("None. Every construct resolves forward and every file resolves back.\n");
    } else {
        for gap in forward.gaps.iter().chain(reverse.gaps.iter()) {
            let _ = writeln!(out, "- {}", cell(gap));
        }
    }
    out
}

/// Renders `refactor/docs/COVERAGE-MATRIX.md`.
fn coverage(survey: &Survey, forward: &Forward, present: &BTreeMap<String, bool>) -> String {
    let exports = forward.family("exported-symbol");
    let register = forward.family("symbol-register");
    let variadic = survey
        .exports
        .iter()
        .filter(|export| export.variadic)
        .count();
    let deprecated = survey
        .register
        .iter()
        .filter(|entry| !entry.deprecated.is_empty())
        .count();
    let removed = survey
        .register
        .iter()
        .filter(|entry| !entry.last.is_empty())
        .count();

    let mut out = String::new();
    preamble(
        &mut out,
        "Coverage Matrix",
        &format!(
            "The public surface, reconciled across the mechanical oracles that describe it:\nthe export list, the declarations in the public headers, and the symbol register.\nAt the pinned tag the export list holds **{} name(s)**, of which **{}** are\nvariadic or take an argument list and are therefore reached through the C thunk;\nthe register holds **{} entry(ies)**, **{}** marked deprecated and **{}**\ncarrying a last version, so discriminant gaps and obsolete entries are\npreserved by construction. **Status is what the tree shows, not what is\nintended**: a target reads `planned` until its crate exists.",
            survey.exports.len(),
            variadic,
            survey.register.len(),
            deprecated,
            removed
        ),
    );

    out.push_str("\n## Public headers\n\nThe headers are immutable inputs. Agreement between them and the Rust\ndeclarations is verified, never generated.\n\n| # | Header | Target | Mechanism |\n|---:|---|---|---|\n");
    for (index, row) in forward.family("public-header").iter().enumerate() {
        let _ = writeln!(
            out,
            "| {} | `{}` | `{}` | {} |",
            index + 1,
            cell(&row.source),
            cell(&row.target),
            cell(&row.detail)
        );
    }

    out.push_str("\n## Exported symbols\n\n| # | Symbol | Reached as | Declared in | Target | Status |\n|---:|---|---|---|---|---|\n");
    for (index, export) in survey.exports.iter().enumerate() {
        let target = exports
            .iter()
            .find(|row| row.source == export.name)
            .map_or("none", |row| row.target.as_str());
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | {} | `{}` | {} |",
            index + 1,
            cell(&export.name),
            if export.variadic {
                "C thunk"
            } else {
                "Rust entry point"
            },
            if export.headers.is_empty() {
                "_undeclared_".to_owned()
            } else {
                export
                    .headers
                    .iter()
                    .map(|header| format!("`{}`", cell(header)))
                    .collect::<Vec<_>>()
                    .join(", ")
            },
            cell(target),
            status(present, target)
        );
    }

    out.push_str("\n## Symbol register\n\nEvery entry of the register, with the version that introduced it, the version\nthat deprecated it and the last version that featured it where the register\nrecords them.\n\n| # | Symbol | Detail | Target | Status |\n|---:|---|---|---|---|\n");
    for (index, row) in register.iter().enumerate() {
        let _ = writeln!(
            out,
            "| {} | `{}` | {} | `{}` | {} |",
            index + 1,
            cell(&row.source),
            cell(&row.detail),
            cell(&row.target),
            status(present, &row.target)
        );
    }

    out.push_str(
        "\n## Byte-frozen tool surfaces\n\n| Surface | Count | Target |\n|---|---:|---|\n",
    );
    let _ = writeln!(
        out,
        "| Command-line options | {} | `curl-cli` |",
        survey.cli_options.len()
    );
    let _ = writeln!(
        out,
        "| Output-format variables | {} | `curl-cli` |",
        survey.writeout_variables.len()
    );
    let _ = writeln!(
        out,
        "| Build flags and build-system options | {} | `refactor/shim` |",
        survey.build_flags.len()
    );
    out
}

/// Renders `refactor/docs/QUIRKS.md`.
fn quirks(hazards: &[Hazard], present: &BTreeMap<String, bool>) -> String {
    let count = |verdict: &str| hazards.iter().filter(|h| h.verdict == verdict).count();
    let mut out = String::new();
    preamble(
        &mut out,
        "Quirks and Hazards",
        &format!(
            "Every hazard the vendored oracle carries that the port has to answer for, with\nthe verdict the project holds, the crate that owns it and the verification that\nproves the verdict. **{} hazard(s)**: **{}** reproduced bug for bug, **{}**\nsubstituted with an identical observable outcome, **{}** diverging and therefore\ncarrying a divergence-allowlist entry, and **{}** belonging to a platform the\nmatrix excludes. `Status` is `obligation` where the named verification is not\nyet written and `verified` only where an artifact exists. Upstream's own record\nof known issues is `original/docs/KNOWN_BUGS.md`; this file records what the\nport does about the hazards, not a second copy of that record.",
            hazards.len(),
            count("reproduce"),
            count("substitute"),
            count("diverge"),
            count("not-ported")
        ),
    );

    out.push_str("\n## Register\n\n| ID | Locator | Observable behaviour | Verdict | Owner | Compensating verification | Status | Decision |\n|---|---|---|---|---|---|---|---|\n");
    for hazard in hazards {
        let _ = writeln!(
            out,
            "| {} | `{}:{}-{}` | {} | {} | {} | {} | {} | {} |",
            cell(&hazard.id),
            cell(&hazard.path),
            hazard.lines.0,
            hazard.lines.1,
            cell(&hazard.behaviour),
            cell(&hazard.verdict),
            if hazard.owner == "none" {
                "_none_".to_owned()
            } else {
                format!(
                    "`{}` ({})",
                    cell(&hazard.owner),
                    status(present, &hazard.owner)
                )
            },
            cell(&hazard.verification),
            cell(&hazard.status),
            cell(&hazard.decision)
        );
    }

    out.push_str("\n## Verdicts by owner\n\n| Owner | Reproduce | Substitute | Diverge | Not ported | Total |\n|---|---:|---:|---:|---:|---:|\n");
    let mut owners: BTreeMap<&str, [usize; 4]> = BTreeMap::new();
    for hazard in hazards {
        let slot = owners.entry(hazard.owner.as_str()).or_insert([0; 4]);
        let index = match hazard.verdict.as_str() {
            "reproduce" => 0,
            "substitute" => 1,
            "diverge" => 2,
            _ => 3,
        };
        slot[index] += 1;
    }
    for (owner, tally) in owners {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} | {} |",
            cell(owner),
            tally[0],
            tally[1],
            tally[2],
            tally[3],
            tally.iter().sum::<usize>()
        );
    }
    out
}

/// Renders every declared document, keyed by its output path.
#[must_use]
pub fn documents(
    index: &Index,
    survey: &Survey,
    forward: &Forward,
    reverse: &Reverse,
    hazards: &[Hazard],
    present: &BTreeMap<String, bool>,
) -> Vec<(String, String)> {
    let mut rendered = Vec::new();
    let mut add = |name: &str, body: String| {
        if let Some(path) = index.output(name) {
            rendered.push((path.to_owned(), body));
        }
    };
    add(PROVENANCE, provenance(survey, forward, present));
    add(
        TRACEABILITY,
        traceability(survey, forward, reverse, present),
    );
    add(COVERAGE, coverage(survey, forward, present));
    add(QUIRKS, quirks(hazards, present));
    rendered.sort_by(|left, right| left.0.cmp(&right.0));
    rendered
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::{cell, status};

    #[test]
    fn cells_cannot_break_the_table() {
        assert_eq!(cell("a|b"), "a\\|b");
        assert_eq!(cell("plain"), "plain");
    }

    #[test]
    fn status_reads_the_tree_rather_than_the_intent() {
        let present: BTreeMap<String, bool> = [
            ("curl-core".to_owned(), true),
            ("curl-tls".to_owned(), false),
        ]
        .into_iter()
        .collect();
        assert_eq!(status(&present, "curl-core"), "present");
        assert_eq!(status(&present, "curl-tls"), "planned");
        assert_eq!(status(&present, "curl-tls, curl-core"), "present");
        assert_eq!(status(&present, "unknown"), "planned");
    }
}
