//! Alternative Services (Alt-Svc) cache — RFC 7838.
//!
//! This module is a memory-safe Rust rewrite of the curl 8.x source-of-truth
//! `lib/altsvc.c`. It maintains the *Alternative Services* cache described in
//! [RFC 7838](https://datatracker.ietf.org/doc/html/rfc7838), which lets curl
//! transparently switch a request from an origin (`h1`/`h2`/`h3` + host + port)
//! to an advertised alternate endpoint — most commonly to hop from HTTP/1.1 or
//! HTTP/2 to an HTTP/3 (QUIC) service on a different port.
//!
//! The cache has three responsibilities, each a faithful port of its C
//! counterpart:
//!
//! * **Header ingestion** — [`AltSvc::parse`] consumes an `Alt-Svc:` response
//!   header value (`h2=":443"`, `h3=":443"; ma=3600; persist=1`, `clear`, …),
//!   applying RFC 7838 update / replace / clear semantics.
//! * **Persistence** — [`AltSvc::save`] / [`AltSvc::load`] write and read the
//!   on-disk cache in curl's exact, **byte-compatible** nine-field line format
//!   (IPv6 hosts written bracketed), so a file produced by this implementation
//!   round-trips identically against a curl 8.x reference binary.
//! * **Lookup** — [`AltSvc::lookup`] is the query the connection layer uses to
//!   pick an alternative service for a given origin, honoring the
//!   `CURLALTSVC_H*` version bitmask and dropping expired entries.
//!
//! # Parity notes
//!
//! * Entry insertion order is preserved (curl uses an ordered linked list;
//!   this module uses a [`Vec`]). The save format emits entries in that order.
//! * Expired entries are **loaded and saved** unchanged; expiry is only
//!   consulted — and expired entries pruned — during [`AltSvc::lookup`],
//!   exactly as in `lib/altsvc.c`.
//! * The [`AlpnId`] discriminants are intentionally equal to the
//!   `CURLALTSVC_H*` flag bits, mirroring `enum alpnid` in `lib/hostip.h`; this
//!   is what lets the lookup version filter be a direct bitwise `&`.
//!
//! # Safety
//!
//! This module is implemented entirely in safe Rust, honoring the
//! workspace-wide policy that confines low-level memory operations to the FFI
//! crate. It performs no raw-pointer, transmute, or FFI operations.

use std::fs;
use std::net::Ipv6Addr;

use chrono::{DateTime, Datelike, NaiveDate, Timelike, Utc};

use crate::error::{Error, Result};

// ---------------------------------------------------------------------------
// Public bitmask constants — mirror `include/curl/curl.h`.
//
// These are the bits accepted by the `CURLOPT_ALTSVC_CTRL` option. Their
// integer values are a frozen part of the public contract and must match curl
// 8.x exactly. They are declared as `i64` because the underlying libcurl option
// is a C `long`.
// ---------------------------------------------------------------------------

/// `CURLALTSVC_READONLYFILE` — do not write the cache file back out on save.
pub const CURLALTSVC_READONLYFILE: i64 = 1 << 2;
/// `CURLALTSVC_H1` — allow selecting an HTTP/1.1 alternative.
pub const CURLALTSVC_H1: i64 = 1 << 3;
/// `CURLALTSVC_H2` — allow selecting an HTTP/2 alternative.
pub const CURLALTSVC_H2: i64 = 1 << 4;
/// `CURLALTSVC_H3` — allow selecting an HTTP/3 alternative.
pub const CURLALTSVC_H3: i64 = 1 << 5;

// ---------------------------------------------------------------------------
// Internal parser limits — mirror the `#define`s at the top of `lib/altsvc.c`
// (and `MAX_IPADR_LEN` from `lib/urldata.h`).
// ---------------------------------------------------------------------------

/// Maximum length of a single line read from the cache file (`MAX_ALTSVC_LINE`).
const MAX_ALTSVC_LINE: usize = 4095;
/// Maximum length of the quoted date field (`MAX_ALTSVC_DATELEN`), e.g.
/// `20191231 00:00:00` which is exactly 17 bytes.
const MAX_ALTSVC_DATELEN: usize = 17;
/// Maximum length of a host token (`MAX_ALTSVC_HOSTLEN`).
const MAX_ALTSVC_HOSTLEN: usize = 2048;
/// Maximum length of an ALPN token (`MAX_ALTSVC_ALPNLEN`).
const MAX_ALTSVC_ALPNLEN: usize = 10;
/// Maximum length of a textual IP address (`MAX_IPADR_LEN`), sized for
/// `ffff:ffff:ffff:ffff:ffff:ffff:255.255.255.255` plus its terminator.
const MAX_IPADR_LEN: usize = 46;

/// The largest value representable by a 64-bit signed `time_t`, matching
/// curl's `TIME_T_MAX` on the supported 64-bit platforms. Used to cap the
/// `ma` (max-age) computation exactly as `lib/altsvc.c` does.
const TIME_T_MAX: i64 = i64::MAX;

/// The two header lines written verbatim at the top of every saved cache file.
/// Reproduced byte-for-byte from `Curl_altsvc_save` in `lib/altsvc.c`.
const ALTSVC_FILE_HEADER: &str = "# Your alt-svc cache. https://curl.se/docs/alt-svc.html\n\
     # This file was generated by libcurl! Edit at your own risk.\n";

// ---------------------------------------------------------------------------
// ALPN identifiers
// ---------------------------------------------------------------------------

/// Application-Layer Protocol Negotiation identifier for an alternative
/// service, mirroring the C `enum alpnid` in `lib/hostip.h`.
///
/// The discriminants are **deliberately** equal to the `CURLALTSVC_H*` flag
/// bits ([`CURLALTSVC_H1`] = 8, [`CURLALTSVC_H2`] = 16, [`CURLALTSVC_H3`] = 32).
/// This equivalence is relied upon by [`AltSvc::lookup`], which tests the
/// caller-supplied version bitmask against a destination id with a plain
/// bitwise `&` — precisely as curl does with `versions & (int)as->dst.alpnid`.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AlpnId {
    /// `ALPN_none` — unknown / unset (also the "rubbish input" sentinel).
    None = 0,
    /// `ALPN_h1` — HTTP/1.1 (`h1`, or the ALPN token `http/1.1`).
    H1 = 1 << 3,
    /// `ALPN_h2` — HTTP/2 (`h2`).
    H2 = 1 << 4,
    /// `ALPN_h3` — HTTP/3 (`h3`).
    H3 = 1 << 5,
}

impl AlpnId {
    /// Returns the integer bit value of this id (`self as i32`).
    ///
    /// Because the discriminants equal the `CURLALTSVC_H*` bits, this value can
    /// be tested directly against a `CURLALTSVC_H*` version mask.
    #[must_use]
    pub const fn bits(self) -> i32 {
        self as i32
    }

    /// Maps an ALPN token to its id, mirroring `Curl_alpn2alpnid`
    /// (`lib/connect.c`).
    ///
    /// The comparison is **case-sensitive** (curl uses `memcmp`): the two-byte
    /// tokens `h1`, `h2`, `h3` map to the corresponding protocol, the eight-byte
    /// token `http/1.1` maps to [`AlpnId::H1`], and anything else — including
    /// differently-cased spellings — maps to [`AlpnId::None`].
    #[must_use]
    pub fn from_alpn(name: &str) -> AlpnId {
        match name.as_bytes() {
            b"h1" => AlpnId::H1,
            b"h2" => AlpnId::H2,
            b"h3" => AlpnId::H3,
            b"http/1.1" => AlpnId::H1,
            _ => AlpnId::None,
        }
    }

    /// Returns the canonical textual name for this id, mirroring
    /// `Curl_alpnid2str` (`lib/altsvc.c`). [`AlpnId::None`] renders as the empty
    /// string, exactly as curl's `default` branch does.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            AlpnId::H1 => "h1",
            AlpnId::H2 => "h2",
            AlpnId::H3 => "h3",
            AlpnId::None => "",
        }
    }
}

// ---------------------------------------------------------------------------
// Cache entry types
// ---------------------------------------------------------------------------

/// One side (source *or* destination) of an alternative-service mapping,
/// mirroring the C `struct althost` in `lib/altsvc.h`.
///
/// `host` is stored **without** surrounding brackets even for IPv6 literals;
/// the brackets are re-applied on save (see [`AltSvc::save`]).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AltHost {
    /// The host name or IP literal (IPv6 stored unbracketed).
    pub host: String,
    /// The TCP/UDP port.
    pub port: u16,
    /// The ALPN protocol identifier for this endpoint.
    pub alpnid: AlpnId,
}

/// A single cached alternative service, mirroring the C `struct altsvc`
/// (`lib/altsvc.h`): a source origin, its advertised destination, an absolute
/// expiry, and the RFC 7838 `persist` / `prio` attributes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AltSvcEntry {
    /// The origin this alternative applies to.
    pub src: AltHost,
    /// The advertised alternative endpoint.
    pub dst: AltHost,
    /// Absolute expiry as a Unix timestamp (seconds, UTC). Matches curl's
    /// `time_t expires`.
    pub expires: i64,
    /// Whether the entry should persist across cache reloads (`persist=1`).
    pub persist: bool,
    /// RFC 7838 priority. curl currently always stores `0` here; preserved for
    /// format compatibility.
    pub prio: u32,
}

/// The result of a successful [`AltSvc::lookup`]: the chosen destination
/// endpoint plus whether it is effectively identical to the origin.
///
/// This is an owned value (rather than a borrow of the cache) so callers in the
/// connection layer can hold onto the selected alternative without pinning a
/// borrow of the whole cache.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AltSvcMatch {
    /// The destination ALPN protocol to switch to.
    pub alpnid: AlpnId,
    /// The destination host (IPv6 unbracketed).
    pub host: String,
    /// The destination port.
    pub port: u16,
    /// `true` when the destination host and port are the same as the queried
    /// origin (curl's `psame_destination`), i.e. only the protocol differs.
    pub same_destination: bool,
}

// ---------------------------------------------------------------------------
// The cache
// ---------------------------------------------------------------------------

/// The Alt-Svc cache, mirroring the C `struct altsvcinfo` (`lib/altsvc.h`).
///
/// Holds the ordered set of [`AltSvcEntry`] values, the optional backing file
/// name (remembered across a [`load`](AltSvc::load) so a later
/// [`save`](AltSvc::save) can default to it), and the publicly settable
/// `CURLALTSVC_*` flag bitmask.
#[derive(Debug, Clone)]
pub struct AltSvc {
    /// The cache file name remembered from the most recent [`load`](AltSvc::load).
    filename: Option<String>,
    /// The cached entries, in insertion order (curl's linked list order).
    entries: Vec<AltSvcEntry>,
    /// The `CURLALTSVC_*` control bitmask (a C `long`).
    flags: i64,
}

impl Default for AltSvc {
    fn default() -> Self {
        Self::new()
    }
}

impl AltSvc {
    /// Creates a new, empty Alt-Svc cache, mirroring `Curl_altsvc_init`.
    ///
    /// The default control mask enables all three protocol versions
    /// (`CURLALTSVC_H1 | CURLALTSVC_H2 | CURLALTSVC_H3`). This matches a curl
    /// build with HTTP/2 and HTTP/3 support compiled in — which is always the
    /// case for this Rust rewrite (both `h2` and `h3` are first-class).
    #[must_use]
    pub fn new() -> Self {
        AltSvc {
            filename: None,
            entries: Vec::new(),
            flags: CURLALTSVC_H1 | CURLALTSVC_H2 | CURLALTSVC_H3,
        }
    }

    /// Returns the number of entries currently cached (curl's
    /// `Curl_llist_count`).
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Returns `true` when the cache holds no entries.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Returns a read-only view of the cached entries in insertion order.
    #[must_use]
    pub fn entries(&self) -> &[AltSvcEntry] {
        &self.entries
    }

    /// Returns the current `CURLALTSVC_*` control bitmask.
    #[must_use]
    pub fn flags(&self) -> i64 {
        self.flags
    }

    /// Overwrites the `CURLALTSVC_*` control bitmask.
    ///
    /// Prefer [`ctrl`](AltSvc::ctrl) when reproducing the `CURLOPT_ALTSVC_CTRL`
    /// semantics (which reject a zero mask).
    pub fn set_flags(&mut self, flags: i64) {
        self.flags = flags;
    }

    /// Returns the remembered cache file name, if any.
    #[must_use]
    pub fn filename(&self) -> Option<&str> {
        self.filename.as_deref()
    }
}

impl AltSvc {
    /// Applies an external `CURLALTSVC_*` control bitmask, mirroring
    /// `Curl_altsvc_ctrl`.
    ///
    /// A zero mask is rejected with `CURLE_BAD_FUNCTION_ARGUMENT`
    /// ([`Error::BadFunctionArgument`]); any other value replaces the current
    /// flags wholesale.
    ///
    /// # Errors
    ///
    /// Returns [`Error::BadFunctionArgument`] when `ctrl` is `0`.
    pub fn ctrl(&mut self, ctrl: i64) -> Result<()> {
        if ctrl == 0 {
            return Err(Error::bad_argument(
                "CURLALTSVC_CTRL requires a non-zero bitmask",
            ));
        }
        self.flags = ctrl;
        Ok(())
    }

    /// Loads Alt-Svc entries from `file`, mirroring `Curl_altsvc_load`.
    ///
    /// The file name is remembered (so a later [`save`](AltSvc::save) with no
    /// explicit path defaults to it) **before** the file is opened, exactly as
    /// curl does. A missing or unreadable file is **not** an error — it simply
    /// yields no entries, matching curl's behavior of only returning errors on
    /// problems that prevent alt-svc handling entirely.
    ///
    /// Each line is parsed independently; a malformed line is skipped without
    /// aborting the load. Comment lines (first non-blank byte `#`) are ignored.
    /// Expired entries are loaded unchanged — expiry is only consulted during
    /// [`lookup`](AltSvc::lookup).
    ///
    /// # Errors
    ///
    /// This function does not currently return an error; the [`Result`] shape is
    /// retained for API parity with the C `CURLcode` contract and for forward
    /// compatibility.
    pub fn load(&mut self, file: &str) -> Result<()> {
        // Keep a private copy of the file name so it survives an easy-handle
        // reset (parity: curl stores it even when the subsequent open fails).
        self.filename = Some(file.to_string());

        // A missing / unreadable file is not an error: no entries are loaded.
        let bytes = match fs::read(file) {
            Ok(b) => b,
            Err(_) => return Ok(()),
        };
        // Alt-Svc cache files are ASCII; lossy decoding cannot corrupt valid
        // input and guarantees we never fail on stray bytes.
        let content = String::from_utf8_lossy(&bytes);

        for segment in content.split('\n') {
            // Parity: Curl_get_line aborts the load on an over-long line.
            if segment.len() > MAX_ALTSVC_LINE {
                break;
            }
            let mut cur = Parser::new(segment);
            cur.pass_blanks();
            // Comment lines start with '#'; everything else is a candidate.
            if cur.first() == Some(b'#') {
                continue;
            }
            if let Some(entry) = parse_file_line(cur.remaining()) {
                self.entries.push(entry);
            }
        }
        Ok(())
    }

    /// Writes the cache to disk in curl's byte-compatible format, mirroring
    /// `Curl_altsvc_save`.
    ///
    /// The target path is `file` when supplied, otherwise the name remembered
    /// from the most recent [`load`](AltSvc::load). Nothing is written — and
    /// `Ok(())` is returned — when the [`CURLALTSVC_READONLYFILE`] flag is set,
    /// or when no (or an empty) path is available.
    ///
    /// Every entry is written, in insertion order, including expired ones. IPv6
    /// literal hosts are emitted bracketed. The write is performed to a sibling
    /// temporary file which is then atomically renamed over the target,
    /// mirroring curl's `Curl_fopen` + rename strategy.
    ///
    /// # Errors
    ///
    /// * [`Error::Io`] if the temporary file cannot be written.
    /// * [`Error::Write`] if the atomic rename over the target fails
    ///   (`CURLE_WRITE_ERROR`).
    /// * [`Error::BadFunctionArgument`] if an entry's expiry cannot be
    ///   represented as a calendar date (mirrors a `curlx_gmtime` failure).
    pub fn save(&self, file: Option<&str>) -> Result<()> {
        // Resolve the target: an explicit argument wins, else the stored name.
        let resolved = match file {
            Some(f) => Some(f),
            None => self.filename.as_deref(),
        };
        // Read-only caches are never written back (checked before the
        // empty-path test, exactly as curl orders it).
        if self.flags & CURLALTSVC_READONLYFILE != 0 {
            return Ok(());
        }
        let path = match resolved {
            Some(f) if !f.is_empty() => f,
            _ => return Ok(()), // no file or zero-length name: nothing to do
        };

        let mut out = String::from(ALTSVC_FILE_HEADER);
        for entry in &self.entries {
            out.push_str(&entry_to_line(entry)?);
        }

        // Atomic replace: write to a uniquely-named sibling, then rename.
        let tmp = format!("{path}.tmp.{}", std::process::id());
        fs::write(&tmp, out.as_bytes())?;
        if fs::rename(&tmp, path).is_err() {
            let _ = fs::remove_file(&tmp);
            return Err(Error::Write);
        }
        Ok(())
    }
}

impl AltSvc {
    /// Removes every cached entry whose **source** origin matches
    /// `(srcalpnid, srchost, srcport)`, mirroring `altsvc_flush`.
    ///
    /// Host comparison ignores a single trailing dot on `srchost` and is
    /// case-insensitive (see [`hostcompare`]).
    fn flush(&mut self, srcalpnid: AlpnId, srchost: &str, srcport: u16) {
        self.entries.retain(|e| {
            !(e.src.alpnid == srcalpnid
                && e.src.port == srcport
                && hostcompare(srchost, &e.src.host))
        });
    }

    /// Ingests an `Alt-Svc:` response-header value, mirroring
    /// `Curl_altsvc_parse`.
    ///
    /// `value` is the header content to the right of the `Alt-Svc:` name.
    /// `srcalpnid` / `srchost` / `srcport` identify the origin the header was
    /// received over. RFC 7838 semantics are applied:
    ///
    /// * The magic keyword `clear` flushes every alternative for the origin.
    /// * The first advertised alternative on a line replaces the origin's
    ///   previously cached set (subsequent alternatives on the same line are
    ///   appended).
    /// * The optional `ma` (max-age, seconds) and `persist=1` parameters are
    ///   honored; unknown parameters are skipped. A missing `ma` defaults to
    ///   24 hours.
    /// * Alternatives with an unparseable host, an out-of-range port, an
    ///   unknown protocol token, or a missing quote are rejected individually
    ///   without failing the whole header.
    ///
    /// Invalid data is rejected silently (no error), matching curl. Diagnostic
    /// messages mirror curl's `infof` output and are emitted via `tracing` to
    /// preserve the `--verbose` vocabulary.
    ///
    /// # Errors
    ///
    /// This function does not currently return an error; the [`Result`] shape is
    /// retained for API parity with the C `CURLcode` contract.
    pub fn parse(
        &mut self,
        value: &str,
        srcalpnid: AlpnId,
        srchost: &str,
        srcport: u16,
    ) -> Result<()> {
        // (1) Initial check for the magic "clear" keyword: the text up to the
        //     first ';' or CR/LF, trimmed, compared case-insensitively.
        {
            let mut c = Parser::new(value);
            if let Some(tok) = c.take_cspn(b";\n\r") {
                if trim_blanks(tok).eq_ignore_ascii_case("clear") {
                    self.flush(srcalpnid, srchost, srcport);
                    return Ok(());
                }
            }
        }

        // (2) Parse the comma-separated list of alternatives.
        let mut p = Parser::new(value);
        let mut alpn = match p.take_until(MAX_ALTSVC_LINE, b'=') {
            Some(a) => trim_blanks(a),
            None => return Ok(()), // strange line: nothing before '='
        };
        let mut entries: usize = 0;

        loop {
            if !p.eat_char(b'=') {
                break;
            }
            let dstalpnid = AlpnId::from_alpn(alpn);
            let mut maxage: i64 = 24 * 3600; // default max-age is 24 hours
            let mut persist = false;

            if !p.eat_char(b'"') {
                break; // no opening quote after '='
            }

            // Destination host — defaults to the source host when absent.
            let dsthost: String;
            if !p.eat_char(b':') {
                // A host token is present.
                if !p.eat_char(b'[') {
                    // Regular host name, up to the ':' port separator.
                    match p.take_until(MAX_ALTSVC_HOSTLEN, b':') {
                        Some(h) => dsthost = h.to_string(),
                        None => {
                            tracing::info!("Bad alt-svc hostname, ignoring.");
                            break;
                        }
                    }
                } else {
                    // Bracketed IPv6 literal, up to the ']'.
                    match p.take_until(MAX_IPADR_LEN, b']') {
                        Some(h) if p.eat_char(b']') => dsthost = h.to_string(),
                        _ => {
                            tracing::info!("Bad alt-svc IPv6 hostname, ignoring.");
                            break;
                        }
                    }
                }
                if !p.eat_char(b':') {
                    break; // expected ':' before the port
                }
            } else {
                // No destination name given: reuse the source host.
                dsthost = srchost.to_string();
            }

            // Port.
            let dstport = match p.take_number(0xffff) {
                Some(n) => n as u16,
                None => {
                    tracing::info!("Unknown alt-svc port number, ignoring.");
                    break;
                }
            };

            if !p.eat_char(b'"') {
                break; // expected the closing quote
            }

            // (3) Optional ';'-separated parameters: 'ma', 'persist', others
            //     silently skipped.
            p.pass_blanks();
            if p.eat_char(b';') {
                // Each iteration consumes one `name=value` parameter; the loop
                // ends when no further name token is present (curl's
                // `curlx_str_until(&p, &name, 20, '=')` failing).
                while let Some(name) = p.take_until(20, b'=') {
                    if !p.eat_char(b'=') {
                        break;
                    }
                    let value_start = p.pos();
                    let raw_val = match p.take_cspn(b",;") {
                        Some(v) => v,
                        None => break,
                    };
                    let name = trim_blanks(name);
                    // The value may be quoted; count leading blanks so the
                    // number is parsed from exactly where curl's `vp` points.
                    // Byte-oriented to match `curlx_str_trimblanks` (ISBLANK).
                    let leading = raw_val
                        .bytes()
                        .take_while(|&b| b == b' ' || b == b'\t')
                        .count();
                    let trimmed = trim_blanks(raw_val);
                    let quoted = trimmed.as_bytes().first() == Some(&b'"');
                    let number_start = value_start + leading + usize::from(quoted);
                    p.set_pos(number_start);
                    match p.take_number(TIME_T_MAX) {
                        Some(num) => {
                            if name.eq_ignore_ascii_case("ma") {
                                maxage = num;
                            } else if name.eq_ignore_ascii_case("persist") && num == 1 {
                                persist = true;
                            }
                        }
                        None => break,
                    }
                    // `p` now sits just past the parsed number.
                    p.pass_blanks();
                    if quoted && !p.eat_char(b'"') {
                        break;
                    }
                    p.pass_blanks();
                    if !p.eat_char(b';') {
                        break;
                    }
                }
            }

            // (4) Commit the alternative. Unknown protocols are skipped.
            if dstalpnid != AlpnId::None {
                if entries == 0 {
                    // The first alternative on a line replaces the origin's set.
                    self.flush(srcalpnid, srchost, srcport);
                }
                entries += 1;
                if let Some(mut entry) =
                    create_id(srchost, &dsthost, srcalpnid, dstalpnid, srcport, dstport)
                {
                    let secs = now_secs();
                    // RFC 7838 §3.1: fold max-age into an absolute expiry,
                    // capping at TIME_T_MAX on overflow.
                    entry.expires = if maxage > TIME_T_MAX - secs {
                        TIME_T_MAX
                    } else {
                        maxage + secs
                    };
                    entry.persist = persist;
                    tracing::info!(
                        "Added alt-svc: {}:{} over {}",
                        dsthost,
                        dstport,
                        dstalpnid.as_str()
                    );
                    self.entries.push(entry);
                }
            }

            // (5) A comma introduces another alternative; anything else ends
            //     the header.
            if !p.eat_char(b',') {
                break;
            }
            alpn = match p.take_until(MAX_ALTSVC_LINE, b'=') {
                Some(a) => trim_blanks(a),
                None => break,
            };
        }

        Ok(())
    }

    /// Selects a cached alternative service for the origin
    /// `(srcalpnid, srchost, srcport)`, mirroring `Curl_altsvc_lookup`.
    ///
    /// `versions` is a bitmask of acceptable destination protocols built from
    /// [`CURLALTSVC_H1`] / [`CURLALTSVC_H2`] / [`CURLALTSVC_H3`]; a destination
    /// matches when its [`AlpnId::bits`] intersects the mask. Entries whose
    /// expiry has passed are pruned as they are encountered (parity with curl,
    /// which removes expired nodes during the scan).
    ///
    /// Returns the first matching alternative as an owned [`AltSvcMatch`], whose
    /// [`same_destination`](AltSvcMatch::same_destination) flag indicates the
    /// alternative differs from the origin only in protocol.
    #[must_use]
    pub fn lookup(
        &mut self,
        srcalpnid: AlpnId,
        srchost: &str,
        srcport: u16,
        versions: i32,
    ) -> Option<AltSvcMatch> {
        let now = now_secs();
        let mut i = 0;
        while i < self.entries.len() {
            // Prune expired entries in place, exactly as curl does mid-scan.
            if self.entries[i].expires < now {
                self.entries.remove(i);
                continue;
            }
            let e = &self.entries[i];
            if e.src.alpnid == srcalpnid
                && hostcompare(srchost, &e.src.host)
                && e.src.port == srcport
                && (versions & e.dst.alpnid.bits()) != 0
            {
                let same_destination = srcport == e.dst.port && hostcompare(srchost, &e.dst.host);
                return Some(AltSvcMatch {
                    alpnid: e.dst.alpnid,
                    host: e.dst.host.clone(),
                    port: e.dst.port,
                    same_destination,
                });
            }
            i += 1;
        }
        None
    }
}

// ---------------------------------------------------------------------------
// Free helper functions
// ---------------------------------------------------------------------------

/// Trims leading and trailing blanks (ASCII space or tab) from `s`, mirroring
/// `curlx_str_trimblanks`.
///
/// Only ASCII space and tab are treated as blank (curl's `ISBLANK`), never
/// newlines or other Unicode whitespace, so the trim is byte-exact.
fn trim_blanks(s: &str) -> &str {
    s.trim_matches(|c: char| c == ' ' || c == '\t')
}

/// Returns `true` when `host` matches `check`, mirroring `hostcompare`
/// (`lib/altsvc.c`).
///
/// A single trailing dot on `host` (the query side) is ignored, and the
/// comparison is ASCII case-insensitive. Because
/// [`str::eq_ignore_ascii_case`] already requires equal lengths, the length
/// pre-check curl performs is subsumed.
fn hostcompare(host: &str, check: &str) -> bool {
    let host = host.strip_suffix('.').unwrap_or(host);
    host.eq_ignore_ascii_case(check)
}

/// Returns `true` when `host` is a bare IPv6 literal, mirroring curl's
/// `curlx_inet_pton(AF_INET6, host, ...)` probe used to decide whether to
/// bracket the host on save. [`Ipv6Addr`]'s parser is strict (no brackets, no
/// zone id), matching `inet_pton`.
fn host_is_ipv6(host: &str) -> bool {
    host.parse::<Ipv6Addr>().is_ok()
}

/// Returns "now" as a Unix timestamp (seconds, UTC).
///
/// In debug builds this honors the `CURL_TIME` environment variable, mirroring
/// curl's `DEBUGBUILD`/`UNITTESTS` `time()` override (used by the alt-svc unit
/// test to pin a deterministic clock). Release builds always use the wall
/// clock. When `CURL_TIME` is set but not a leading decimal number, `0` is
/// returned — matching curl's `altsvc_debugtime`, whose value stays `0` on a
/// parse failure.
fn now_secs() -> i64 {
    if cfg!(debug_assertions) {
        if let Ok(s) = std::env::var("CURL_TIME") {
            let mut p = Parser::new(&s);
            return p.take_number(TIME_T_MAX).unwrap_or(0);
        }
    }
    Utc::now().timestamp()
}

/// Parses a fixed-width all-ASCII-digit byte field into a [`u32`].
///
/// Returns `None` if the field is empty, contains a non-digit, or overflows
/// `u32`. Unlike [`str::parse`], it rejects a leading `+`.
fn digits(b: &[u8]) -> Option<u32> {
    if b.is_empty() || !b.iter().all(u8::is_ascii_digit) {
        return None;
    }
    let mut v: u32 = 0;
    for &c in b {
        v = v.checked_mul(10)?.checked_add(u32::from(c - b'0'))?;
    }
    Some(v)
}

/// Parses the canonical on-disk date `YYYYMMDD HH:MM:SS` (UTC) into a Unix
/// timestamp.
///
/// This is the exact 17-byte layout curl writes (and reads back via its general
/// date parser). Any deviation — wrong length, misplaced separators, or an
/// out-of-range calendar value — yields `None`, in which case the caller leaves
/// the entry's expiry at `0` (parity with curl ignoring `Curl_getdate_capped`'s
/// return value).
fn parse_altsvc_date(s: &str) -> Option<i64> {
    let b = s.as_bytes();
    if b.len() != MAX_ALTSVC_DATELEN || b[8] != b' ' || b[11] != b':' || b[14] != b':' {
        return None;
    }
    let year = digits(&b[0..4])? as i32;
    let month = digits(&b[4..6])?;
    let day = digits(&b[6..8])?;
    let hour = digits(&b[9..11])?;
    let minute = digits(&b[12..14])?;
    let second = digits(&b[15..17])?;

    let date = NaiveDate::from_ymd_opt(year, month, day)?;
    let datetime = date.and_hms_opt(hour, minute, second)?;
    Some(datetime.and_utc().timestamp())
}

/// Breaks a Unix timestamp down into `(year, month, day, hour, minute, second)`
/// in UTC, mirroring `curlx_gmtime`.
///
/// # Errors
///
/// Returns [`Error::BadFunctionArgument`] when the timestamp is outside the
/// range chrono can represent as a calendar date (mirrors a `gmtime` failure,
/// which curl surfaces as `CURLE_BAD_FUNCTION_ARGUMENT`).
fn gmtime_fields(secs: i64) -> Result<(i32, u32, u32, u32, u32, u32)> {
    match DateTime::<Utc>::from_timestamp(secs, 0) {
        Some(dt) => {
            let n = dt.naive_utc();
            Ok((
                n.year(),
                n.month(),
                n.day(),
                n.hour(),
                n.minute(),
                n.second(),
            ))
        }
        None => Err(Error::bad_argument(
            "alt-svc expiry timestamp out of representable range",
        )),
    }
}

/// Serializes one [`AltSvcEntry`] to its nine-field on-disk line (terminated
/// by `\n`), mirroring `altsvc_out` (`lib/altsvc.c`).
///
/// The field order and formatting are byte-identical to curl's
/// `curl_mfprintf`: source `alpn host port`, destination `alpn host port`, a
/// quoted `"YYYYMMDD HH:MM:SS"` expiry, then the `persist` and `prio` integers.
/// IPv6 literal hosts are wrapped in brackets.
fn entry_to_line(e: &AltSvcEntry) -> Result<String> {
    let (year, month, day, hour, minute, second) = gmtime_fields(e.expires)?;
    let (src_pre, src_post) = if host_is_ipv6(&e.src.host) {
        ("[", "]")
    } else {
        ("", "")
    };
    let (dst_pre, dst_post) = if host_is_ipv6(&e.dst.host) {
        ("[", "]")
    } else {
        ("", "")
    };
    Ok(format!(
        "{} {}{}{} {} {} {}{}{} {} \"{}{:02}{:02} {:02}:{:02}:{:02}\" {} {}\n",
        e.src.alpnid.as_str(),
        src_pre,
        e.src.host,
        src_post,
        e.src.port,
        e.dst.alpnid.as_str(),
        dst_pre,
        e.dst.host,
        dst_post,
        e.dst.port,
        year,
        month,
        day,
        hour,
        minute,
        second,
        u8::from(e.persist),
        e.prio,
    ))
}

/// Builds an [`AltSvcEntry`] from raw host/port/alpn values, mirroring
/// `altsvc_createid` (`lib/altsvc.c`).
///
/// Host normalization matches curl exactly: the **source** host has any
/// surrounding IPv6 brackets stripped, or otherwise a single trailing dot; the
/// **destination** host only has brackets stripped. A host that is empty after
/// normalization causes the whole entry to be rejected (`None`). `expires`,
/// `persist`, and `prio` are initialized to zero/false and set by the caller.
fn create_id(
    srchost: &str,
    dsthost: &str,
    srcalpnid: AlpnId,
    dstalpnid: AlpnId,
    srcport: u16,
    dstport: u16,
) -> Option<AltSvcEntry> {
    let sh = strip_host(srchost, true);
    let dh = strip_host(dsthost, false);
    if sh.is_empty() || dh.is_empty() {
        return None;
    }
    Some(AltSvcEntry {
        src: AltHost {
            host: sh.to_string(),
            port: srcport,
            alpnid: srcalpnid,
        },
        dst: AltHost {
            host: dh.to_string(),
            port: dstport,
            alpnid: dstalpnid,
        },
        expires: 0,
        persist: false,
        prio: 0,
    })
}

/// Normalizes a host per `altsvc_createid`: strips surrounding IPv6 brackets,
/// and — only when `strip_trailing_dot` is set (the source side) — a single
/// trailing dot. The bracket rule mirrors curl's assumption of a matching
/// trailing `]` when the host begins with `[` and is longer than two bytes.
fn strip_host(host: &str, strip_trailing_dot: bool) -> &str {
    let bytes = host.as_bytes();
    if bytes.len() > 2 && bytes[0] == b'[' {
        &host[1..host.len() - 1]
    } else if strip_trailing_dot && bytes.last() == Some(&b'.') {
        &host[..host.len() - 1]
    } else {
        host
    }
}

/// Parses one nine-field cache line into an [`AltSvcEntry`], mirroring
/// `altsvc_add` + `altsvc_create` (`lib/altsvc.c`).
///
/// Fields are separated by exactly one space. Any tokenization failure yields
/// `None` (the whole line is skipped, as curl's loader ignores per-line
/// errors). An unknown ALPN token on either side, or an empty normalized host,
/// also rejects the line. `prio` is forced to `0` and `persist` is coerced to a
/// boolean, exactly as curl does on load.
fn parse_file_line(line: &str) -> Option<AltSvcEntry> {
    let mut p = Parser::new(line);

    let src_alpn = p.take_word(MAX_ALTSVC_ALPNLEN)?;
    if !p.eat_char(b' ') {
        return None;
    }
    let src_host = p.take_word(MAX_ALTSVC_HOSTLEN)?;
    if !p.eat_char(b' ') {
        return None;
    }
    let src_port = p.take_number(65535)?;
    if !p.eat_char(b' ') {
        return None;
    }
    let dst_alpn = p.take_word(MAX_ALTSVC_ALPNLEN)?;
    if !p.eat_char(b' ') {
        return None;
    }
    let dst_host = p.take_word(MAX_ALTSVC_HOSTLEN)?;
    if !p.eat_char(b' ') {
        return None;
    }
    let dst_port = p.take_number(65535)?;
    if !p.eat_char(b' ') {
        return None;
    }
    let date = p.take_quoted(MAX_ALTSVC_DATELEN)?;
    if !p.eat_char(b' ') {
        return None;
    }
    let persist = p.take_number(1)?;
    if !p.eat_char(b' ') {
        return None;
    }
    // `prio` is bounded to 0 by curl (max = 0) and always stored as 0.
    let _prio = p.take_number(0)?;
    if !p.expect_newline_or_end() {
        return None;
    }

    let src_alpnid = AlpnId::from_alpn(src_alpn);
    let dst_alpnid = AlpnId::from_alpn(dst_alpn);
    if src_alpnid == AlpnId::None || dst_alpnid == AlpnId::None {
        return None;
    }

    let mut entry = create_id(
        src_host,
        dst_host,
        src_alpnid,
        dst_alpnid,
        src_port as u16,
        dst_port as u16,
    )?;
    entry.expires = parse_altsvc_date(date).unwrap_or(0);
    entry.persist = persist != 0;
    entry.prio = 0;
    Some(entry)
}

// ---------------------------------------------------------------------------
// Internal byte-oriented string cursor
//
// A faithful, offset-based reimplementation of the subset of curl's
// `curlx_str_*` tokenizers used by alt-svc. Using a byte offset into the full
// input (rather than shrinking sub-slices) is essential: curl's header parser
// resets its cursor to a position *inside* a previously extracted token and
// then continues reading past that token's end (the `p = vp` idiom), which is
// only expressible against the complete backing string.
//
// All tokenizers operate on bytes; delimiters, digits and blanks are ASCII, so
// every slice boundary this cursor produces lands on a UTF-8 char boundary.
// ---------------------------------------------------------------------------

struct Parser<'a> {
    full: &'a str,
    pos: usize,
}

impl<'a> Parser<'a> {
    /// Creates a cursor positioned at the start of `s`.
    fn new(s: &'a str) -> Self {
        Parser { full: s, pos: 0 }
    }

    /// Returns the current byte offset.
    fn pos(&self) -> usize {
        self.pos
    }

    /// Moves the cursor to an absolute byte offset (clamped to the input end).
    /// Callers only ever pass offsets that fall on ASCII boundaries.
    fn set_pos(&mut self, pos: usize) {
        self.pos = pos.min(self.full.len());
    }

    /// Returns the not-yet-consumed remainder of the input.
    fn remaining(&self) -> &'a str {
        &self.full[self.pos..]
    }

    /// Returns the byte at the cursor, or `None` at end of input.
    fn first(&self) -> Option<u8> {
        self.full.as_bytes().get(self.pos).copied()
    }

    /// Advances over any leading blanks (space or tab), mirroring
    /// `curlx_str_passblanks`.
    fn pass_blanks(&mut self) {
        let b = self.full.as_bytes();
        while self.pos < b.len() && (b[self.pos] == b' ' || b[self.pos] == b'\t') {
            self.pos += 1;
        }
    }

    /// Consumes a single expected byte, mirroring `curlx_str_single`. Returns
    /// `true` (and advances) on a match, `false` (leaving the cursor put)
    /// otherwise.
    fn eat_char(&mut self, c: u8) -> bool {
        if self.first() == Some(c) {
            self.pos += 1;
            true
        } else {
            false
        }
    }

    /// Reads a token of `1..=max` bytes up to (but not consuming) `delim` or the
    /// end of input, mirroring `curlx_str_until`. Returns `None` when the token
    /// would be empty (`STRE_SHORT`) or exceed `max` (`STRE_BIG`).
    fn take_until(&mut self, max: usize, delim: u8) -> Option<&'a str> {
        let b = self.full.as_bytes();
        let start = self.pos;
        let mut i = start;
        let mut len = 0usize;
        while i < b.len() && b[i] != delim {
            i += 1;
            len += 1;
            if len > max {
                return None;
            }
        }
        if len == 0 {
            return None;
        }
        self.pos = i;
        Some(&self.full[start..i])
    }

    /// Reads a token up to the next space, mirroring `curlx_str_word`.
    fn take_word(&mut self, max: usize) -> Option<&'a str> {
        self.take_until(max, b' ')
    }

    /// Reads a double-quoted token, mirroring `curlx_str_quotedword`.
    ///
    /// The surrounding quotes are stripped from the returned slice; an escaped
    /// quote (`\"`) does not terminate the token but the backslash is **kept**
    /// in the returned bytes (exactly as curl, which counts but does not unescape
    /// it). Returns `None` on a missing opening/closing quote or on exceeding
    /// `max` inner bytes.
    fn take_quoted(&mut self, max: usize) -> Option<&'a str> {
        let b = self.full.as_bytes();
        let start = self.pos;
        if b.get(start) != Some(&b'"') {
            return None; // STRE_BEGQUOTE
        }
        let mut i = start + 1;
        let mut len = 0usize;
        while i < b.len() && b[i] != b'"' {
            if b[i] == b'\\' && i + 1 < b.len() {
                i += 1;
                len += 1;
                if len > max {
                    return None;
                }
            }
            i += 1;
            len += 1;
            if len > max {
                return None;
            }
        }
        if b.get(i) != Some(&b'"') {
            return None; // STRE_ENDQUOTE
        }
        let inner = &self.full[start + 1..i];
        self.pos = i + 1;
        Some(inner)
    }

    /// Reads an unsigned base-10 number capped at `max`, mirroring
    /// `curlx_str_number` (no sign, no `0x`, leading zeros accepted). Returns
    /// `None` when there is no leading digit (`STRE_NO_NUM`) or the value would
    /// exceed `max` (`STRE_OVERFLOW`). The two-branch structure mirrors curl's
    /// own overflow handling for small vs. large `max`.
    fn take_number(&mut self, max: i64) -> Option<i64> {
        let b = self.full.as_bytes();
        let start = self.pos;
        match b.get(start) {
            Some(c) if c.is_ascii_digit() => {}
            _ => return None,
        }
        let mut num: i64 = 0;
        let mut i = start;
        if max < 10 {
            loop {
                let n = i64::from(b[i] - b'0');
                num = num * 10 + n;
                if num > max {
                    return None;
                }
                i += 1;
                if i >= b.len() || !b[i].is_ascii_digit() {
                    break;
                }
            }
        } else {
            loop {
                let n = i64::from(b[i] - b'0');
                if num > (max - n) / 10 {
                    return None;
                }
                num = num * 10 + n;
                i += 1;
                if i >= b.len() || !b[i].is_ascii_digit() {
                    break;
                }
            }
        }
        self.pos = i;
        Some(num)
    }

    /// Reads the run of bytes that are **not** in `reject` (nor end of input),
    /// mirroring `curlx_str_cspn`. Returns `None` when the run is empty.
    fn take_cspn(&mut self, reject: &[u8]) -> Option<&'a str> {
        let b = self.full.as_bytes();
        let start = self.pos;
        let mut i = start;
        while i < b.len() && !reject.contains(&b[i]) {
            i += 1;
        }
        if i == start {
            return None;
        }
        self.pos = i;
        Some(&self.full[start..i])
    }

    /// Accepts a CR or LF (consuming it) or end of input, mirroring
    /// `curlx_str_newline`.
    ///
    /// End of input is treated as a valid line terminator because
    /// `Curl_get_line` guarantees every parsed line ends in a newline; a
    /// stripped trailing newline is therefore functionally equivalent.
    fn expect_newline_or_end(&mut self) -> bool {
        match self.first() {
            None => true,
            Some(b'\n' | b'\r') => {
                self.pos += 1;
                true
            }
            Some(_) => false,
        }
    }
}

// ===========================================================================
// Tests
//
// The behavioral oracle is curl's own `tests/unit/unit1654.c` +
// `tests/data/test1654`: the loader, the fourteen `Curl_altsvc_parse` calls
// (with their exact intermediate entry counts), and the byte-for-byte saved
// output. Reproducing it here guarantees parity with the reference binary.
// ===========================================================================
#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::sync::Mutex;

    // `now_secs()` reads the process-global `CURL_TIME` override; serialize
    // every test that depends on it so parallel execution cannot interleave
    // env-var mutations. Pure-function tests do not take this lock.
    static TIME_LOCK: Mutex<()> = Mutex::new(());
    // Unique temp-file suffixes so parallel tests never collide.
    static COUNTER: AtomicU64 = AtomicU64::new(0);

    // "20190124 22:34:21" UTC — the fixed clock used by test1654's <setenv>.
    const CURL_TIME_FIXED: &str = "1548369261";

    fn temp_path(tag: &str) -> String {
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        std::env::temp_dir()
            .join(format!(
                "altsvc_rs_test_{}_{tag}_{n}.txt",
                std::process::id()
            ))
            .to_string_lossy()
            .into_owned()
    }

    // ---- Pure-function unit tests (no clock dependency) --------------------

    #[test]
    fn alpn_mapping_is_case_sensitive_and_bit_stable() {
        assert_eq!(AlpnId::from_alpn("h1"), AlpnId::H1);
        assert_eq!(AlpnId::from_alpn("h2"), AlpnId::H2);
        assert_eq!(AlpnId::from_alpn("h3"), AlpnId::H3);
        assert_eq!(AlpnId::from_alpn("http/1.1"), AlpnId::H1);
        // Unknown / wrongly-cased tokens map to None.
        assert_eq!(AlpnId::from_alpn("H2"), AlpnId::None);
        assert_eq!(AlpnId::from_alpn("h6"), AlpnId::None);
        assert_eq!(AlpnId::from_alpn("bad"), AlpnId::None);
        assert_eq!(AlpnId::from_alpn(""), AlpnId::None);

        // Round-trip through the textual form.
        assert_eq!(AlpnId::H1.as_str(), "h1");
        assert_eq!(AlpnId::H2.as_str(), "h2");
        assert_eq!(AlpnId::H3.as_str(), "h3");
        assert_eq!(AlpnId::None.as_str(), "");

        // Discriminants equal the CURLALTSVC_* bits (relied on by lookup).
        assert_eq!(AlpnId::H1.bits() as i64, CURLALTSVC_H1);
        assert_eq!(AlpnId::H2.bits() as i64, CURLALTSVC_H2);
        assert_eq!(AlpnId::H3.bits() as i64, CURLALTSVC_H3);
    }

    #[test]
    fn date_parses_and_round_trips() {
        // Canonical 17-byte form -> timestamp -> canonical form.
        let ts = parse_altsvc_date("20191231 00:00:00").unwrap();
        assert_eq!(ts, 1_577_750_400);
        let (y, mo, d, h, mi, s) = gmtime_fields(ts).unwrap();
        assert_eq!((y, mo, d, h, mi, s), (2019, 12, 31, 0, 0, 0));

        assert_eq!(
            parse_altsvc_date("20121231 00:00:01").unwrap(),
            1_356_912_001
        );
        assert_eq!(
            parse_altsvc_date("20291231 23:30:00").unwrap(),
            1_893_454_200
        );
        assert_eq!(
            parse_altsvc_date("20190124 22:34:21").unwrap(),
            1_548_369_261
        );

        // Malformed inputs yield None (caller then stores expiry 0).
        assert_eq!(parse_altsvc_date("2019123 00:00:00"), None); // too short
        assert_eq!(parse_altsvc_date("20191231T00:00:00"), None); // wrong sep
        assert_eq!(parse_altsvc_date("2019123100:00:00 "), None); // wrong layout
        assert_eq!(parse_altsvc_date("2019xx31 00:00:00"), None); // non-digit
        assert_eq!(parse_altsvc_date("20191331 00:00:00"), None); // month 13
    }

    #[test]
    fn entry_to_line_brackets_ipv6_and_formats_fields() {
        let e = AltSvcEntry {
            src: AltHost {
                host: "2001:db8::1".to_string(),
                port: 443,
                alpnid: AlpnId::H2,
            },
            dst: AltHost {
                host: "example.com".to_string(),
                port: 8443,
                alpnid: AlpnId::H3,
            },
            expires: 1_577_750_400, // 20191231 00:00:00
            persist: true,
            prio: 0,
        };
        let line = entry_to_line(&e).unwrap();
        assert_eq!(
            line,
            "h2 [2001:db8::1] 443 h3 example.com 8443 \"20191231 00:00:00\" 1 0\n"
        );
    }

    #[test]
    fn hostcompare_ignores_trailing_dot_and_case() {
        assert!(hostcompare("EXAMPLE.com", "example.com"));
        assert!(hostcompare("example.com.", "example.com"));
        assert!(!hostcompare("example.com", "example.com.")); // dot only on lhs
        assert!(!hostcompare("example.org", "example.com"));
        assert!(!hostcompare("sub.example.com", "example.com"));
    }

    #[test]
    fn ipv6_detection() {
        assert!(host_is_ipv6("::1"));
        assert!(host_is_ipv6("2001:db8::1"));
        assert!(!host_is_ipv6("example.com"));
        assert!(!host_is_ipv6("127.0.0.1"));
        assert!(!host_is_ipv6("[::1]")); // brackets are not part of the literal
    }

    #[test]
    fn create_id_strips_brackets_and_trailing_dot() {
        // Source: trailing dot stripped; destination: brackets stripped.
        let e = create_id("example.com.", "[::1]", AlpnId::H1, AlpnId::H3, 80, 443).unwrap();
        assert_eq!(e.src.host, "example.com");
        assert_eq!(e.dst.host, "::1");
        assert_eq!(e.src.alpnid, AlpnId::H1);
        assert_eq!(e.dst.alpnid, AlpnId::H3);
        assert_eq!(e.src.port, 80);
        assert_eq!(e.dst.port, 443);

        // Destination trailing dot is NOT stripped (parity with curl).
        let e2 = create_id("[fe80::1]", "example.org.", AlpnId::H2, AlpnId::H2, 1, 2).unwrap();
        assert_eq!(e2.src.host, "fe80::1");
        assert_eq!(e2.dst.host, "example.org.");

        // Empty host after normalization is rejected.
        assert!(create_id("", "example.com", AlpnId::H1, AlpnId::H2, 80, 80).is_none());
    }

    #[test]
    fn ctrl_rejects_zero_mask() {
        let mut asi = AltSvc::new();
        assert!(asi.ctrl(0).is_err());
        assert!(asi.ctrl(CURLALTSVC_H1).is_ok());
        assert_eq!(asi.flags(), CURLALTSVC_H1);
    }

    #[test]
    fn readonly_flag_suppresses_write() {
        let path = temp_path("readonly");
        let mut asi = AltSvc::new();
        asi.set_flags(CURLALTSVC_READONLYFILE | CURLALTSVC_H1);
        asi.entries.push(AltSvcEntry {
            src: AltHost {
                host: "a".into(),
                port: 1,
                alpnid: AlpnId::H1,
            },
            dst: AltHost {
                host: "b".into(),
                port: 2,
                alpnid: AlpnId::H2,
            },
            expires: 1_577_750_400,
            persist: false,
            prio: 0,
        });
        asi.save(Some(&path)).unwrap();
        // Read-only means the file must not have been created.
        assert!(!std::path::Path::new(&path).exists());
    }

    #[test]
    fn ipv6_entry_round_trips_bracketed() {
        let path = temp_path("ipv6");
        let mut asi = AltSvc::new();
        asi.entries.push(AltSvcEntry {
            src: AltHost {
                host: "2001:db8::1".into(),
                port: 443,
                alpnid: AlpnId::H2,
            },
            dst: AltHost {
                host: "2001:db8::2".into(),
                port: 8443,
                alpnid: AlpnId::H3,
            },
            expires: 1_577_750_400,
            persist: false,
            prio: 0,
        });
        asi.save(Some(&path)).unwrap();

        let saved = fs::read_to_string(&path).unwrap();
        assert!(
            saved.contains("[2001:db8::1]"),
            "src IPv6 must be bracketed"
        );
        assert!(
            saved.contains("[2001:db8::2]"),
            "dst IPv6 must be bracketed"
        );

        // Load it back into a fresh cache: the entry (unbracketed in memory)
        // must be identical.
        let mut reloaded = AltSvc::new();
        reloaded.load(&path).unwrap();
        assert_eq!(reloaded.entries(), asi.entries());

        // Saving the reloaded cache reproduces the exact same bytes.
        let path2 = temp_path("ipv6b");
        reloaded.save(Some(&path2)).unwrap();
        assert_eq!(fs::read_to_string(&path2).unwrap(), saved);

        let _ = fs::remove_file(&path);
        let _ = fs::remove_file(&path2);
    }

    // ---- Clock-dependent tests (serialized; CURL_TIME pinned) --------------

    #[test]
    fn clear_flushes_matching_origin_only() {
        let _guard = TIME_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        std::env::set_var("CURL_TIME", CURL_TIME_FIXED);

        let mut asi = AltSvc::new();
        asi.parse("h2=\":443\"\r\n", AlpnId::H1, "a.example", 80)
            .unwrap();
        asi.parse("h3=\":443\"\r\n", AlpnId::H1, "b.example", 80)
            .unwrap();
        assert_eq!(asi.len(), 2);

        // "clear" only affects the (h1, a.example, 80) origin.
        asi.parse("clear\r\n", AlpnId::H1, "a.example", 80).unwrap();
        assert_eq!(asi.len(), 1);
        assert_eq!(asi.entries()[0].src.host, "b.example");

        // A different origin's clear removes nothing more here.
        asi.parse("clear;\r\n", AlpnId::H2, "b.example", 80)
            .unwrap();
        assert_eq!(asi.len(), 1);
    }

    // Time-exact: depends on the `CURL_TIME` override, which `now_secs()` only
    // honors in debug builds (parity with curl's `#if defined(DEBUGBUILD) ||
    // defined(UNITTESTS)` guard on `altsvc_debugtime` and unit1654).
    #[test]
    #[cfg(debug_assertions)]
    fn lookup_matches_version_mask_and_prunes_expired() {
        let _guard = TIME_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        std::env::set_var("CURL_TIME", CURL_TIME_FIXED);
        let now: i64 = CURL_TIME_FIXED.parse().unwrap();

        let mut asi = AltSvc::new();
        // A live h3 alternative for (h1, origin.example, 443).
        asi.entries.push(AltSvcEntry {
            src: AltHost {
                host: "origin.example".into(),
                port: 443,
                alpnid: AlpnId::H1,
            },
            dst: AltHost {
                host: "alt.example".into(),
                port: 8443,
                alpnid: AlpnId::H3,
            },
            expires: now + 3600,
            persist: false,
            prio: 0,
        });

        // Version mask excludes H3 -> no match.
        assert!(asi
            .lookup(
                AlpnId::H1,
                "origin.example",
                443,
                (CURLALTSVC_H1 | CURLALTSVC_H2) as i32
            )
            .is_none());

        // Version mask includes H3 -> match, different destination.
        let m = asi
            .lookup(AlpnId::H1, "origin.example", 443, CURLALTSVC_H3 as i32)
            .expect("expected an h3 match");
        assert_eq!(m.alpnid, AlpnId::H3);
        assert_eq!(m.host, "alt.example");
        assert_eq!(m.port, 8443);
        assert!(!m.same_destination);

        // A same-destination alternative (only the protocol differs).
        let mut asi2 = AltSvc::new();
        asi2.entries.push(AltSvcEntry {
            src: AltHost {
                host: "same.example".into(),
                port: 443,
                alpnid: AlpnId::H1,
            },
            dst: AltHost {
                host: "same.example".into(),
                port: 443,
                alpnid: AlpnId::H2,
            },
            expires: now + 3600,
            persist: false,
            prio: 0,
        });
        let m2 = asi2
            .lookup(AlpnId::H1, "same.example", 443, CURLALTSVC_H2 as i32)
            .expect("expected an h2 match");
        assert!(m2.same_destination);

        // Expired entries are pruned during the scan and never matched.
        let mut asi3 = AltSvc::new();
        asi3.entries.push(AltSvcEntry {
            src: AltHost {
                host: "old.example".into(),
                port: 443,
                alpnid: AlpnId::H1,
            },
            dst: AltHost {
                host: "old.example".into(),
                port: 8443,
                alpnid: AlpnId::H3,
            },
            expires: now - 1, // already expired
            persist: false,
            prio: 0,
        });
        assert!(asi3
            .lookup(AlpnId::H1, "old.example", 443, CURLALTSVC_H3 as i32)
            .is_none());
        assert!(asi3.is_empty(), "expired entry must be pruned");
    }

    // ---- The full unit1654 byte-exact oracle -------------------------------

    // Time-exact byte oracle — debug-only, mirroring curl's unit1654 which is
    // itself gated behind DEBUGBUILD/UNITTESTS (it relies on the CURL_TIME
    // clock override to produce deterministic expiry timestamps).
    #[test]
    #[cfg(debug_assertions)]
    fn unit1654_load_parse_save_is_byte_exact() {
        let _guard = TIME_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        std::env::set_var("CURL_TIME", CURL_TIME_FIXED);

        // The input cache file (line 5 begins with a real TAB; two lines carry
        // leading blanks; `bad`/`rubbish` lines are intentionally invalid).
        let input = concat!(
            "h2 example.com 443 h3 shiny.example.com 8443 \"20191231 00:00:00\" 0 0\n",
            "# a comment\n",
            "h2 foo.example.com 443 h3 shiny.example.com 8443 \"20291231 23:30:00\" 0 0\n",
            "  h1 example.com 443 h3 shiny.example.com 8443 \"20121231 00:00:01\" 0 0\n",
            "\th3 example.com 443 h3 shiny.example.com 8443 \"20131231 00:00:00\" 0 0\n",
            "    # also a comment\n",
            "bad example.com 443 h3 shiny.example.com 8443 \"20191231 00:00:00\" 0 0\n",
            "rubbish\n",
        );
        let expected = concat!(
            "# Your alt-svc cache. https://curl.se/docs/alt-svc.html\n",
            "# This file was generated by libcurl! Edit at your own risk.\n",
            "h2 example.com 443 h3 shiny.example.com 8443 \"20191231 00:00:00\" 0 0\n",
            "h2 foo.example.com 443 h3 shiny.example.com 8443 \"20291231 23:30:00\" 0 0\n",
            "h1 example.com 443 h3 shiny.example.com 8443 \"20121231 00:00:01\" 0 0\n",
            "h3 example.com 443 h3 shiny.example.com 8443 \"20131231 00:00:00\" 0 0\n",
            "h1 example.org 8080 h2 example.com 8080 \"20190125 22:34:21\" 0 0\n",
            "h1 2.example.org 8080 h3 2.example.org 8080 \"20190125 22:34:21\" 0 0\n",
            "h1 3.example.org 8080 h2 example.com 8080 \"20190125 22:34:21\" 0 0\n",
            "h1 3.example.org 8080 h3 yesyes.com 8080 \"20190125 22:34:21\" 0 0\n",
            "h2 example.org 80 h2 example.com 443 \"20190124 22:36:21\" 0 0\n",
            "h2 example.net 80 h2 example.net 443 \"20190124 22:37:21\" 0 0\n",
            "h2 test.se 443 h2 test2.se 443 \"20190124 22:37:21\" 0 0\n",
            "h2 test.se 443 h2 test3.se 443 \"20190124 22:36:21\" 0 0\n",
        );

        let in_path = temp_path("1654-in");
        let out_path = temp_path("1654-out");
        fs::write(&in_path, input).unwrap();

        let mut asi = AltSvc::new();
        asi.load(&in_path).unwrap();
        assert_eq!(asi.len(), 4, "load: wrong number of entries");

        asi.parse(
            "h2=\"example.com:8080\"\r\n",
            AlpnId::H1,
            "example.org",
            8080,
        )
        .unwrap();
        assert_eq!(asi.len(), 5);

        asi.parse("h3=\":8080\"\r\n", AlpnId::H1, "2.example.org", 8080)
            .unwrap();
        assert_eq!(asi.len(), 6);

        asi.parse(
            "h2=\"example.com:8080\", h3=\"yesyes.com:8080\"\r\n",
            AlpnId::H1,
            "3.example.org",
            8080,
        )
        .unwrap();
        assert_eq!(asi.len(), 8, "that header should make two entries");

        asi.parse(
            "h2=\"example.com:443\"; ma = 120;\r\n",
            AlpnId::H2,
            "example.org",
            80,
        )
        .unwrap();
        assert_eq!(asi.len(), 9);

        asi.parse(
            "h2=\"example.net:443\"; ma=\"180\";\r\n",
            AlpnId::H2,
            "example.net",
            80,
        )
        .unwrap();
        assert_eq!(asi.len(), 10);

        asi.parse(
            "h2=\":443\"; ma=180, h3=\":443\"; persist = \"1\"; ma = 120;\r\n",
            AlpnId::H1,
            "curl.se",
            80,
        )
        .unwrap();
        assert_eq!(asi.len(), 12);

        asi.parse("clear;\r\n", AlpnId::H1, "curl.se", 80).unwrap();
        assert_eq!(asi.len(), 10, "clear; should drop the two curl.se entries");

        asi.parse(
            "h2=\":443\", h3=\":443\"; persist = \"1\"; ma = 120;\r\n",
            AlpnId::H1,
            "curl.se",
            80,
        )
        .unwrap();
        assert_eq!(asi.len(), 12);

        asi.parse("clear\r\n", AlpnId::H1, "curl.se", 80).unwrap();
        assert_eq!(asi.len(), 10, "clear (no semicolon) should also drop them");

        // Non-existing alpn: rejected, no change.
        asi.parse(
            "h6=\"example.net:443\"; ma=\"180\";\r\n",
            AlpnId::H2,
            "5.example.net",
            80,
        )
        .unwrap();
        assert_eq!(asi.len(), 10);

        // Missing quote in host: rejected.
        asi.parse(
            "h2=\"example.net:443,; ma=\"180\";\r\n",
            AlpnId::H2,
            "6.example.net",
            80,
        )
        .unwrap();
        assert_eq!(asi.len(), 10);

        // Missing port in hostname: rejected.
        asi.parse(
            "h2=\"example.net\"; ma=\"180\";\r\n",
            AlpnId::H2,
            "7.example.net",
            80,
        )
        .unwrap();
        assert_eq!(asi.len(), 10);

        // Illegal port (70000 > 65535): rejected.
        asi.parse(
            "h2=\"example.net:70000\"; ma=\"180\";\r\n",
            AlpnId::H2,
            "8.example.net",
            80,
        )
        .unwrap();
        assert_eq!(asi.len(), 10);

        // A quoted 'ma' with trailing space, an unknown flag, then a second
        // comma-separated alternative -> two new entries.
        asi.parse(
            "h2=\"test2.se:443\"; ma=\"180 \" ; unknown=2, h2=\"test3.se:443\"; ma = 120;\r\n",
            AlpnId::H2,
            "test.se",
            443,
        )
        .unwrap();
        assert_eq!(asi.len(), 12);

        // Save and diff against curl 8.x's expected byte stream.
        asi.save(Some(&out_path)).unwrap();
        let got = fs::read_to_string(&out_path).unwrap();
        assert_eq!(
            got, expected,
            "saved cache is not byte-identical to curl 8.x"
        );

        // Reloading the saved file yields the identical entry set and re-saves
        // to the same bytes (full save->load->save round-trip).
        let mut reloaded = AltSvc::new();
        reloaded.load(&out_path).unwrap();
        assert_eq!(reloaded.entries(), asi.entries());
        let out_path2 = temp_path("1654-out2");
        reloaded.save(Some(&out_path2)).unwrap();
        assert_eq!(fs::read_to_string(&out_path2).unwrap(), expected);

        let _ = fs::remove_file(&in_path);
        let _ = fs::remove_file(&out_path);
        let _ = fs::remove_file(&out_path2);
    }
}
