//! Alt-Svc (Alternative Service) cache — Rust rewrite of `lib/altsvc.c`.
//!
//! Implements HTTP Alt-Svc header parsing, storage, lookup, and file
//! persistence per [RFC 7838](https://datatracker.ietf.org/doc/html/rfc7838).
//!
//! The on-disk cache file format is byte-compatible with curl 8.x so that
//! existing `~/.cache/curl-alt-svc` files can be read/written without
//! conversion.
//!
//! # Cache File Format
//!
//! ```text
//! # Your alt-svc cache. https://curl.se/docs/alt-svc.html
//! # This file was generated by libcurl! Edit at your own risk.
//! h2 example.com 443 h3 alt.example.com 8443 "20251231 23:59:59" 1 0
//! ```
//!
//! Each data line contains space-separated fields:
//!
//! | Field      | Description                                      |
//! |------------|--------------------------------------------------|
//! | srcalpn    | Source ALPN identifier (`h1`, `h2`, `h3`)        |
//! | srchost    | Source hostname (brackets for IPv6)               |
//! | srcport    | Source port (0–65535)                             |
//! | dstalpn    | Destination ALPN identifier                      |
//! | dsthost    | Destination hostname (brackets for IPv6)         |
//! | dstport    | Destination port (0–65535)                        |
//! | date       | Expiry timestamp `"YYYYMMDD HH:MM:SS"` (UTC)    |
//! | persist    | Persist flag (`0` or `1`)                        |
//! | prio       | Priority (unsigned, currently always `0`)        |

use crate::error::{CurlError, CurlResult};
use chrono::{DateTime, Duration, NaiveDateTime, Utc};
use std::fs::File;
use std::io::{BufRead, BufReader, BufWriter, Write};
use tracing::{debug, info, warn};

// ---------------------------------------------------------------------------
// Constants — matching the C implementation in lib/altsvc.c
// ---------------------------------------------------------------------------

/// Bitmask: cache file is read-only — `save_file` becomes a no-op.
const CURLALTSVC_READONLYFILE: u32 = 1 << 2;

/// Bitmask: allow HTTP/1.1 alternative services.
const CURLALTSVC_H1: u32 = 1 << 3;

/// Bitmask: allow HTTP/2 alternative services.
const CURLALTSVC_H2: u32 = 1 << 4;

/// Bitmask: allow HTTP/3 alternative services.
const CURLALTSVC_H3: u32 = 1 << 5;

/// Maximum length of a single alt-svc cache file line.
const MAX_ALTSVC_LINE: usize = 4095;

/// Maximum hostname length accepted in cache entries.
const MAX_ALTSVC_HOSTLEN: usize = 2048;

/// Maximum ALPN identifier length accepted in cache entries.
const MAX_ALTSVC_ALPNLEN: usize = 10;

/// First line written to every alt-svc cache file.
const ALTSVC_HEADER_LINE1: &str =
    "# Your alt-svc cache. https://curl.se/docs/alt-svc.html\n";

/// Second line written to every alt-svc cache file.
const ALTSVC_HEADER_LINE2: &str =
    "# This file was generated by libcurl! Edit at your own risk.\n";

/// Default max-age for Alt-Svc entries when `ma` is not specified (24 h).
const DEFAULT_MAXAGE_SECS: i64 = 24 * 3600;

// ---------------------------------------------------------------------------
// Helper functions — ALPN mapping, host comparison, IPv6 detection
// ---------------------------------------------------------------------------

/// Converts an ALPN identifier string to the corresponding `CURLALTSVC_H*`
/// bitmask flag.  Returns `0` for unrecognised identifiers.
fn alpn_to_flag(alpn: &str) -> u32 {
    match alpn {
        "h1" => CURLALTSVC_H1,
        "h2" => CURLALTSVC_H2,
        "h3" => CURLALTSVC_H3,
        _ => 0,
    }
}

/// Returns an ALPN string for a given bitmask flag (inverse of
/// [`alpn_to_flag`]).  Falls back to an empty string for unknown flags.
///
/// This is the Rust equivalent of `Curl_alpnid2str()` from `lib/altsvc.c`.
pub fn flag_to_alpn(flag: u32) -> &'static str {
    match flag {
        f if f == CURLALTSVC_H1 => "h1",
        f if f == CURLALTSVC_H2 => "h2",
        f if f == CURLALTSVC_H3 => "h3",
        _ => "",
    }
}

/// Returns `true` when `alpn` is one of the three recognised identifiers.
fn is_valid_alpn(alpn: &str) -> bool {
    alpn_to_flag(alpn) != 0
}

/// Returns a numeric priority used to select the *best* alternative service
/// when multiple matches exist.  Higher is better: h3 > h2 > h1.
fn alpn_priority(alpn: &str) -> u32 {
    match alpn {
        "h3" => 3,
        "h2" => 2,
        "h1" => 1,
        _ => 0,
    }
}

/// Case-insensitive hostname comparison that ignores a trailing dot on `host`.
///
/// This mirrors the C `hostcompare()` function in `lib/altsvc.c`.
fn host_compare(host: &str, check: &str) -> bool {
    let h = host.strip_suffix('.').unwrap_or(host);
    h.eq_ignore_ascii_case(check)
}

/// Strips IPv6 brackets and trailing dots from a hostname for storage.
///
/// Hosts are stored *without* brackets internally; brackets are re-added
/// on output when the host is detected as an IPv6 literal.
fn normalize_host(host: &str) -> String {
    let h = host.trim();
    // Strip IPv6 brackets
    let h = if h.len() > 2 && h.starts_with('[') && h.ends_with(']') {
        &h[1..h.len() - 1]
    } else {
        h
    };
    // Strip trailing dot (for non-IPv6 hosts)
    let h = h.strip_suffix('.').unwrap_or(h);
    h.to_owned()
}

/// Returns `true` when `host` (stored without brackets) is an IPv6 literal.
fn is_ipv6(host: &str) -> bool {
    host.parse::<std::net::Ipv6Addr>().is_ok()
}

/// Formats a hostname for file output, wrapping IPv6 literals in brackets.
fn format_host(host: &str) -> String {
    if is_ipv6(host) {
        format!("[{}]", host)
    } else {
        host.to_owned()
    }
}

// ---------------------------------------------------------------------------
// Public data structures
// ---------------------------------------------------------------------------

/// Represents the origin (source) of an HTTP request — the combination of
/// scheme (ALPN identifier), hostname, and port that identifies where the
/// original request was directed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Origin {
    /// ALPN protocol identifier for the source, e.g. `"h1"`, `"h2"`, `"h3"`.
    pub scheme: String,
    /// Hostname of the source origin (stored without IPv6 brackets and without
    /// trailing dot).
    pub host: String,
    /// TCP port of the source origin.
    pub port: u16,
}

impl Origin {
    /// Constructs a new [`Origin`] with the given components.
    pub fn new(scheme: impl Into<String>, host: impl Into<String>, port: u16) -> Self {
        Self {
            scheme: scheme.into(),
            host: normalize_host(&host.into()),
            port,
        }
    }
}

/// Describes a single alternative service destination — the protocol, host,
/// and port to which a client *may* direct future requests.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AlternativeService {
    /// ALPN protocol identifier, e.g. `"h2"`, `"h3"`.
    pub alpn: String,
    /// Hostname of the alternative service (stored without IPv6 brackets).
    pub host: String,
    /// TCP port of the alternative service.
    pub port: u16,
}

impl AlternativeService {
    /// Constructs a new [`AlternativeService`].
    pub fn new(alpn: impl Into<String>, host: impl Into<String>, port: u16) -> Self {
        Self {
            alpn: alpn.into(),
            host: normalize_host(&host.into()),
            port,
        }
    }
}

/// A single Alt-Svc cache entry mapping a source [`Origin`] to an
/// [`AlternativeService`] with expiry and persistence metadata.
#[derive(Debug, Clone)]
pub struct AltSvcEntry {
    /// The source origin this entry applies to.
    pub src_origin: Origin,
    /// The alternative service destination.
    pub dst: AlternativeService,
    /// Expiry time as a Unix timestamp (seconds since 1970-01-01 00:00:00 UTC).
    pub expires: i64,
    /// Whether this entry should persist across sessions (`persist=1`).
    pub persist: bool,
    /// Priority hint (currently always `0` in curl 8.x).
    pub prio: u32,
}

/// Cache for HTTP Alt-Svc (Alternative Service) entries.
///
/// Manages Alt-Svc header parsing, cache file persistence, and service
/// lookup with protocol-version preference ordering.
///
/// # Example
///
/// ```ignore
/// use curl_rs_lib::altsvc::{AltSvcCache, Origin};
///
/// let mut cache = AltSvcCache::new();
/// cache.load_file("/tmp/alt-svc-cache").ok();
///
/// let origin = Origin::new("h2", "example.com", 443);
/// if let Some(alt) = cache.lookup(&origin) {
///     println!("upgrade to {}://{}:{}", alt.alpn, alt.host, alt.port);
/// }
/// ```
pub struct AltSvcCache {
    /// All stored alternative-service entries.
    entries: Vec<AltSvcEntry>,
    /// Path of the loaded cache file (used as fallback in [`save_file`]).
    filename: Option<String>,
    /// Bitmask controlling which protocol versions are accepted and whether
    /// the cache file is read-only.  Combines `CURLALTSVC_H1`, `CURLALTSVC_H2`,
    /// `CURLALTSVC_H3`, and `CURLALTSVC_READONLYFILE`.
    flags: u32,
}

// ---------------------------------------------------------------------------
// AltSvcCache implementation
// ---------------------------------------------------------------------------

impl AltSvcCache {
    // -- Construction -------------------------------------------------------

    /// Creates a new, empty Alt-Svc cache with all protocol versions enabled.
    ///
    /// The default flags are `CURLALTSVC_H1 | CURLALTSVC_H2 | CURLALTSVC_H3`.
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
            filename: None,
            flags: CURLALTSVC_H1 | CURLALTSVC_H2 | CURLALTSVC_H3,
        }
    }

    // -- Lookup -------------------------------------------------------------

    /// Looks up the best alternative service for `origin`.
    ///
    /// Expired entries are evicted during the scan.  Among matching entries
    /// the one with the highest protocol priority wins (h3 > h2 > h1).
    /// Only entries whose destination ALPN is allowed by the current
    /// [control flags](`Self::ctrl`) are considered.
    ///
    /// Returns `None` when no valid alternative exists.
    pub fn lookup(&mut self, origin: &Origin) -> Option<&AlternativeService> {
        let now = Utc::now().timestamp();

        // Evict expired entries (mirrors C Curl_altsvc_lookup behaviour).
        let expired_count = self.entries.iter().filter(|e| e.expires < now).count();
        if expired_count > 0 {
            debug!(
                "evicting {} expired alt-svc entries during lookup",
                expired_count
            );
        }
        self.entries.retain(|e| e.expires >= now);

        // Find the best match: same source origin + allowed destination ALPN,
        // preferring h3 > h2 > h1.
        let mut best_idx: Option<usize> = None;
        let mut best_prio: u32 = 0;

        let src_flag = alpn_to_flag(&origin.scheme);
        for (i, entry) in self.entries.iter().enumerate() {
            let entry_src_flag = alpn_to_flag(&entry.src_origin.scheme);
            if entry_src_flag == src_flag
                && host_compare(&origin.host, &entry.src_origin.host)
                && entry.src_origin.port == origin.port
                && (self.flags & alpn_to_flag(&entry.dst.alpn)) != 0
            {
                let prio = alpn_priority(&entry.dst.alpn);
                if best_idx.is_none() || prio > best_prio {
                    best_idx = Some(i);
                    best_prio = prio;
                }
            }
        }

        if let Some(idx) = best_idx {
            debug!(
                "alt-svc lookup hit: {}:{} -> {}://{}:{}",
                origin.host,
                origin.port,
                self.entries[idx].dst.alpn,
                self.entries[idx].dst.host,
                self.entries[idx].dst.port,
            );
        }

        best_idx.map(|idx| &self.entries[idx].dst)
    }

    // -- Mutation ------------------------------------------------------------

    /// Appends an entry to the cache.
    pub fn add(&mut self, entry: AltSvcEntry) {
        debug!(
            "add alt-svc: {}://{}:{} -> {}://{}:{}",
            entry.src_origin.scheme,
            entry.src_origin.host,
            entry.src_origin.port,
            entry.dst.alpn,
            entry.dst.host,
            entry.dst.port,
        );
        self.entries.push(entry);
    }

    /// Parses an `Alt-Svc` response header value (per RFC 7838) and stores
    /// all valid alternatives for the given source origin.
    ///
    /// The special value `clear` removes all cached alternatives for
    /// `src_origin`.  Multiple comma-separated alternatives in one header
    /// are supported.
    ///
    /// Invalid individual alternatives (bad hostname, unknown ALPN, etc.)
    /// are silently skipped — only catastrophic errors like memory exhaustion
    /// propagate as `CurlError`.
    pub fn parse_header(&mut self, value: &str, src_origin: &Origin) -> CurlResult<()> {
        let value = value.trim();
        if value.is_empty() {
            return Ok(());
        }

        // ---- Handle "clear" directive -------------------------------------
        if self.check_and_handle_clear(value, src_origin) {
            return Ok(());
        }

        // ---- Parse comma-separated alternatives ---------------------------
        let mut pos: &str = value;
        let mut entries_added: usize = 0;

        while let Some(eq_idx) = pos.find('=') {
            // Extract ALPN identifier (everything before '=')
            let alpn_raw = pos[..eq_idx].trim();
            if alpn_raw.len() > MAX_ALTSVC_ALPNLEN {
                break;
            }
            pos = &pos[eq_idx + 1..]; // skip past '='

            let dst_alpn = alpn_raw.to_owned();

            // Opening double-quote
            if !pos.starts_with('"') {
                break;
            }
            pos = &pos[1..];

            // ---- Parse host:port inside the quotes ------------------------
            let (dst_host, dst_port);
            if pos.starts_with(':') {
                // No hostname — use the source host.
                pos = &pos[1..]; // skip ':'
                dst_host = src_origin.host.clone();
            } else if pos.starts_with('[') {
                // IPv6 literal hostname inside brackets
                pos = &pos[1..]; // skip '['
                let bracket_end = match pos.find(']') {
                    Some(i) => i,
                    None => {
                        warn!("Bad alt-svc IPv6 hostname, ignoring.");
                        break;
                    }
                };
                dst_host = normalize_host(&pos[..bracket_end]);
                pos = &pos[bracket_end + 1..]; // skip past ']'
                // Expect ':' separator before port
                if !pos.starts_with(':') {
                    break;
                }
                pos = &pos[1..];
            } else {
                // Regular hostname — read up to ':'
                let colon_idx = match pos.find(':') {
                    Some(i) => i,
                    None => {
                        warn!("Bad alt-svc hostname, ignoring.");
                        break;
                    }
                };
                if colon_idx > MAX_ALTSVC_HOSTLEN {
                    warn!("Alt-svc hostname too long, ignoring.");
                    break;
                }
                dst_host = normalize_host(&pos[..colon_idx]);
                pos = &pos[colon_idx + 1..]; // skip past ':'
            }

            // Port number (digits up to closing quote)
            let port_end = pos
                .find(|c: char| !c.is_ascii_digit())
                .unwrap_or(pos.len());
            if port_end == 0 {
                warn!("Unknown alt-svc port number, ignoring.");
                break;
            }
            dst_port = match pos[..port_end].parse::<u16>() {
                Ok(p) => p,
                Err(_) => {
                    warn!("Unknown alt-svc port number, ignoring.");
                    break;
                }
            };
            pos = &pos[port_end..];

            // Closing double-quote
            if !pos.starts_with('"') {
                break;
            }
            pos = &pos[1..];

            // ---- Optional parameters after the quoted value ---------------
            let mut maxage: i64 = DEFAULT_MAXAGE_SECS;
            let mut persist = false;
            pos = pos.trim_start();
            if pos.starts_with(';') {
                pos = &pos[1..];
                self.parse_params(&mut pos, &mut maxage, &mut persist);
            }

            // ---- Create and store the entry if the ALPN is known ----------
            if alpn_to_flag(&dst_alpn) != 0 {
                // On the first valid alternative from this header, flush any
                // existing entries for this source origin (matches C behaviour
                // of `altsvc_flush` on `!entries++`).
                if entries_added == 0 {
                    self.flush_origin(src_origin);
                }
                entries_added += 1;

                let now = Utc::now();
                let duration = Duration::seconds(maxage);
                let expires = match now.checked_add_signed(duration) {
                    Some(dt) => dt.timestamp(),
                    None => i64::MAX,
                };

                let effective_host = if dst_host.is_empty() {
                    src_origin.host.clone()
                } else {
                    dst_host
                };

                let entry = AltSvcEntry {
                    src_origin: src_origin.clone(),
                    dst: AlternativeService {
                        alpn: dst_alpn.clone(),
                        host: effective_host.clone(),
                        port: dst_port,
                    },
                    expires,
                    persist,
                    prio: 0,
                };

                info!(
                    "Added alt-svc: {}:{} over {}",
                    effective_host, dst_port, dst_alpn
                );
                self.entries.push(entry);
            }

            // ---- Advance to the next comma-separated alternative ----------
            pos = pos.trim_start();
            if pos.starts_with(',') {
                pos = &pos[1..];
                pos = pos.trim_start();
            } else {
                break;
            }
        }

        Ok(())
    }

    // -- File I/O -----------------------------------------------------------

    /// Loads Alt-Svc entries from a curl-compatible cache file.
    ///
    /// Lines beginning with `#` are treated as comments and skipped.
    /// Individual lines that cannot be parsed are silently ignored (matching
    /// curl 8.x behaviour).  Only I/O errors propagate.
    ///
    /// The `path` is remembered so that [`save_file`](`Self::save_file`) can
    /// fall back to it when called with `None`.
    pub fn load_file(&mut self, path: &str) -> CurlResult<()> {
        self.filename = Some(path.to_owned());

        let file = match File::open(path) {
            Ok(f) => f,
            Err(e) => {
                // Non-existent file is not an error — the cache simply
                // starts empty, consistent with curl 8.x.
                if e.kind() == std::io::ErrorKind::NotFound {
                    debug!("alt-svc cache file not found: {}", path);
                    return Ok(());
                }
                warn!("failed to open alt-svc cache file: {}: {}", path, e);
                return Err(CurlError::ReadError);
            }
        };

        let reader = BufReader::new(file);
        let mut loaded: usize = 0;

        for line_result in reader.lines() {
            let line = match line_result {
                Ok(l) => l,
                Err(e) => {
                    warn!("I/O error reading alt-svc cache: {}", e);
                    return Err(CurlError::ReadError);
                }
            };

            let trimmed = line.trim();

            // Skip empty lines and comments
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }

            // Enforce maximum line length
            if trimmed.len() > MAX_ALTSVC_LINE {
                debug!("alt-svc cache line too long, skipping");
                continue;
            }

            // Attempt to parse the line into an entry
            if let Some(entry) = parse_cache_line(trimmed) {
                self.entries.push(entry);
                loaded += 1;
            }
        }

        info!("loaded {} alt-svc entries from {}", loaded, path);
        Ok(())
    }

    /// Writes all current entries to a curl-compatible cache file.
    ///
    /// If `path` is `None` the filename stored during [`load_file`] is used.
    /// If neither is available, or the `CURLALTSVC_READONLYFILE` flag is set,
    /// the call is a silent no-op (matching curl 8.x behaviour).
    pub fn save_file(&self, path: Option<&str>) -> CurlResult<()> {
        let file_path = match path {
            Some(p) if !p.is_empty() => p.to_owned(),
            _ => match &self.filename {
                Some(f) if !f.is_empty() => f.clone(),
                _ => return Ok(()),
            },
        };

        // Respect the read-only flag
        if self.flags & CURLALTSVC_READONLYFILE != 0 {
            debug!("alt-svc cache is read-only, skipping save");
            return Ok(());
        }

        let file = File::create(&file_path).map_err(|e| {
            warn!("failed to create alt-svc cache file: {}: {}", file_path, e);
            CurlError::WriteError
        })?;

        let mut writer = BufWriter::new(file);

        // Write header lines exactly matching curl 8.x output
        writer
            .write_all(ALTSVC_HEADER_LINE1.as_bytes())
            .map_err(|_| CurlError::WriteError)?;
        writer
            .write_all(ALTSVC_HEADER_LINE2.as_bytes())
            .map_err(|_| CurlError::WriteError)?;

        for entry in &self.entries {
            write_cache_entry(&mut writer, entry).map_err(|_| CurlError::WriteError)?;
        }

        writer.flush().map_err(|_| CurlError::WriteError)?;

        info!(
            "saved {} alt-svc entries to {}",
            self.entries.len(),
            file_path
        );
        Ok(())
    }

    // -- Control and lifecycle ----------------------------------------------

    /// Removes all entries from the cache.
    pub fn clear(&mut self) {
        debug!("clearing all {} alt-svc cache entries", self.entries.len());
        self.entries.clear();
    }

    /// Sets the control bitmask for the cache.
    ///
    /// `flags` is a combination of `CURLALTSVC_H1`, `CURLALTSVC_H2`,
    /// `CURLALTSVC_H3`, and optionally `CURLALTSVC_READONLYFILE`.
    ///
    /// Passing `0` is an error (`CurlError::BadFunctionArgument`), matching
    /// the C `Curl_altsvc_ctrl` behaviour.
    pub fn ctrl(&mut self, flags: u32) -> CurlResult<()> {
        if flags == 0 {
            return Err(CurlError::BadFunctionArgument);
        }
        self.flags = flags;
        debug!("alt-svc control flags set to 0x{:x}", flags);
        Ok(())
    }

    /// Releases all resources held by the cache, resetting it to a freshly-
    /// constructed state.
    ///
    /// This is the Rust equivalent of `Curl_altsvc_cleanup` from
    /// `lib/altsvc.c`.
    pub fn cleanup(&mut self) {
        debug!("cleaning up alt-svc cache");
        self.entries.clear();
        self.filename = None;
        self.flags = CURLALTSVC_H1 | CURLALTSVC_H2 | CURLALTSVC_H3;
    }

    // -- Private helpers ----------------------------------------------------

    /// Returns `true` and flushes the origin if `value` is the `clear`
    /// directive.
    fn check_and_handle_clear(&mut self, value: &str, src_origin: &Origin) -> bool {
        // Extract the first token before any semicolon, newline, or CR.
        let first_token = value
            .split([';', '\n', '\r'])
            .next()
            .unwrap_or("")
            .trim();

        if first_token.eq_ignore_ascii_case("clear") {
            info!(
                "alt-svc clear directive for {}://{}:{}",
                src_origin.scheme, src_origin.host, src_origin.port
            );
            self.flush_origin(src_origin);
            true
        } else {
            false
        }
    }

    /// Removes all cached entries whose source origin matches `origin`.
    fn flush_origin(&mut self, origin: &Origin) {
        let src_flag = alpn_to_flag(&origin.scheme);
        let before = self.entries.len();
        self.entries.retain(|e| {
            let entry_flag = alpn_to_flag(&e.src_origin.scheme);
            !(entry_flag == src_flag
                && host_compare(&origin.host, &e.src_origin.host)
                && e.src_origin.port == origin.port)
        });
        let removed = before - self.entries.len();
        if removed > 0 {
            debug!("flushed {} alt-svc entries for origin", removed);
        }
    }

    /// Parses optional `; key=value` parameters from an Alt-Svc header value.
    ///
    /// Recognised keys: `ma` (max-age in seconds), `persist` (1 = persist
    /// across sessions).  Unknown keys are silently skipped.
    fn parse_params(&self, pos: &mut &str, maxage: &mut i64, persist: &mut bool) {
        loop {
            *pos = pos.trim_start();

            // Extract key (up to '=')
            let eq_idx = match pos.find('=') {
                Some(i) => i,
                None => break,
            };
            // Guard against malformed keys that span across comma boundaries
            let comma_idx = pos.find(',').unwrap_or(pos.len());
            if eq_idx > comma_idx {
                break;
            }

            let key = pos[..eq_idx].trim();
            *pos = &pos[eq_idx + 1..];

            // Extract value — may be quoted or bare
            let val_str;
            if pos.starts_with('"') {
                *pos = &pos[1..]; // skip opening quote
                let end = pos.find('"').unwrap_or(pos.len());
                val_str = &pos[..end];
                if end < pos.len() {
                    *pos = &pos[end + 1..]; // skip closing quote
                } else {
                    *pos = &pos[end..];
                }
            } else {
                let end = pos
                    .find(|c: char| c == ',' || c == ';' || c.is_ascii_whitespace())
                    .unwrap_or(pos.len());
                val_str = &pos[..end];
                *pos = &pos[end..];
            }

            // Interpret known parameters
            if let Ok(num) = val_str.parse::<i64>() {
                if key.eq_ignore_ascii_case("ma") {
                    *maxage = num;
                } else if key.eq_ignore_ascii_case("persist") && num == 1 {
                    *persist = true;
                }
            }

            *pos = pos.trim_start();
            if pos.starts_with(';') {
                *pos = &pos[1..];
            } else {
                break;
            }
        }
    }
}

impl Default for AltSvcCache {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Private file-format helpers
// ---------------------------------------------------------------------------

/// Parses a single cache file line into an [`AltSvcEntry`].
///
/// Returns `None` for lines that cannot be parsed (comments, empty, or
/// malformed).  This mirrors the forgiving parsing in the C `altsvc_add()`
/// function which silently skips bad lines.
///
/// Expected format (fields separated by exactly one space):
/// ```text
/// srcalpn srchost srcport dstalpn dsthost dstport "YYYYMMDD HH:MM:SS" persist prio
/// ```
fn parse_cache_line(line: &str) -> Option<AltSvcEntry> {
    // Tokenise on whitespace.  The date field contains a space but is
    // enclosed in double-quotes, so we split into at least 10 tokens:
    //   0: srcalpn, 1: srchost, 2: srcport,
    //   3: dstalpn, 4: dsthost, 5: dstport,
    //   6: "YYYYMMDD (date-part with opening quote),
    //   7: HH:MM:SS" (time-part with closing quote),
    //   8: persist, 9: prio
    let tokens: Vec<&str> = line.split_whitespace().collect();
    if tokens.len() < 9 {
        return None;
    }

    let src_alpn = tokens[0];
    let src_host_raw = tokens[1];
    let src_port: u16 = tokens[2].parse().ok()?;
    let dst_alpn = tokens[3];
    let dst_host_raw = tokens[4];
    let dst_port: u16 = tokens[5].parse().ok()?;

    // Validate ALPN identifiers
    if !is_valid_alpn(src_alpn) || !is_valid_alpn(dst_alpn) {
        return None;
    }

    // Validate field lengths
    if src_alpn.len() > MAX_ALTSVC_ALPNLEN
        || dst_alpn.len() > MAX_ALTSVC_ALPNLEN
        || src_host_raw.len() > MAX_ALTSVC_HOSTLEN
        || dst_host_raw.len() > MAX_ALTSVC_HOSTLEN
    {
        return None;
    }

    // Reconstruct the quoted date string.
    // tokens[6] starts with `"`, tokens[7] ends with `"`.
    let date_part = tokens[6].trim_start_matches('"');
    let time_part = tokens[7].trim_end_matches('"');
    let date_str = format!("{} {}", date_part, time_part);

    // Parse the date into a Unix timestamp (UTC).
    let naive_dt = NaiveDateTime::parse_from_str(&date_str, "%Y%m%d %H:%M:%S").ok()?;
    let expires = naive_dt.and_utc().timestamp();

    // Persist flag (field 8)
    let persist_val: u32 = tokens[8].parse().unwrap_or(0);

    // Priority (field 9, optional — defaults to 0)
    let prio: u32 = if tokens.len() > 9 {
        tokens[9].parse().unwrap_or(0)
    } else {
        0
    };

    Some(AltSvcEntry {
        src_origin: Origin {
            scheme: src_alpn.to_owned(),
            host: normalize_host(src_host_raw),
            port: src_port,
        },
        dst: AlternativeService {
            alpn: dst_alpn.to_owned(),
            host: normalize_host(dst_host_raw),
            port: dst_port,
        },
        expires,
        persist: persist_val != 0,
        prio,
    })
}

/// Writes a single [`AltSvcEntry`] to a cache file writer in the curl 8.x
/// compatible format.
///
/// Output line format (matching `altsvc_out()` in `lib/altsvc.c`):
/// ```text
/// srcalpn srchost srcport dstalpn dsthost dstport "YYYYMMDD HH:MM:SS" persist prio\n
/// ```
fn write_cache_entry<W: Write>(writer: &mut W, entry: &AltSvcEntry) -> std::io::Result<()> {
    // Convert the Unix timestamp to a UTC datetime for formatting.
    let dt: DateTime<Utc> = match DateTime::from_timestamp(entry.expires, 0) {
        Some(d) => d,
        None => {
            // Fallback: use epoch if the timestamp is out of range.
            DateTime::from_timestamp(0, 0).expect("epoch is always valid")
        }
    };
    let naive = dt.naive_utc();

    // Format the date portion exactly as the C code does:
    //   "%d%02d%02d %02d:%02d:%02d"
    //   with tm_year+1900, tm_mon+1, tm_mday, tm_hour, tm_min, tm_sec
    //
    // chrono's `%Y%m%d %H:%M:%S` produces identical output for dates in the
    // range 1000–9999 (year is always 4 digits).
    let date_formatted = naive.format("%Y%m%d %H:%M:%S");

    let src_host_fmt = format_host(&entry.src_origin.host);
    let dst_host_fmt = format_host(&entry.dst.host);

    writer.write_fmt(format_args!(
        "{} {} {} {} {} {} \"{}\" {} {}\n",
        entry.src_origin.scheme,
        src_host_fmt,
        entry.src_origin.port,
        entry.dst.alpn,
        dst_host_fmt,
        entry.dst.port,
        date_formatted,
        if entry.persist { 1u32 } else { 0u32 },
        entry.prio,
    ))
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -- Origin / AlternativeService construction ---------------------------

    #[test]
    fn origin_strips_trailing_dot() {
        let o = Origin::new("h2", "example.com.", 443);
        assert_eq!(o.host, "example.com");
    }

    #[test]
    fn origin_strips_ipv6_brackets() {
        let o = Origin::new("h2", "[::1]", 443);
        assert_eq!(o.host, "::1");
    }

    #[test]
    fn alternative_service_new() {
        let a = AlternativeService::new("h3", "alt.example.com", 8443);
        assert_eq!(a.alpn, "h3");
        assert_eq!(a.host, "alt.example.com");
        assert_eq!(a.port, 8443);
    }

    // -- Helper function tests ----------------------------------------------

    #[test]
    fn alpn_flag_roundtrip() {
        assert_eq!(flag_to_alpn(alpn_to_flag("h1")), "h1");
        assert_eq!(flag_to_alpn(alpn_to_flag("h2")), "h2");
        assert_eq!(flag_to_alpn(alpn_to_flag("h3")), "h3");
        assert_eq!(alpn_to_flag("unknown"), 0);
    }

    #[test]
    fn host_compare_basic() {
        assert!(host_compare("example.com", "example.com"));
        assert!(host_compare("EXAMPLE.COM", "example.com"));
        assert!(host_compare("example.com.", "example.com"));
        assert!(!host_compare("other.com", "example.com"));
    }

    #[test]
    fn normalize_host_ipv6() {
        assert_eq!(normalize_host("[::1]"), "::1");
        assert_eq!(normalize_host("example.com."), "example.com");
        assert_eq!(normalize_host("example.com"), "example.com");
    }

    #[test]
    fn ipv6_detection() {
        assert!(is_ipv6("::1"));
        assert!(is_ipv6("2001:db8::1"));
        assert!(!is_ipv6("example.com"));
        assert!(!is_ipv6("192.168.1.1"));
    }

    #[test]
    fn format_host_ipv6_gets_brackets() {
        assert_eq!(format_host("::1"), "[::1]");
        assert_eq!(format_host("example.com"), "example.com");
    }

    // -- Cache line parsing -------------------------------------------------

    #[test]
    fn parse_valid_cache_line() {
        let line = r#"h2 example.com 443 h3 alt.example.com 8443 "20251231 23:59:59" 1 0"#;
        let entry = parse_cache_line(line).expect("should parse");
        assert_eq!(entry.src_origin.scheme, "h2");
        assert_eq!(entry.src_origin.host, "example.com");
        assert_eq!(entry.src_origin.port, 443);
        assert_eq!(entry.dst.alpn, "h3");
        assert_eq!(entry.dst.host, "alt.example.com");
        assert_eq!(entry.dst.port, 8443);
        assert!(entry.persist);
        assert_eq!(entry.prio, 0);

        // Verify the date parsed correctly (2025-12-31 23:59:59 UTC)
        let expected = NaiveDateTime::parse_from_str("20251231 23:59:59", "%Y%m%d %H:%M:%S")
            .unwrap()
            .and_utc()
            .timestamp();
        assert_eq!(entry.expires, expected);
    }

    #[test]
    fn parse_cache_line_ipv6() {
        let line = r#"h2 [::1] 443 h3 [2001:db8::1] 8443 "20301231 12:00:00" 0 0"#;
        let entry = parse_cache_line(line).expect("should parse");
        assert_eq!(entry.src_origin.host, "::1");
        assert_eq!(entry.dst.host, "2001:db8::1");
        assert!(!entry.persist);
    }

    #[test]
    fn parse_cache_line_invalid_alpn() {
        let line = r#"xx example.com 443 yy alt.com 8443 "20251231 23:59:59" 0 0"#;
        assert!(parse_cache_line(line).is_none());
    }

    #[test]
    fn parse_cache_line_comment_is_none() {
        // Comments should not reach parse_cache_line (filtered by load_file),
        // but if they do the function returns None.
        assert!(parse_cache_line("# comment").is_none());
    }

    #[test]
    fn parse_cache_line_too_few_fields() {
        assert!(parse_cache_line("h2 example.com 443").is_none());
    }

    // -- Cache file roundtrip -----------------------------------------------

    #[test]
    fn write_and_parse_roundtrip() {
        let entry = AltSvcEntry {
            src_origin: Origin::new("h2", "example.com", 443),
            dst: AlternativeService::new("h3", "alt.example.com", 8443),
            expires: NaiveDateTime::parse_from_str("20251231 23:59:59", "%Y%m%d %H:%M:%S")
                .unwrap()
                .and_utc()
                .timestamp(),
            persist: true,
            prio: 0,
        };

        let mut buf = Vec::new();
        write_cache_entry(&mut buf, &entry).expect("write should succeed");
        let line = std::str::from_utf8(&buf).unwrap().trim();

        let parsed = parse_cache_line(line).expect("parse should succeed");
        assert_eq!(parsed.src_origin.scheme, entry.src_origin.scheme);
        assert_eq!(parsed.src_origin.host, entry.src_origin.host);
        assert_eq!(parsed.src_origin.port, entry.src_origin.port);
        assert_eq!(parsed.dst.alpn, entry.dst.alpn);
        assert_eq!(parsed.dst.host, entry.dst.host);
        assert_eq!(parsed.dst.port, entry.dst.port);
        assert_eq!(parsed.expires, entry.expires);
        assert_eq!(parsed.persist, entry.persist);
        assert_eq!(parsed.prio, entry.prio);
    }

    // -- AltSvcCache lifecycle ----------------------------------------------

    #[test]
    fn new_cache_is_empty() {
        let cache = AltSvcCache::new();
        assert_eq!(cache.entries.len(), 0);
    }

    #[test]
    fn add_and_lookup() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h2", "example.com", 443);
        let entry = AltSvcEntry {
            src_origin: origin.clone(),
            dst: AlternativeService::new("h3", "alt.example.com", 8443),
            expires: Utc::now().timestamp() + 3600,
            persist: false,
            prio: 0,
        };
        cache.add(entry);

        let result = cache.lookup(&origin);
        assert!(result.is_some());
        let alt = result.unwrap();
        assert_eq!(alt.alpn, "h3");
        assert_eq!(alt.host, "alt.example.com");
        assert_eq!(alt.port, 8443);
    }

    #[test]
    fn lookup_evicts_expired() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h2", "example.com", 443);
        let expired_entry = AltSvcEntry {
            src_origin: origin.clone(),
            dst: AlternativeService::new("h3", "alt.example.com", 8443),
            expires: Utc::now().timestamp() - 1, // already expired
            persist: false,
            prio: 0,
        };
        cache.add(expired_entry);

        let result = cache.lookup(&origin);
        assert!(result.is_none());
        assert_eq!(cache.entries.len(), 0);
    }

    #[test]
    fn lookup_prefers_h3_over_h2() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h1", "example.com", 80);
        let future = Utc::now().timestamp() + 3600;

        cache.add(AltSvcEntry {
            src_origin: origin.clone(),
            dst: AlternativeService::new("h2", "example.com", 443),
            expires: future,
            persist: false,
            prio: 0,
        });
        cache.add(AltSvcEntry {
            src_origin: origin.clone(),
            dst: AlternativeService::new("h3", "example.com", 443),
            expires: future,
            persist: false,
            prio: 0,
        });

        let alt = cache.lookup(&origin).expect("should find match");
        assert_eq!(alt.alpn, "h3");
    }

    #[test]
    fn lookup_respects_version_flags() {
        let mut cache = AltSvcCache::new();
        // Only allow h2
        cache.ctrl(CURLALTSVC_H2).unwrap();

        let origin = Origin::new("h1", "example.com", 80);
        let future = Utc::now().timestamp() + 3600;

        cache.add(AltSvcEntry {
            src_origin: origin.clone(),
            dst: AlternativeService::new("h3", "example.com", 443),
            expires: future,
            persist: false,
            prio: 0,
        });

        // h3 should not be returned because only h2 is allowed
        assert!(cache.lookup(&origin).is_none());
    }

    #[test]
    fn clear_removes_all() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h2", "example.com", 443);
        let future = Utc::now().timestamp() + 3600;
        cache.add(AltSvcEntry {
            src_origin: origin.clone(),
            dst: AlternativeService::new("h3", "alt.example.com", 8443),
            expires: future,
            persist: false,
            prio: 0,
        });
        assert_eq!(cache.entries.len(), 1);
        cache.clear();
        assert_eq!(cache.entries.len(), 0);
    }

    #[test]
    fn ctrl_rejects_zero() {
        let mut cache = AltSvcCache::new();
        let result = cache.ctrl(0);
        assert!(result.is_err());
        match result.unwrap_err() {
            CurlError::BadFunctionArgument => {}
            other => panic!("expected BadFunctionArgument, got {:?}", other),
        }
    }

    #[test]
    fn cleanup_resets_state() {
        let mut cache = AltSvcCache::new();
        cache.filename = Some("/tmp/test".to_owned());
        cache.flags = CURLALTSVC_H3;
        let origin = Origin::new("h2", "example.com", 443);
        cache.add(AltSvcEntry {
            src_origin: origin,
            dst: AlternativeService::new("h3", "alt.example.com", 8443),
            expires: Utc::now().timestamp() + 3600,
            persist: false,
            prio: 0,
        });
        cache.cleanup();
        assert_eq!(cache.entries.len(), 0);
        assert!(cache.filename.is_none());
        assert_eq!(
            cache.flags,
            CURLALTSVC_H1 | CURLALTSVC_H2 | CURLALTSVC_H3
        );
    }

    // -- Alt-Svc header parsing ---------------------------------------------

    #[test]
    fn parse_header_simple() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h2", "example.com", 443);
        cache
            .parse_header(r#"h3=":443""#, &origin)
            .expect("should parse");
        assert_eq!(cache.entries.len(), 1);
        let e = &cache.entries[0];
        assert_eq!(e.dst.alpn, "h3");
        assert_eq!(e.dst.host, "example.com"); // inherited from origin
        assert_eq!(e.dst.port, 443);
    }

    #[test]
    fn parse_header_with_host_and_params() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h2", "example.com", 443);
        cache
            .parse_header(r#"h3="alt.example.com:8443"; ma=7200; persist=1"#, &origin)
            .expect("should parse");
        assert_eq!(cache.entries.len(), 1);
        let e = &cache.entries[0];
        assert_eq!(e.dst.host, "alt.example.com");
        assert_eq!(e.dst.port, 8443);
        assert!(e.persist);
        // Verify expiry is roughly now + 7200 seconds
        let now = Utc::now().timestamp();
        assert!(e.expires >= now + 7100 && e.expires <= now + 7300);
    }

    #[test]
    fn parse_header_multiple_alternatives() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h1", "example.com", 80);
        cache
            .parse_header(r#"h2=":443", h3=":443""#, &origin)
            .expect("should parse");
        assert_eq!(cache.entries.len(), 2);
        assert_eq!(cache.entries[0].dst.alpn, "h2");
        assert_eq!(cache.entries[1].dst.alpn, "h3");
    }

    #[test]
    fn parse_header_clear() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h2", "example.com", 443);

        // Pre-populate
        cache.add(AltSvcEntry {
            src_origin: origin.clone(),
            dst: AlternativeService::new("h3", "alt.example.com", 8443),
            expires: Utc::now().timestamp() + 3600,
            persist: false,
            prio: 0,
        });
        assert_eq!(cache.entries.len(), 1);

        // "clear" should remove all entries for this origin
        cache.parse_header("clear", &origin).expect("should parse");
        assert_eq!(cache.entries.len(), 0);
    }

    #[test]
    fn parse_header_empty_is_noop() {
        let mut cache = AltSvcCache::new();
        let origin = Origin::new("h2", "example.com", 443);
        cache.parse_header("", &origin).expect("should succeed");
        assert_eq!(cache.entries.len(), 0);
    }

    // -- File I/O integration -----------------------------------------------

    #[test]
    fn load_nonexistent_file_is_ok() {
        let mut cache = AltSvcCache::new();
        let result = cache.load_file("/tmp/nonexistent_altsvc_cache_12345");
        assert!(result.is_ok());
        assert_eq!(cache.entries.len(), 0);
    }

    #[test]
    fn save_with_readonly_flag_is_noop() {
        let mut cache = AltSvcCache::new();
        cache
            .ctrl(CURLALTSVC_H1 | CURLALTSVC_H2 | CURLALTSVC_H3 | CURLALTSVC_READONLYFILE)
            .unwrap();
        // This should succeed silently without creating a file
        let result = cache.save_file(Some("/tmp/should_not_exist_altsvc"));
        assert!(result.is_ok());
    }

    #[test]
    fn save_and_load_roundtrip() {
        let path = "/tmp/blitzy_test_altsvc_roundtrip.txt";

        // Create a cache with entries and save it
        let mut cache = AltSvcCache::new();
        let future = NaiveDateTime::parse_from_str("20301231 23:59:59", "%Y%m%d %H:%M:%S")
            .unwrap()
            .and_utc()
            .timestamp();

        cache.add(AltSvcEntry {
            src_origin: Origin::new("h2", "example.com", 443),
            dst: AlternativeService::new("h3", "alt.example.com", 8443),
            expires: future,
            persist: true,
            prio: 0,
        });
        cache.add(AltSvcEntry {
            src_origin: Origin::new("h1", "other.com", 80),
            dst: AlternativeService::new("h2", "other.com", 443),
            expires: future,
            persist: false,
            prio: 0,
        });

        cache.save_file(Some(path)).expect("save should succeed");

        // Load into a fresh cache and verify
        let mut cache2 = AltSvcCache::new();
        cache2.load_file(path).expect("load should succeed");
        assert_eq!(cache2.entries.len(), 2);

        assert_eq!(cache2.entries[0].src_origin.scheme, "h2");
        assert_eq!(cache2.entries[0].src_origin.host, "example.com");
        assert_eq!(cache2.entries[0].dst.alpn, "h3");
        assert_eq!(cache2.entries[0].dst.host, "alt.example.com");
        assert_eq!(cache2.entries[0].dst.port, 8443);
        assert!(cache2.entries[0].persist);

        assert_eq!(cache2.entries[1].src_origin.scheme, "h1");
        assert_eq!(cache2.entries[1].dst.alpn, "h2");
        assert!(!cache2.entries[1].persist);

        // Cleanup
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn default_creates_same_as_new() {
        let cache = AltSvcCache::default();
        assert_eq!(cache.entries.len(), 0);
        assert_eq!(
            cache.flags,
            CURLALTSVC_H1 | CURLALTSVC_H2 | CURLALTSVC_H3
        );
    }

    // -- Priority ordering --------------------------------------------------

    #[test]
    fn alpn_priority_ordering() {
        assert!(alpn_priority("h3") > alpn_priority("h2"));
        assert!(alpn_priority("h2") > alpn_priority("h1"));
        assert!(alpn_priority("h1") > alpn_priority("unknown"));
    }
}
