// SPDX-License-Identifier: curl

//! HTTP Strict Transport Security (HSTS) cache — RFC 6797.
//!
//! This module is a faithful, behavior-preserving Rust port of curl's
//! `lib/hsts.c` (and its declaration companion `lib/hsts.h`). It maintains the
//! in-memory HSTS store, persists it to (and loads it from) the on-disk cache
//! file, ingests `Strict-Transport-Security` response headers, and answers the
//! single question the transfer layer asks before every `http://` request:
//! *"is this host known-HSTS, and must therefore be upgraded to `https://`?"*
//! (In curl this is the `Curl_hsts(..., TRUE)` call at `lib/url.c`.)
//!
//! # Parity contract
//!
//! The persisted file format is **byte-compatible** with curl 8.x, which is a
//! hard requirement (AAP §0.6.3): a file written by this module must be
//! readable by a curl 8.x reference binary and vice-versa. Concretely, the
//! writer reproduces curl's exact output:
//!
//! ```text
//! # Your HSTS cache. https://curl.se/docs/hsts.html
//! # This file was generated by libcurl! Edit at your own risk.
//! .example.com "20370101 00:00:00"
//! example.net "unlimited"
//! ```
//!
//! Each entry line is `curl_mfprintf(fp, "%s%s \"%s\"\n", …)` in the C source:
//! an optional leading `.` when the entry carries `includeSubDomains`, then the
//! host, a space, then a double-quoted expiry stamp. The stamp is either
//! `YYYYMMDD HH:MM:SS` in UTC (formatted exactly like curl's
//! `"%d%02d%02d %02d:%02d:%02d"`) or the sentinel string `unlimited` for
//! entries that never expire.
//!
//! # Matching semantics
//!
//! [`Hsts::is_hsts`] mirrors curl's `Curl_hsts`: it strips a single trailing
//! dot from the query name, ignores expired entries, returns immediately on an
//! exact (ASCII case-insensitive) host match, and otherwise honors the
//! *longest* `includeSubDomains` tail match. A tail match requires the stored
//! host to be strictly shorter than the query (`ntail < hlen`), the byte
//! immediately preceding the tail in the query to be a `.`, and the tail bytes
//! to compare equal case-insensitively — precisely the rule in `hsts.c`.
//!
//! # Header ingestion
//!
//! [`Hsts::parse`] mirrors `Curl_hsts_parse`: it walks the header's
//! `;`-separated directives, recognizing `max-age` (mandatory) and
//! `includeSubDomains` (the `preload` token is ignored), rejecting duplicates,
//! and applying RFC 6797 rules — `max-age=0` deletes an existing entry, IP
//! address hosts are excluded entirely, and an overflowing `max-age` saturates
//! to the "unlimited" sentinel.
//!
//! # Callback parity
//!
//! curl exposes `CURLOPT_HSTSREADFUNCTION` / `CURLOPT_HSTSWRITEFUNCTION` so an
//! application can supply / receive entries programmatically. Those C hook
//! points are preserved (AAP §0.6.1); this module exposes the Rust-side hooks
//! ([`Hsts::load_from_callback`] / [`Hsts::save_to_callback`], driven by
//! [`HstsEntry`] and [`HstsCode`]) that the FFI trampoline in `curl-rs-ffi`
//! wires the C callbacks onto.
//!
//! # Feature gating
//!
//! In the C tree this file is compiled only when
//! `!defined(CURL_DISABLE_HTTP) && !defined(CURL_DISABLE_HSTS)`. In the Rust
//! workspace the equivalent gate is applied at the `mod hsts;` declaration in
//! the crate root (under the default-on `http` feature), so this file is kept
//! self-contained and dependency-light.
//!
//! # Safety
//!
//! This module is written entirely in safe Rust: it performs no raw-pointer
//! manipulation and never panics on file- or network-derived input (every
//! fallible operation returns an [`Error`]). The token that denotes non-safe
//! Rust is intentionally absent from this file so the crate-wide `grep` audit
//! stays green.

use std::time::{SystemTime, UNIX_EPOCH};

use chrono::{DateTime, Datelike, NaiveDate, NaiveDateTime, NaiveTime, Timelike, Utc};

use crate::error::{Error, Result};

// ---------------------------------------------------------------------------
// Constants — transcribed verbatim from lib/hsts.c
// ---------------------------------------------------------------------------

/// Maximum accepted length of a single line in the on-disk cache file.
///
/// Mirrors `#define MAX_HSTS_LINE 4095`. Lines longer than this are rejected
/// by the loader exactly as curl rejects them.
pub const MAX_HSTS_LINE: usize = 4095;

/// Maximum accepted host-name length, in bytes.
///
/// Mirrors `#define MAX_HSTS_HOSTLEN 2048`. Both the file parser and
/// [`Hsts::is_hsts`] treat a longer host as a non-match.
pub const MAX_HSTS_HOSTLEN: usize = 2048;

/// Maximum accepted length of the quoted expiry field in the file, in bytes.
///
/// Mirrors `#define MAX_HSTS_DATELEN 256`.
pub const MAX_HSTS_DATELEN: usize = 256;

/// The sentinel string curl writes (and reads) for entries that never expire.
///
/// Mirrors `#define UNLIMITED "unlimited"`.
pub const UNLIMITED: &str = "unlimited";

/// Enable-HSTS bit for the `CURLOPT_HSTS_CTRL` bitmask.
///
/// Mirrors `#define CURLHSTS_ENABLE (1L << 0)` from `include/curl/curl.h`.
pub const CURLHSTS_ENABLE: u32 = 1 << 0;

/// Read-only-file bit for the `CURLOPT_HSTS_CTRL` bitmask.
///
/// Mirrors `#define CURLHSTS_READONLYFILE (1L << 1)`. When set, [`Hsts::save`]
/// leaves the backing file untouched.
pub const CURLHSTS_READONLYFILE: u32 = 1 << 1;

/// The two comment lines curl writes at the top of every saved cache file.
///
/// Reproduced verbatim (including the trailing newlines) so that a file this
/// module writes is byte-identical to one curl 8.x writes for the same set of
/// entries.
const FILE_HEADER: &str = "# Your HSTS cache. https://curl.se/docs/hsts.html\n\
                           # This file was generated by libcurl! Edit at your own risk.\n";

// ---------------------------------------------------------------------------
// Callback types — parity with CURLSTScode / struct curl_hstsentry
// ---------------------------------------------------------------------------

/// Status code returned by the HSTS read/write callbacks.
///
/// Mirrors the C `CURLSTScode` enum from `include/curl/curl.h`:
///
/// ```c
/// typedef enum { CURLSTS_OK, CURLSTS_DONE, CURLSTS_FAIL } CURLSTScode;
/// ```
///
/// The discriminants are pinned to the C integer values so the FFI trampoline
/// can convert with a plain cast.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HstsCode {
    /// `CURLSTS_OK` — the callback produced/accepted an entry; keep going.
    Ok = 0,
    /// `CURLSTS_DONE` — iteration is finished; stop without error.
    Done = 1,
    /// `CURLSTS_FAIL` — the callback failed; abort the operation.
    Fail = 2,
}

/// A single HSTS entry as exchanged with an application callback.
///
/// Mirrors `struct curl_hstsentry` from `include/curl/curl.h`:
///
/// ```c
/// struct curl_hstsentry {
///   char *name;
///   size_t namelen;
///   unsigned int includeSubDomains:1;
///   char expire[18]; /* YYYYMMDD HH:MM:SS [null-terminated] */
/// };
/// ```
///
/// The `expire` field uses curl's textual convention: an empty string on the
/// read side means "no expiry" (unlimited); on the write side an unlimited
/// entry is rendered as the [`UNLIMITED`] sentinel, otherwise as
/// `YYYYMMDD HH:MM:SS` in UTC.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct HstsEntry {
    /// The host name (without any leading `.`), as C's `name` / `namelen`.
    pub name: String,
    /// Whether the entry applies to sub-domains, as C's `includeSubDomains`.
    pub include_subdomains: bool,
    /// The textual expiry stamp, as C's `expire[18]` (see the type docs).
    pub expire: String,
}

// ---------------------------------------------------------------------------
// StsEntry — the in-memory entry, mirroring `struct stsentry`
// ---------------------------------------------------------------------------

/// A single stored HSTS entry.
///
/// Mirrors curl's `struct stsentry`:
///
/// ```c
/// struct stsentry {
///   struct Curl_llist_node node;
///   curl_off_t expires;         /* the timestamp of this entry's expiry */
///   BIT(includeSubDomains);
///   char host[1];
/// };
/// ```
///
/// The C flexible-array `host` becomes an owned [`String`]; the intrusive
/// linked-list `node` is unnecessary because the [`Hsts`] store owns entries in
/// insertion order. The `curl_off_t expires` becomes an [`Option<i64>`] Unix
/// timestamp where [`None`] is curl's `TIME_T_MAX` "unlimited" sentinel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StsEntry {
    /// Stored host, always without a leading or trailing dot.
    host: String,
    /// Whether the policy extends to sub-domains of [`host`](StsEntry::host).
    include_subdomains: bool,
    /// Expiry as a Unix timestamp (seconds, UTC). [`None`] means the entry
    /// never expires (curl's `TIME_T_MAX`); `Some(0)` is an already-expired
    /// entry, matching curl leaving `expires == 0` on an unparseable date.
    expires: Option<i64>,
}

impl StsEntry {
    /// The stored host name (never carries a leading or trailing dot).
    #[must_use]
    pub fn host(&self) -> &str {
        &self.host
    }

    /// Whether this policy extends to sub-domains of [`host`](StsEntry::host).
    #[must_use]
    pub fn include_subdomains(&self) -> bool {
        self.include_subdomains
    }

    /// The expiry timestamp, or [`None`] for an entry that never expires.
    #[must_use]
    pub fn expires(&self) -> Option<i64> {
        self.expires
    }

    /// Returns `true` when this entry is expired relative to `now` (a Unix
    /// timestamp). An unlimited entry ([`None`]) is never expired.
    ///
    /// Mirrors curl's `sts->expires <= now` test (with `TIME_T_MAX` — here
    /// [`None`] — never satisfying it).
    #[must_use]
    fn is_expired(&self, now: i64) -> bool {
        match self.expires {
            None => false,
            Some(ts) => ts <= now,
        }
    }
}

// ---------------------------------------------------------------------------
// Hsts — the cache, mirroring `struct hsts`
// ---------------------------------------------------------------------------

/// The HSTS cache.
///
/// Mirrors curl's `struct hsts`:
///
/// ```c
/// struct hsts {
///   struct Curl_llist list;
///   char *filename;
///   unsigned int flags;
/// };
/// ```
///
/// The intrusive list becomes a [`Vec<StsEntry>`] that preserves insertion
/// order — this is what makes the saved file byte-identical to curl's, since
/// curl appends new entries at the list tail and writes them in list order.
/// `filename` is retained so that a later [`save`](Hsts::save) with no explicit
/// path reuses the path the cache was loaded from (matching curl's behavior of
/// keeping the name so it "survives an easy handle reset"). `flags` carries the
/// `CURLHSTS_*` bits.
#[derive(Debug, Clone, Default)]
pub struct Hsts {
    /// Entries in insertion order (curl's `Curl_llist`).
    entries: Vec<StsEntry>,
    /// The cache file path remembered from a load, reused by `save(None)`.
    filename: Option<String>,
    /// `CURLHSTS_*` flag bits (notably [`CURLHSTS_READONLYFILE`]).
    flags: u32,
}

impl Hsts {
    /// Creates an empty HSTS cache.
    ///
    /// Mirrors `Curl_hsts_init`.
    #[must_use]
    pub fn new() -> Self {
        Hsts {
            entries: Vec::new(),
            filename: None,
            flags: 0,
        }
    }

    /// Returns the current `CURLHSTS_*` flag bits.
    #[must_use]
    pub fn flags(&self) -> u32 {
        self.flags
    }

    /// Replaces the `CURLHSTS_*` flag bits wholesale.
    pub fn set_flags(&mut self, flags: u32) {
        self.flags = flags;
    }

    /// Sets or clears the [`CURLHSTS_READONLYFILE`] bit.
    ///
    /// When set, [`save`](Hsts::save) never touches the backing file (the
    /// callback path still runs), matching curl's `CURLHSTS_READONLYFILE`
    /// handling in `Curl_hsts_save`.
    pub fn set_readonly(&mut self, readonly: bool) {
        if readonly {
            self.flags |= CURLHSTS_READONLYFILE;
        } else {
            self.flags &= !CURLHSTS_READONLYFILE;
        }
    }

    /// Returns the remembered cache-file path, if any.
    #[must_use]
    pub fn filename(&self) -> Option<&str> {
        self.filename.as_deref()
    }

    /// Returns the number of entries currently stored (curl's
    /// `Curl_llist_count`).
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Returns `true` when the cache holds no entries.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Read-only view of the stored entries, in insertion order.
    ///
    /// Primarily useful for the FFI layer and for tests; ordinary transfers use
    /// [`is_hsts`](Hsts::is_hsts).
    #[must_use]
    pub fn entries(&self) -> &[StsEntry] {
        &self.entries
    }
}

// ---------------------------------------------------------------------------
// Time source — parity with curl's hsts_debugtime()
// ---------------------------------------------------------------------------

/// Returns the current wall-clock time as a Unix timestamp (seconds, UTC).
///
/// A pre-1970 clock (which cannot happen in practice) clamps to `0`.
fn system_now() -> i64 {
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(d) => d.as_secs() as i64,
        Err(_) => 0,
    }
}

/// The "current time" used by the public entry points.
///
/// In debug and test builds this honors the `CURL_TIME` environment variable,
/// exactly mirroring curl's `hsts_debugtime()` which is compiled under
/// `#if defined(DEBUGBUILD) || defined(UNITTESTS)`. This lets the curl test
/// corpus (and this module's own tests) pin "now" for deterministic expiry
/// behavior. Release builds always use the real clock, matching curl's release
/// behavior.
#[cfg(any(test, debug_assertions))]
fn hsts_now() -> i64 {
    if let Ok(timestr) = std::env::var("CURL_TIME") {
        if let Ok(val) = timestr.trim().parse::<i64>() {
            return val;
        }
    }
    system_now()
}

/// The "current time" used by the public entry points (release builds).
#[cfg(not(any(test, debug_assertions)))]
fn hsts_now() -> i64 {
    system_now()
}

// ---------------------------------------------------------------------------
// Date helpers — chrono-backed, byte-for-byte with curl's gmtime formatting
// ---------------------------------------------------------------------------

/// Formats an expiry into the exact textual stamp curl writes.
///
/// [`None`] (unlimited) yields the [`UNLIMITED`] sentinel. `Some(ts)` yields
/// `YYYYMMDD HH:MM:SS` in UTC, reproducing curl's
/// `curl_msnprintf(…, "%d%02d%02d %02d:%02d:%02d", tm_year+1900, tm_mon+1, …)`:
/// the year is emitted with no zero-padding (`%d`) and the remaining fields are
/// two-digit zero-padded (`%02d`).
///
/// Returns [`Error::with_context`] with [`CurlCode::BadFunctionArgument`] if
/// the timestamp is outside the representable calendar range (curl's
/// `curlx_gmtime` failure), which cannot occur for real HSTS expiries.
fn format_expiry(expires: Option<i64>) -> Result<String> {
    match expires {
        None => Ok(UNLIMITED.to_string()),
        Some(ts) => {
            let dt: DateTime<Utc> = DateTime::<Utc>::from_timestamp(ts, 0).ok_or_else(|| {
                Error::with_context(
                    crate::error::CurlCode::BadFunctionArgument,
                    "HSTS expiry timestamp out of range",
                )
            })?;
            Ok(format!(
                "{}{:02}{:02} {:02}:{:02}:{:02}",
                dt.year(),
                dt.month(),
                dt.day(),
                dt.hour(),
                dt.minute(),
                dt.second()
            ))
        }
    }
}

/// Parses the `YYYYMMDD HH:MM:SS` stamp curl writes into a Unix timestamp.
///
/// This is the chrono-backed equivalent of the path curl's
/// `Curl_getdate_capped` takes for the fixed stamp its own writer emits (and
/// which the callback `expire` field is documented to use). The eight-digit
/// date is split as `year = [0..4]`, `month = [4..6]`, `day = [6..8]`, exactly
/// mirroring `parsedate.c`'s `val/10000`, `(val%10000)/100`, `val%100`
/// decomposition of a `YYYYMMDD` token. A missing time component defaults to
/// `00:00:00`, as curl's parser zeroes an absent time.
///
/// Returns [`None`] for any input that does not match the expected shape or
/// denotes an invalid calendar instant; callers treat that as curl does when
/// `getdate` fails — an `expires` of `0` (an already-expired entry).
fn parse_general_date(s: &str) -> Option<i64> {
    let s = s.trim();
    let (date_part, time_part) = match s.split_once(' ') {
        Some((d, t)) => (d, t.trim_start()),
        None => (s, ""),
    };

    // The date must be exactly eight ASCII digits: YYYYMMDD.
    if date_part.len() != 8 || !date_part.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    let year: i32 = date_part[0..4].parse().ok()?;
    let month: u32 = date_part[4..6].parse().ok()?;
    let day: u32 = date_part[6..8].parse().ok()?;

    // Time is HH:MM:SS; an absent field defaults to zero (as curl does).
    let (hour, minute, second) = parse_hms(time_part)?;

    let date = NaiveDate::from_ymd_opt(year, month, day)?;
    let time = NaiveTime::from_hms_opt(hour, minute, second)?;
    Some(NaiveDateTime::new(date, time).and_utc().timestamp())
}

/// Parses an `HH:MM:SS` (or shorter, colon-separated) time.
///
/// Missing trailing components default to `0`, mirroring curl's
/// `if(-1 == secnum) secnum = minnum = hournum = 0;`. An empty string is a
/// valid `00:00:00`. Any non-numeric component fails the parse.
fn parse_hms(time_part: &str) -> Option<(u32, u32, u32)> {
    if time_part.is_empty() {
        return Some((0, 0, 0));
    }
    let mut it = time_part.split(':');
    let hour = parse_time_field(it.next())?;
    let minute = parse_time_field(it.next())?;
    let second = parse_time_field(it.next())?;
    // Reject trailing garbage such as "00:00:00:00".
    if it.next().is_some() {
        return None;
    }
    Some((hour, minute, second))
}

/// Parses one optional colon-separated time field; an absent field is `0`.
fn parse_time_field(field: Option<&str>) -> Option<u32> {
    match field {
        None => Some(0),
        Some(f) => f.parse::<u32>().ok(),
    }
}

/// Returns `true` when `host` is a numeric IP literal (IPv4 or IPv6).
///
/// Mirrors curl's `Curl_host_is_ipnum`, which RFC 6797 §8.3 uses to exclude
/// IP-address hosts from HSTS entirely ("explicit IP address identification of
/// all forms is excluded").
fn is_ip_address(host: &str) -> bool {
    host.parse::<std::net::Ipv4Addr>().is_ok() || host.parse::<std::net::Ipv6Addr>().is_ok()
}

// ---------------------------------------------------------------------------
// Core matching, insertion and removal — mirroring Curl_hsts / hsts_create
// ---------------------------------------------------------------------------

impl Hsts {
    /// Finds the best matching, non-expired entry for `host`.
    ///
    /// This is the read-only heart of curl's `Curl_hsts`. It:
    ///
    /// * returns [`None`] immediately if the query length is `0` or exceeds
    ///   [`MAX_HSTS_HOSTLEN`];
    /// * strips a single trailing `.` from the query name;
    /// * ignores expired entries (unlike `Curl_hsts` it does **not** remove
    ///   them here — removal happens in the `&mut` paths via
    ///   [`find_and_prune`](Hsts::find_and_prune) — because this borrows
    ///   `&self`);
    /// * returns an exact (ASCII case-insensitive) host match as soon as it is
    ///   seen; and
    /// * otherwise, when `subdomain` is set, returns the entry with the
    ///   *longest* `includeSubDomains` tail match, applying curl's
    ///   `ntail < hlen`, preceding-dot, and case-insensitive-tail rule.
    ///
    /// The returned value is an index into [`entries`](Hsts::entries).
    fn find(&self, host: &str, subdomain: bool, now: i64) -> Option<usize> {
        let bytes = host.as_bytes();
        let mut hlen = bytes.len();

        if hlen > MAX_HSTS_HOSTLEN || hlen == 0 {
            return None;
        }
        // Remove a single trailing dot from the query name.
        if bytes[hlen - 1] == b'.' {
            hlen -= 1;
        }
        if hlen == 0 {
            // The query was just "."; nothing can match.
            return None;
        }
        let query = &bytes[..hlen];

        let mut best: Option<usize> = None;
        let mut best_len = 0usize;

        for (idx, sts) in self.entries.iter().enumerate() {
            if sts.is_expired(now) {
                continue;
            }
            let ehost = sts.host.as_bytes();
            let ntail = ehost.len();

            if subdomain && sts.include_subdomains && ntail < hlen {
                let offs = hlen - ntail;
                // The byte before the tail must be a dot, the tail must match
                // case-insensitively, and we keep only the longest such tail.
                if query[offs - 1] == b'.'
                    && query[offs..].eq_ignore_ascii_case(ehost)
                    && ntail > best_len
                {
                    best = Some(idx);
                    best_len = ntail;
                }
            }

            // Exact match wins outright (curl returns it immediately).
            if hlen == ntail && query.eq_ignore_ascii_case(ehost) {
                return Some(idx);
            }
        }

        best
    }

    /// Removes every expired entry relative to `now`.
    ///
    /// Preserves the relative order of the surviving entries, matching curl's
    /// in-place list removal (and keeping the saved-file byte order stable).
    fn prune_expired(&mut self, now: i64) {
        self.entries.retain(|e| !e.is_expired(now));
    }

    /// Prunes expired entries, then finds the best match — the full `&mut`
    /// equivalent of `Curl_hsts` (which removes expired entries as it scans).
    ///
    /// Because expired entries never match, pruning first and then running the
    /// read-only [`find`](Hsts::find) yields exactly the same match `Curl_hsts`
    /// would return from its single removing pass.
    fn find_and_prune(&mut self, host: &str, subdomain: bool, now: i64) -> Option<usize> {
        self.prune_expired(now);
        self.find(host, subdomain, now)
    }

    /// Appends a new entry (curl's `hsts_create`).
    ///
    /// A single trailing dot is stripped from `host`; if nothing remains the
    /// entry is silently dropped (`if(hlen)` in the C source). No leading-dot
    /// handling happens here — callers strip a leading `.` and set `subdomains`
    /// before calling, exactly as `hsts_add` does. Entries are appended at the
    /// tail so insertion order (and therefore saved-file order) is preserved.
    fn create(&mut self, host: &str, subdomains: bool, expires: Option<i64>) {
        let bytes = host.as_bytes();
        let mut hlen = host.len();
        if hlen > 0 && bytes[hlen - 1] == b'.' {
            hlen -= 1;
        }
        if hlen > 0 {
            // `host[..hlen]` is a valid boundary: we only trimmed a trailing
            // ASCII '.', and the input is already valid UTF-8.
            self.entries.push(StsEntry {
                host: host[..hlen].to_string(),
                include_subdomains: subdomains,
                expires,
            });
        }
    }

    /// Removes the entry that exactly matches `host` (no sub-domain matching).
    ///
    /// Mirrors the `max-age=0` branch of `Curl_hsts_parse`, which looks the
    /// host up with `subdomain = FALSE` and removes it if present.
    fn remove_exact(&mut self, host: &str, now: i64) {
        if let Some(idx) = self.find_and_prune(host, false, now) {
            self.entries.remove(idx);
        }
    }

    /// Returns `true` when `host` is currently a known-HSTS host and must be
    /// upgraded from `http://` to `https://`.
    ///
    /// This is the public form of curl's `Curl_hsts(h, host, len, TRUE)` call
    /// (the sub-domain-aware lookup performed at `lib/url.c`). Expired entries
    /// are ignored; IP-address hosts simply never match any stored name.
    #[must_use]
    pub fn is_hsts(&self, host: &str) -> bool {
        self.is_hsts_at(host, hsts_now())
    }

    /// [`is_hsts`](Hsts::is_hsts) with an explicit "now", for deterministic
    /// testing and for callers that already hold a timestamp.
    #[must_use]
    fn is_hsts_at(&self, host: &str, now: i64) -> bool {
        self.find(host, true, now).is_some()
    }

    /// Returns the best matching, non-expired entry for `host`, if any.
    ///
    /// Sub-domain matching is enabled, matching the upgrade-decision lookup.
    /// This mirrors `Curl_hsts` returning the matched `struct stsentry`.
    #[must_use]
    pub fn lookup(&self, host: &str) -> Option<&StsEntry> {
        self.find(host, true, hsts_now())
            .map(|idx| &self.entries[idx])
    }
}

// ---------------------------------------------------------------------------
// Header-directive parsing helpers — mirroring curlx_str_* primitives
// ---------------------------------------------------------------------------

/// Returns `true` for curl's `ISBLANK`: an ASCII space or horizontal tab.
fn is_blank(b: u8) -> bool {
    b == b' ' || b == b'\t'
}

/// Case-insensitive ASCII prefix test, equivalent to
/// `curl_strnequal(needle, haystack, needle.len())`.
fn eq_ci_prefix(haystack: &[u8], needle: &[u8]) -> bool {
    haystack.len() >= needle.len() && haystack[..needle.len()].eq_ignore_ascii_case(needle)
}

/// Result of [`parse_u_number`], mirroring the relevant `STRE_*` codes.
enum NumParse {
    /// A value was parsed successfully.
    Ok(i64),
    /// The value overflowed the supplied maximum (`STRE_OVERFLOW`).
    Overflow,
    /// The first byte was not a digit (`STRE_NO_NUM`).
    NoNum,
}

/// Parses an unsigned decimal number at `bytes[*pos..]`.
///
/// Faithful port of curl's `curlx_str_number` / `str_num_base(base = 10)` for
/// the `max >= base` path used here (`max == i64::MAX`):
///
/// * On success, advances `*pos` past the digits and returns [`NumParse::Ok`].
/// * On overflow past `max`, returns [`NumParse::Overflow`] and leaves `*pos`
///   **unchanged** — `str_num_base` only writes `*linep` on success, so the
///   caller's cursor stays at the number's start. Reproducing this exactly is
///   what makes a `max-age="<overflow>"` header correctly fail on its missing
///   closing quote, just as curl does.
/// * If the first byte is not a digit, returns [`NumParse::NoNum`] without
///   advancing.
fn parse_u_number(bytes: &[u8], pos: &mut usize, max: i64) -> NumParse {
    let start = *pos;
    if start >= bytes.len() || !bytes[start].is_ascii_digit() {
        return NumParse::NoNum;
    }
    let mut num: i64 = 0;
    let mut i = start;
    while i < bytes.len() && bytes[i].is_ascii_digit() {
        let n = i64::from(bytes[i] - b'0');
        // Overflow check identical to str_num_base's `num > (max - n) / base`.
        if num > (max - n) / 10 {
            return NumParse::Overflow;
        }
        num = num * 10 + n;
        i += 1;
    }
    *pos = i;
    NumParse::Ok(num)
}

// ---------------------------------------------------------------------------
// Header ingestion — mirroring Curl_hsts_parse
// ---------------------------------------------------------------------------

impl Hsts {
    /// Ingests a `Strict-Transport-Security` response header for `hostname`.
    ///
    /// Mirrors `Curl_hsts_parse`. `hostname` is the host the response came
    /// from; `header` is the raw header value (without the field name). See the
    /// module docs for the directive grammar. Returns [`Error::bad_argument`]
    /// (curl's `CURLE_BAD_FUNCTION_ARGUMENT`) for a malformed header, mirroring
    /// curl's error returns.
    pub fn parse(&mut self, hostname: &str, header: &str) -> Result<()> {
        self.parse_at(hostname, header, hsts_now())
    }

    /// [`parse`](Hsts::parse) with an explicit "now", for deterministic tests.
    fn parse_at(&mut self, hostname: &str, header: &str, now: i64) -> Result<()> {
        // RFC 6797 §8.3: IP-address hosts are excluded entirely.
        if is_ip_address(hostname) {
            return Ok(());
        }

        let bytes = header.as_bytes();
        let len = bytes.len();
        let mut p = 0usize;

        let mut expires: i64 = 0;
        let mut got_maxage = false;
        let mut got_include = false;
        let mut subdomains = false;

        // C is a `do { … } while(*p);` loop: the body always runs once, and
        // continues while unconsumed bytes remain.
        loop {
            // curlx_str_passblanks
            while p < len && is_blank(bytes[p]) {
                p += 1;
            }

            if eq_ci_prefix(&bytes[p..], b"max-age") {
                if got_maxage {
                    return Err(Error::bad_argument("duplicate HSTS max-age directive"));
                }
                p += 7;
                while p < len && is_blank(bytes[p]) {
                    p += 1;
                }
                // require '='
                if !(p < len && bytes[p] == b'=') {
                    return Err(Error::bad_argument("HSTS max-age missing '='"));
                }
                p += 1;
                while p < len && is_blank(bytes[p]) {
                    p += 1;
                }
                // optional opening quote
                let quoted = p < len && bytes[p] == b'"';
                if quoted {
                    p += 1;
                }
                match parse_u_number(bytes, &mut p, i64::MAX) {
                    NumParse::Overflow => {
                        // Saturate to the unlimited sentinel; deliberately do
                        // NOT advance `p`, exactly as str_num_base does not.
                        expires = i64::MAX;
                    }
                    NumParse::Ok(v) => expires = v,
                    NumParse::NoNum => {
                        return Err(Error::bad_argument("HSTS max-age is not a number"));
                    }
                }
                if quoted {
                    if !(p < len && bytes[p] == b'"') {
                        return Err(Error::bad_argument("HSTS max-age missing closing quote"));
                    }
                    p += 1;
                }
                got_maxage = true;
            } else if eq_ci_prefix(&bytes[p..], b"includesubdomains") {
                if got_include {
                    return Err(Error::bad_argument("duplicate HSTS includeSubDomains"));
                }
                subdomains = true;
                p += 17;
                got_include = true;
            } else {
                // Unknown directive: a lame attempt to skip to the next ';'.
                while p < len && bytes[p] != b';' {
                    p += 1;
                }
            }

            // curlx_str_passblanks; then consume a single ';' separator.
            while p < len && is_blank(bytes[p]) {
                p += 1;
            }
            if p < len && bytes[p] == b';' {
                p += 1;
            }

            if p >= len {
                break;
            }
        }

        if !got_maxage {
            // max-age is mandatory.
            return Err(Error::bad_argument("HSTS header lacks mandatory max-age"));
        }

        if expires == 0 {
            // max-age=0 removes an existing entry (verbatim, no sub-domain).
            self.remove_exact(hostname, now);
            return Ok(());
        }

        // Absolute expiry = now + max-age, saturating to the unlimited
        // sentinel (curl caps at CURL_OFF_T_MAX, which equals the TIME_T_MAX
        // sentinel this module represents as `None`).
        let abs = match now.checked_add(expires) {
            Some(v) if v < i64::MAX => Some(v),
            _ => None,
        };

        // Update an existing exact entry, otherwise create a fresh one.
        if let Some(idx) = self.find_and_prune(hostname, false, now) {
            self.entries[idx].expires = abs;
            self.entries[idx].include_subdomains = subdomains;
        } else {
            self.create(hostname, subdomains, abs);
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// File serialization helpers — mirroring hsts_out and Curl_fopen atomicity
// ---------------------------------------------------------------------------

/// Renders a single entry into its exact on-disk line (mirroring `hsts_out`).
///
/// The line is `"%s%s \"%s\"\n"`: an optional leading `.` for
/// `includeSubDomains`, the host, a space, and the double-quoted expiry stamp.
fn entry_line(sts: &StsEntry) -> Result<String> {
    let dot = if sts.include_subdomains { "." } else { "" };
    let date = format_expiry(sts.expires)?;
    Ok(format!("{}{} \"{}\"\n", dot, sts.host, date))
}

/// Writes `contents` to `target` atomically: it writes a sibling temporary
/// file in the same directory, then renames it over the destination.
///
/// This reproduces curl's `Curl_fopen` behavior (write to a temp store, then
/// `rename`), so a crash mid-write never corrupts an existing cache. Any I/O
/// failure maps to [`Error::Write`] (curl's `CURLE_WRITE_ERROR`), and the
/// temporary file is removed on a failed rename (curl `unlink`s it).
fn write_atomic(target: &str, contents: &str) -> Result<()> {
    use std::io::Write;

    let path = std::path::Path::new(target);
    let file_name = path.file_name().ok_or(Error::Write)?;

    // Build a unique sibling temp name: ".<name>.tmp.<pid>.<nanos>".
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    let mut tmp_name = std::ffi::OsString::from(".");
    tmp_name.push(file_name);
    tmp_name.push(format!(".tmp.{}.{}", std::process::id(), nanos));
    let tmp_path = match path.parent().filter(|p| !p.as_os_str().is_empty()) {
        Some(dir) => dir.join(&tmp_name),
        None => std::path::PathBuf::from(&tmp_name),
    };

    // Write the full contents to the temporary file first.
    let write_result = (|| -> std::io::Result<()> {
        let mut f = std::fs::File::create(&tmp_path)?;
        f.write_all(contents.as_bytes())?;
        f.flush()?;
        Ok(())
    })();
    if write_result.is_err() {
        let _ = std::fs::remove_file(&tmp_path);
        return Err(Error::Write);
    }

    // Atomically move it into place.
    if std::fs::rename(&tmp_path, path).is_err() {
        let _ = std::fs::remove_file(&tmp_path);
        return Err(Error::Write);
    }
    Ok(())
}

/// Returns the later of two expiries, treating [`None`] (unlimited) as the
/// maximum. Mirrors curl's `if(expires > e->expires) e->expires = expires;`
/// where the `TIME_T_MAX` sentinel is the largest possible value.
fn max_expiry(a: Option<i64>, b: Option<i64>) -> Option<i64> {
    match (a, b) {
        (None, _) | (_, None) => None,
        (Some(x), Some(y)) => Some(x.max(y)),
    }
}

/// Parses one on-disk cache line into `(host, date_field)`.
///
/// Mirrors the `str_word` / `str_singlespace` / `str_quotedword` /
/// `str_newline` sequence at the top of `hsts_add`. `line` is expected to have
/// had its trailing newline stripped by the caller, so curl's mandatory
/// trailing-newline check becomes "nothing (bar an optional CR) follows the
/// closing quote". Returns [`None`] for any line that does not match — curl
/// silently skips such lines.
fn parse_line(line: &str) -> Option<(&str, String)> {
    let bytes = line.as_bytes();
    let len = bytes.len();
    let mut p = 0usize;

    // curlx_str_word(max = MAX_HSTS_HOSTLEN): read up to the first space.
    while p < len && bytes[p] != b' ' {
        p += 1;
    }
    let host_len = p;
    if host_len == 0 || host_len > MAX_HSTS_HOSTLEN {
        // STRE_SHORT (empty) or STRE_BIG (too long).
        return None;
    }
    let host = &line[..host_len];

    // curlx_str_singlespace: exactly one space must follow.
    if !(p < len && bytes[p] == b' ') {
        return None;
    }
    p += 1;

    // curlx_str_quotedword(max = MAX_HSTS_DATELEN).
    let (date, next) = parse_quoted_word(bytes, p, MAX_HSTS_DATELEN)?;
    p = next;

    // curlx_str_newline: only a newline may follow. Reading stripped lines,
    // that means end-of-line here (an optional lone trailing CR is tolerated,
    // matching curl accepting CR as a newline byte).
    if p != len && !(p + 1 == len && bytes[p] == b'\r') {
        return None;
    }

    Some((host, date))
}

/// Extracts a double-quoted word starting at `start`, mirroring
/// `curlx_str_quotedword`.
///
/// Requires an opening `"`; consumes bytes until the closing `"`, treating a
/// backslash followed by any further byte as a two-byte escape (the raw bytes,
/// backslashes included, form the returned content — curl does not unescape).
/// Enforces `max` on the content length. Returns the content and the index just
/// past the closing quote, or [`None`] on any of curl's `STRE_BEGQUOTE` /
/// `STRE_ENDQUOTE` / `STRE_BIG` conditions.
fn parse_quoted_word(bytes: &[u8], start: usize, max: usize) -> Option<(String, usize)> {
    let len = bytes.len();
    let mut s = start;

    if !(s < len && bytes[s] == b'"') {
        return None; // STRE_BEGQUOTE
    }
    s += 1;
    let content_start = s;
    let mut count = 0usize;
    while s < len && bytes[s] != b'"' {
        if bytes[s] == b'\\' && s + 1 < len {
            s += 1;
            count += 1;
            if count > max {
                return None; // STRE_BIG
            }
        }
        s += 1;
        count += 1;
        if count > max {
            return None; // STRE_BIG
        }
    }
    if !(s < len && bytes[s] == b'"') {
        return None; // STRE_ENDQUOTE
    }
    let content = String::from_utf8_lossy(&bytes[content_start..s]).into_owned();
    Some((content, s + 1))
}

// ---------------------------------------------------------------------------
// Persistence — mirroring Curl_hsts_save / hsts_add / hsts_load / hsts_pull
// ---------------------------------------------------------------------------

impl Hsts {
    /// Serializes the whole cache to the exact byte string curl writes.
    ///
    /// Produces the two comment header lines followed by one line per entry in
    /// insertion order. This is the single source of truth for the on-disk
    /// bytes and is what makes the file byte-identical to curl 8.x output for
    /// the same entries. Every entry currently stored is written (curl does not
    /// prune during save).
    pub fn to_file_string(&self) -> Result<String> {
        let mut out = String::with_capacity(FILE_HEADER.len() + self.entries.len() * 40);
        out.push_str(FILE_HEADER);
        for sts in &self.entries {
            out.push_str(&entry_line(sts)?);
        }
        Ok(out)
    }

    /// Writes the cache to a file (the file half of `Curl_hsts_save`).
    ///
    /// If `file` is [`None`], the path remembered from a previous load is used.
    /// The write is skipped entirely (returning `Ok`) when the
    /// [`CURLHSTS_READONLYFILE`] flag is set, when no path is available, or when
    /// the path is empty — matching curl's `goto skipsave`. The callback half
    /// is exposed separately as [`save_to_callback`](Hsts::save_to_callback);
    /// the FFI layer calls both to fully reproduce `Curl_hsts_save`.
    pub fn save(&self, file: Option<&str>) -> Result<()> {
        let target = match file.or(self.filename.as_deref()) {
            Some(f) => f,
            None => return Ok(()), // no file: nothing to write
        };
        if (self.flags & CURLHSTS_READONLYFILE) != 0 || target.is_empty() {
            return Ok(());
        }
        let contents = self.to_file_string()?;
        write_atomic(target, &contents)
    }

    /// Streams every entry to a write callback (the callback half of
    /// `Curl_hsts_save`, i.e. the `hsts_push` loop).
    ///
    /// The callback receives each [`HstsEntry`] with its zero-based `index` and
    /// the `total` count. A [`HstsCode::Ok`] return continues iteration,
    /// [`HstsCode::Done`] stops it without error, and [`HstsCode::Fail`] aborts
    /// with [`Error::bad_argument`] (curl's `CURLE_BAD_FUNCTION_ARGUMENT`).
    pub fn save_to_callback(
        &self,
        cb: &mut dyn FnMut(&HstsEntry, usize, usize) -> HstsCode,
    ) -> Result<()> {
        let total = self.entries.len();
        for (index, sts) in self.entries.iter().enumerate() {
            let entry = HstsEntry {
                name: sts.host.clone(),
                include_subdomains: sts.include_subdomains,
                expire: format_expiry(sts.expires)?,
            };
            match cb(&entry, index, total) {
                HstsCode::Ok => {}
                HstsCode::Done => break,
                HstsCode::Fail => return Err(Error::bad_argument("HSTS write callback failed")),
            }
        }
        Ok(())
    }

    /// Adds a single already-newline-stripped file line to the cache.
    ///
    /// Mirrors `hsts_add`: it parses the line, derives the expiry (the
    /// [`UNLIMITED`] sentinel, an unparseable date as `0`, or a real stamp),
    /// strips a leading `.` into the sub-domain flag, then either creates a new
    /// entry or, when an entry for the *same* host already exists, keeps the
    /// later expiry. A line that does not parse is silently ignored.
    fn add_line(&mut self, line: &str, now: i64) {
        let (host, date) = match parse_line(line) {
            Some(hd) => hd,
            None => return,
        };

        let expires: Option<i64> = if date == UNLIMITED {
            None
        } else {
            Some(parse_general_date(&date).unwrap_or(0))
        };

        let (host, subdomain) = match host.strip_prefix('.') {
            Some(stripped) => (stripped, true),
            None => (host, false),
        };

        match self.find_and_prune(host, subdomain, now) {
            None => self.create(host, subdomain, expires),
            Some(idx) => {
                // Update only when it is genuinely the same host (curl's
                // curlx_str_casecompare); a sub-domain match on a different
                // stored host is left untouched.
                if self.entries[idx].host.eq_ignore_ascii_case(host) {
                    self.entries[idx].expires = max_expiry(self.entries[idx].expires, expires);
                }
            }
        }
    }

    /// Loads entries from the textual cache format held in `contents`.
    ///
    /// Mirrors the read loop of `hsts_load`: leading blanks are skipped, comment
    /// (`#`) and empty lines are ignored, and every other line is handed to the
    /// line parser. A single line whose length reaches [`MAX_HSTS_LINE`] aborts
    /// the load with [`Error::TooLarge`] (curl's `CURLE_TOO_LARGE` from the
    /// line-reading dynamic buffer); entries parsed before it are retained.
    pub fn load_str(&mut self, contents: &str) -> Result<()> {
        self.load_str_at(contents, hsts_now())
    }

    /// [`load_str`](Hsts::load_str) with an explicit "now", for deterministic
    /// tests.
    fn load_str_at(&mut self, contents: &str, now: i64) -> Result<()> {
        for raw_line in contents.split('\n') {
            // curl reads whole lines *including* the terminating newline and a
            // trailing NUL; a line that would overflow the MAX_HSTS_LINE line
            // buffer is a hard CURLE_TOO_LARGE error.
            if raw_line.len() + 1 >= MAX_HSTS_LINE {
                return Err(Error::TooLarge);
            }
            // curlx_str_passblanks over the leading spaces/tabs.
            let line = raw_line.trim_start_matches([' ', '\t']);
            // Skip comment lines and blank/empty lines (curl: '#' or len <= 1).
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            self.add_line(line, now);
        }
        Ok(())
    }

    /// Loads the HSTS cache from a file (mirrors `Curl_hsts_loadfile`).
    ///
    /// The path is remembered so a later [`save`](Hsts::save) with no argument
    /// reuses it. A missing or unreadable file is not an error (curl's `fopen`
    /// simply returns `NULL` and `hsts_load` still returns `CURLE_OK`); only a
    /// malformed over-long line produces an error, propagated from
    /// [`load_str`](Hsts::load_str).
    pub fn load_file(&mut self, file: &str) -> Result<()> {
        self.load_file_at(file, hsts_now())
    }

    /// [`load_file`](Hsts::load_file) with an explicit "now", for tests.
    fn load_file_at(&mut self, file: &str, now: i64) -> Result<()> {
        // Remember the filename so it survives an easy-handle reset.
        self.filename = Some(file.to_string());
        match std::fs::read_to_string(file) {
            Ok(contents) => self.load_str_at(&contents, now),
            // A missing/unreadable file is silently tolerated, as in curl.
            Err(_) => Ok(()),
        }
    }

    /// Loads entries via an application read callback (mirrors
    /// `Curl_hsts_loadcb` / `hsts_pull`).
    ///
    /// The callback is invoked repeatedly; it fills the supplied [`HstsEntry`]
    /// and returns [`HstsCode::Ok`] to add it (an empty `name` is rejected with
    /// [`Error::bad_argument`]; an empty `expire` means "unlimited"),
    /// [`HstsCode::Done`] to finish, or [`HstsCode::Fail`] to abort with
    /// [`Error::AbortedByCallback`]. Entries arriving via the callback are not
    /// de-duplicated, exactly as curl calls `hsts_create` directly here.
    pub fn load_from_callback(
        &mut self,
        cb: &mut dyn FnMut(&mut HstsEntry) -> HstsCode,
    ) -> Result<()> {
        loop {
            let mut entry = HstsEntry::default();
            match cb(&mut entry) {
                HstsCode::Ok => {
                    if entry.name.is_empty() {
                        return Err(Error::bad_argument("HSTS read callback returned no name"));
                    }
                    let expires = if entry.expire.is_empty() {
                        None
                    } else {
                        Some(parse_general_date(&entry.expire).unwrap_or(0))
                    };
                    self.create(&entry.name, entry.include_subdomains, expires);
                }
                HstsCode::Fail => return Err(Error::AbortedByCallback),
                HstsCode::Done => break,
            }
        }
        Ok(())
    }

    /// Loads several cache files in order (mirrors `Curl_hsts_loadfiles`).
    ///
    /// Files are loaded left to right and loading stops at the first error.
    /// curl additionally takes a share lock (`CURL_LOCK_DATA_HSTS`) around this
    /// loop; that cross-handle synchronization is a concern of the owning
    /// share/multi layer, not of the cache itself, and so is not reproduced
    /// here.
    pub fn load_files(&mut self, files: &[impl AsRef<str>]) -> Result<()> {
        let now = hsts_now();
        for f in files {
            self.load_file_at(f.as_ref(), now)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A deterministic "now" (2001-09-09T01:46:40Z) used across the tests.
    const NOW: i64 = 1_000_000_000;

    /// The exact two-line comment header curl writes.
    const HEADER: &str = "# Your HSTS cache. https://curl.se/docs/hsts.html\n\
                          # This file was generated by libcurl! Edit at your own risk.\n";

    /// Builds the Unix timestamp for a UTC calendar instant via chrono.
    fn ts(year: i32, mon: u32, day: u32, h: u32, m: u32, s: u32) -> i64 {
        NaiveDate::from_ymd_opt(year, mon, day)
            .unwrap()
            .and_hms_opt(h, m, s)
            .unwrap()
            .and_utc()
            .timestamp()
    }

    // -- date helpers --------------------------------------------------------

    #[test]
    fn format_expiry_matches_curl_stamp() {
        // %d%02d%02d %02d:%02d:%02d in UTC.
        let t = ts(2037, 1, 1, 0, 0, 0);
        assert_eq!(format_expiry(Some(t)).unwrap(), "20370101 00:00:00");

        let t2 = ts(2019, 12, 31, 10, 0, 0);
        assert_eq!(format_expiry(Some(t2)).unwrap(), "20191231 10:00:00");

        // Zero-padding of every field except the year.
        let t3 = ts(2005, 3, 4, 5, 6, 7);
        assert_eq!(format_expiry(Some(t3)).unwrap(), "20050304 05:06:07");

        // Unlimited sentinel.
        assert_eq!(format_expiry(None).unwrap(), UNLIMITED);
    }

    #[test]
    fn parse_general_date_round_trips_format() {
        for (y, mo, d, h, mi, s) in [
            (2037, 1, 1, 0, 0, 0),
            (2019, 12, 31, 10, 0, 0),
            (1999, 6, 15, 23, 59, 59),
            (2005, 3, 4, 5, 6, 7),
        ] {
            let t = ts(y, mo, d, h, mi, s);
            let text = format_expiry(Some(t)).unwrap();
            assert_eq!(parse_general_date(&text), Some(t), "round-trip {text}");
        }
    }

    #[test]
    fn parse_general_date_rejects_garbage() {
        assert_eq!(parse_general_date(""), None);
        assert_eq!(parse_general_date("unlimited"), None); // handled elsewhere
        assert_eq!(parse_general_date("2037-01-01"), None); // wrong shape
        assert_eq!(parse_general_date("2037010 00:00:00"), None); // 7 digits
        assert_eq!(parse_general_date("2037010a 00:00:00"), None); // non-digit

        // A date with no time defaults the time to midnight.
        assert_eq!(
            parse_general_date("20370101"),
            Some(ts(2037, 1, 1, 0, 0, 0))
        );
    }

    #[test]
    fn ip_addresses_are_detected() {
        assert!(is_ip_address("192.168.0.1"));
        assert!(is_ip_address("::1"));
        assert!(is_ip_address("2001:db8::1"));
        assert!(!is_ip_address("example.com"));
        assert!(!is_ip_address("192.168.0.256"));
    }

    // -- matching (Curl_hsts) ------------------------------------------------

    fn store(entries: &[(&str, bool, Option<i64>)]) -> Hsts {
        let mut h = Hsts::new();
        for (host, sub, exp) in entries {
            h.entries.push(StsEntry {
                host: (*host).to_string(),
                include_subdomains: *sub,
                expires: *exp,
            });
        }
        h
    }

    #[test]
    fn is_hsts_exact_match() {
        let h = store(&[("example.com", false, None)]);
        assert!(h.is_hsts_at("example.com", NOW));
        assert!(h.is_hsts_at("EXAMPLE.COM", NOW)); // case-insensitive
        assert!(h.is_hsts_at("example.com.", NOW)); // trailing dot stripped
        assert!(!h.is_hsts_at("www.example.com", NOW)); // no subdomain flag
        assert!(!h.is_hsts_at("example.org", NOW));
    }

    #[test]
    fn is_hsts_subdomain_match() {
        let h = store(&[("example.com", true, None)]);
        assert!(h.is_hsts_at("example.com", NOW)); // exact still matches
        assert!(h.is_hsts_at("www.example.com", NOW)); // subdomain
        assert!(h.is_hsts_at("a.b.example.com", NOW)); // deeper subdomain

        // The label boundary (preceding dot) is mandatory.
        assert!(!h.is_hsts_at("notexample.com", NOW));
        assert!(!h.is_hsts_at("fooexample.com", NOW));
        // Different registrable domain.
        assert!(!h.is_hsts_at("example.org", NOW));
    }

    #[test]
    fn subdomain_match_requires_include_flag_and_shorter_tail() {
        // include=false ⇒ only exact matches, never subdomains.
        let h = store(&[("example.com", false, None)]);
        assert!(!h.is_hsts_at("www.example.com", NOW));

        // ntail < hlen is required: an equal-length "tail" is only an exact
        // match, and a longer stored host can never tail-match a shorter query.
        let h2 = store(&[("www.example.com", true, None)]);
        assert!(!h2.is_hsts_at("example.com", NOW));
    }

    #[test]
    fn lookup_returns_longest_tail_match() {
        let h = store(&[("com", true, None), ("example.com", true, None)]);
        // Both ".com" and ".example.com" tail-match; the longest wins.
        let m = h.lookup("www.example.com").expect("a match");
        assert_eq!(m.host(), "example.com");
    }

    #[test]
    fn expired_entries_are_ignored() {
        let h = store(&[("example.com", true, Some(NOW - 1))]);
        assert!(!h.is_hsts_at("example.com", NOW));
        assert!(!h.is_hsts_at("www.example.com", NOW));

        // Exactly-now counts as expired (curl's `expires <= now`).
        let h2 = store(&[("example.com", false, Some(NOW))]);
        assert!(!h2.is_hsts_at("example.com", NOW));

        // One second in the future is still valid.
        let h3 = store(&[("example.com", false, Some(NOW + 1))]);
        assert!(h3.is_hsts_at("example.com", NOW));

        // Unlimited never expires.
        let h4 = store(&[("example.com", false, None)]);
        assert!(h4.is_hsts_at("example.com", NOW));
    }

    #[test]
    fn oversized_or_empty_host_never_matches() {
        let h = store(&[("example.com", true, None)]);
        assert!(!h.is_hsts_at("", NOW));
        assert!(!h.is_hsts_at(".", NOW));
        let long = "a".repeat(MAX_HSTS_HOSTLEN + 1);
        assert!(!h.is_hsts_at(&long, NOW));
    }

    // -- header parsing (Curl_hsts_parse) ------------------------------------

    #[test]
    fn parse_creates_entry_with_absolute_expiry() {
        let mut h = Hsts::new();
        h.parse_at("example.com", "max-age=1000", NOW).unwrap();
        assert_eq!(h.len(), 1);
        let e = &h.entries()[0];
        assert_eq!(e.host(), "example.com");
        assert!(!e.include_subdomains());
        assert_eq!(e.expires(), Some(NOW + 1000));
    }

    #[test]
    fn parse_handles_include_subdomains_and_ignores_preload() {
        let mut h = Hsts::new();
        h.parse_at(
            "example.com",
            "max-age=1000; includeSubDomains; preload",
            NOW,
        )
        .unwrap();
        assert_eq!(h.len(), 1);
        assert!(h.entries()[0].include_subdomains());
        assert!(h.is_hsts_at("sub.example.com", NOW));
    }

    #[test]
    fn parse_accepts_quoted_max_age_and_case_insensitive_directives() {
        let mut h = Hsts::new();
        h.parse_at("example.com", "MAX-AGE=\"1000\"; INCLUDESUBDOMAINS", NOW)
            .unwrap();
        assert_eq!(h.entries()[0].expires(), Some(NOW + 1000));
        assert!(h.entries()[0].include_subdomains());
    }

    #[test]
    fn parse_skips_unknown_directives() {
        let mut h = Hsts::new();
        h.parse_at("example.com", "foo=bar; max-age=1000; baz", NOW)
            .unwrap();
        assert_eq!(h.entries()[0].expires(), Some(NOW + 1000));
    }

    #[test]
    fn parse_updates_existing_entry() {
        let mut h = Hsts::new();
        h.parse_at("example.com", "max-age=1000", NOW).unwrap();
        h.parse_at("example.com", "max-age=2000; includeSubDomains", NOW)
            .unwrap();
        assert_eq!(h.len(), 1); // updated in place, not duplicated
        assert_eq!(h.entries()[0].expires(), Some(NOW + 2000));
        assert!(h.entries()[0].include_subdomains());
    }

    #[test]
    fn parse_max_age_zero_deletes_entry() {
        let mut h = Hsts::new();
        h.parse_at("example.com", "max-age=1000", NOW).unwrap();
        assert_eq!(h.len(), 1);
        h.parse_at("example.com", "max-age=0", NOW).unwrap();
        assert_eq!(h.len(), 0);
        assert!(!h.is_hsts_at("example.com", NOW));
        // Deleting a non-existent entry is a no-op success.
        h.parse_at("absent.example", "max-age=0", NOW).unwrap();
    }

    #[test]
    fn parse_rejects_malformed_headers() {
        let mut h = Hsts::new();
        // Missing mandatory max-age.
        assert!(h.parse_at("example.com", "includeSubDomains", NOW).is_err());
        // Empty header.
        assert!(h.parse_at("example.com", "", NOW).is_err());
        // Duplicate max-age.
        assert!(h
            .parse_at("example.com", "max-age=1; max-age=2", NOW)
            .is_err());
        // Duplicate includeSubDomains.
        assert!(h
            .parse_at(
                "example.com",
                "max-age=1; includeSubDomains; includeSubDomains",
                NOW
            )
            .is_err());
        // max-age with no '='.
        assert!(h.parse_at("example.com", "max-age 5", NOW).is_err());
        // max-age with no number.
        assert!(h.parse_at("example.com", "max-age=", NOW).is_err());
        // No entry should have been created by any failed parse.
        assert_eq!(h.len(), 0);
    }

    #[test]
    fn parse_ignores_ip_address_hosts() {
        let mut h = Hsts::new();
        h.parse_at("192.168.0.1", "max-age=1000; includeSubDomains", NOW)
            .unwrap();
        h.parse_at("::1", "max-age=1000", NOW).unwrap();
        assert_eq!(h.len(), 0);
    }

    #[test]
    fn parse_unquoted_overflow_saturates_to_unlimited() {
        let mut h = Hsts::new();
        // A max-age that overflows i64 saturates to the unlimited sentinel.
        h.parse_at("example.com", "max-age=99999999999999999999999999999", NOW)
            .unwrap();
        assert_eq!(h.len(), 1);
        assert_eq!(h.entries()[0].expires(), None);
    }

    #[test]
    fn parse_quoted_overflow_is_rejected() {
        // Parity with str_num_base: on overflow the cursor does not advance, so
        // the mandatory closing quote is "missing" and the parse fails.
        let mut h = Hsts::new();
        assert!(h
            .parse_at(
                "example.com",
                "max-age=\"99999999999999999999999999999\"",
                NOW
            )
            .is_err());
        assert_eq!(h.len(), 0);
    }

    // -- serialization & round-trip -----------------------------------------

    #[test]
    fn empty_store_serializes_to_header_only() {
        let h = Hsts::new();
        assert_eq!(h.to_file_string().unwrap(), HEADER);
    }

    #[test]
    fn file_header_has_no_stray_whitespace() {
        // Ground-truth header built from two *separate* literals joined with no
        // padding whatsoever — this is exactly the byte sequence curl 8.x writes
        // via its two `fputs` calls in `hsts_save`. It independently proves that
        // the `\`-continuation in `FILE_HEADER` strips the source indentation and
        // introduces no stray spaces on the second line.
        let ground_truth = concat!(
            "# Your HSTS cache. https://curl.se/docs/hsts.html\n",
            "# This file was generated by libcurl! Edit at your own risk.\n"
        );
        assert_eq!(Hsts::new().to_file_string().unwrap(), ground_truth);
    }

    #[test]
    fn file_output_is_byte_identical_to_curl() {
        let h = store(&[
            ("example.com", true, Some(ts(2037, 1, 1, 0, 0, 0))),
            ("example.net", false, None),
            ("sub.example.org", false, Some(ts(2019, 12, 31, 10, 0, 0))),
        ]);
        let expected = format!(
            "{HEADER}\
             .example.com \"20370101 00:00:00\"\n\
             example.net \"unlimited\"\n\
             sub.example.org \"20191231 10:00:00\"\n"
        );
        assert_eq!(h.to_file_string().unwrap(), expected);
    }

    #[test]
    fn round_trip_via_string_preserves_entries() {
        let original = store(&[
            ("example.com", true, Some(ts(2037, 1, 1, 0, 0, 0))),
            ("example.net", false, None),
            ("a.example.org", true, Some(ts(2030, 6, 1, 12, 30, 45))),
        ]);
        let text = original.to_file_string().unwrap();

        let mut loaded = Hsts::new();
        loaded.load_str_at(&text, NOW).unwrap();

        assert_eq!(loaded.entries(), original.entries());
        // And a second serialization is byte-identical (stable round-trip).
        assert_eq!(loaded.to_file_string().unwrap(), text);
    }

    #[test]
    fn load_skips_comments_and_blank_lines() {
        let text = "# a comment\n\
                    \n   \n\
                    example.com \"unlimited\"\n\
                    # another comment\n\
                    .sub.example.net \"20370101 00:00:00\"\n";
        let mut h = Hsts::new();
        h.load_str_at(text, NOW).unwrap();
        assert_eq!(h.len(), 2);
        assert_eq!(h.entries()[0].host(), "example.com");
        assert_eq!(h.entries()[0].expires(), None);
        assert_eq!(h.entries()[1].host(), "sub.example.net");
        assert!(h.entries()[1].include_subdomains());
        assert_eq!(h.entries()[1].expires(), Some(ts(2037, 1, 1, 0, 0, 0)));
    }

    #[test]
    fn load_ignores_malformed_lines() {
        let text = "example.com \"unlimited\"\n\
                    this line has no quoted date\n\
                    missingspace\"20370101 00:00:00\"\n\
                    good.example \"20370101 00:00:00\"\n";
        let mut h = Hsts::new();
        h.load_str_at(text, NOW).unwrap();
        assert_eq!(h.len(), 2);
        assert_eq!(h.entries()[0].host(), "example.com");
        assert_eq!(h.entries()[1].host(), "good.example");
    }

    #[test]
    fn load_tolerates_crlf_line_endings() {
        let text = "example.com \"unlimited\"\r\n.sub.net \"20370101 00:00:00\"\r\n";
        let mut h = Hsts::new();
        h.load_str_at(text, NOW).unwrap();
        assert_eq!(h.len(), 2);
        assert_eq!(h.entries()[0].host(), "example.com");
        assert_eq!(h.entries()[1].host(), "sub.net");
        assert!(h.entries()[1].include_subdomains());
    }

    #[test]
    fn load_add_keeps_latest_expiry_for_duplicate_host() {
        let text = "example.com \"20200101 00:00:00\"\n\
                    example.com \"20370101 00:00:00\"\n";
        let mut h = Hsts::new();
        h.load_str_at(text, NOW).unwrap();
        assert_eq!(h.len(), 1);
        assert_eq!(h.entries()[0].expires(), Some(ts(2037, 1, 1, 0, 0, 0)));

        // "unlimited" (None) beats any finite expiry.
        let text2 = "example.com \"20370101 00:00:00\"\nexample.com \"unlimited\"\n";
        let mut h2 = Hsts::new();
        h2.load_str_at(text2, NOW).unwrap();
        assert_eq!(h2.len(), 1);
        assert_eq!(h2.entries()[0].expires(), None);
    }

    #[test]
    fn load_strips_trailing_dot_on_create() {
        let mut h = Hsts::new();
        h.load_str_at("example.com. \"unlimited\"\n", NOW).unwrap();
        assert_eq!(h.entries()[0].host(), "example.com");
    }

    #[test]
    fn overlong_line_is_a_too_large_error() {
        let long_host = "a".repeat(MAX_HSTS_LINE);
        let text = format!("{long_host} \"unlimited\"\n");
        let mut h = Hsts::new();
        let err = h.load_str_at(&text, NOW).unwrap_err();
        assert_eq!(err.code(), crate::error::CurlCode::TooLarge);
    }

    // -- create() semantics --------------------------------------------------

    #[test]
    fn create_strips_trailing_dot_and_drops_empty() {
        let mut h = Hsts::new();
        h.create("example.com.", false, None);
        assert_eq!(h.entries()[0].host(), "example.com");
        // A host that is only a dot collapses to empty and is dropped.
        h.create(".", false, None);
        assert_eq!(h.len(), 1);
        h.create("", true, None);
        assert_eq!(h.len(), 1);
    }

    // -- callbacks (hsts_push / hsts_pull) -----------------------------------

    #[test]
    fn save_to_callback_streams_all_entries() {
        let h = store(&[
            ("example.com", true, Some(ts(2037, 1, 1, 0, 0, 0))),
            ("example.net", false, None),
        ]);
        let mut seen: Vec<(String, bool, String, usize, usize)> = Vec::new();
        h.save_to_callback(&mut |e, idx, total| {
            seen.push((
                e.name.clone(),
                e.include_subdomains,
                e.expire.clone(),
                idx,
                total,
            ));
            HstsCode::Ok
        })
        .unwrap();
        assert_eq!(seen.len(), 2);
        assert_eq!(
            seen[0],
            ("example.com".into(), true, "20370101 00:00:00".into(), 0, 2)
        );
        assert_eq!(
            seen[1],
            ("example.net".into(), false, UNLIMITED.into(), 1, 2)
        );
    }

    #[test]
    fn save_to_callback_done_stops_without_error() {
        let h = store(&[("a.example", false, None), ("b.example", false, None)]);
        let mut count = 0;
        h.save_to_callback(&mut |_, _, _| {
            count += 1;
            HstsCode::Done
        })
        .unwrap();
        assert_eq!(count, 1); // stopped after the first
    }

    #[test]
    fn save_to_callback_fail_is_an_error() {
        let h = store(&[("a.example", false, None)]);
        let err = h
            .save_to_callback(&mut |_, _, _| HstsCode::Fail)
            .unwrap_err();
        assert_eq!(err.code(), crate::error::CurlCode::BadFunctionArgument);
    }

    #[test]
    fn load_from_callback_adds_entries() {
        let feed = [
            ("example.com", true, "20370101 00:00:00"),
            ("example.net", false, ""), // empty expire ⇒ unlimited
        ];
        let mut i = 0;
        let mut h = Hsts::new();
        h.load_from_callback(&mut |e| {
            if i < feed.len() {
                let (n, sub, exp) = feed[i];
                e.name = n.to_string();
                e.include_subdomains = sub;
                e.expire = exp.to_string();
                i += 1;
                HstsCode::Ok
            } else {
                HstsCode::Done
            }
        })
        .unwrap();
        assert_eq!(h.len(), 2);
        assert_eq!(h.entries()[0].host(), "example.com");
        assert!(h.entries()[0].include_subdomains());
        assert_eq!(h.entries()[0].expires(), Some(ts(2037, 1, 1, 0, 0, 0)));
        assert_eq!(h.entries()[1].host(), "example.net");
        assert_eq!(h.entries()[1].expires(), None);
    }

    #[test]
    fn load_from_callback_empty_name_is_rejected() {
        let mut h = Hsts::new();
        let err = h
            .load_from_callback(&mut |e| {
                e.name = String::new();
                HstsCode::Ok
            })
            .unwrap_err();
        assert_eq!(err.code(), crate::error::CurlCode::BadFunctionArgument);
    }

    #[test]
    fn load_from_callback_fail_aborts() {
        let mut h = Hsts::new();
        let err = h.load_from_callback(&mut |_| HstsCode::Fail).unwrap_err();
        assert_eq!(err.code(), crate::error::CurlCode::AbortedByCallback);
    }

    // -- flags & save() gating ----------------------------------------------

    #[test]
    fn readonly_flag_skips_file_write() {
        let mut h = store(&[("example.com", false, None)]);
        h.set_readonly(true);
        assert_eq!(h.flags() & CURLHSTS_READONLYFILE, CURLHSTS_READONLYFILE);
        // A read-only save is a silent success and writes nothing.
        let path = unique_temp_path("hsts_readonly");
        h.save(Some(&path)).unwrap();
        assert!(!std::path::Path::new(&path).exists());
    }

    #[test]
    fn save_without_path_is_a_noop() {
        let h = store(&[("example.com", false, None)]);
        // No explicit path and no remembered filename ⇒ nothing happens.
        h.save(None).unwrap();
    }

    // -- real filesystem round-trip (save → load_file) ----------------------

    fn unique_temp_path(tag: &str) -> String {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let mut p = std::env::temp_dir();
        p.push(format!(
            "blitzy_hsts_{tag}_{}_{}",
            std::process::id(),
            nanos
        ));
        p.to_string_lossy().into_owned()
    }

    #[test]
    fn save_and_load_file_round_trip_on_disk() {
        let path = unique_temp_path("roundtrip");
        let original = store(&[
            ("example.com", true, Some(ts(2037, 1, 1, 0, 0, 0))),
            ("example.net", false, None),
        ]);
        original.save(Some(&path)).unwrap();

        // The bytes on disk match the canonical serialization exactly.
        let on_disk = std::fs::read_to_string(&path).unwrap();
        assert_eq!(on_disk, original.to_file_string().unwrap());

        // Loading them back reproduces the entries and remembers the filename.
        let mut loaded = Hsts::new();
        loaded.load_file_at(&path, NOW).unwrap();
        assert_eq!(loaded.entries(), original.entries());
        assert_eq!(loaded.filename(), Some(path.as_str()));

        // A save() with no path reuses the remembered filename.
        loaded.save(None).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), on_disk);

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn load_missing_file_is_ok() {
        let path = unique_temp_path("missing");
        let mut h = Hsts::new();
        h.load_file_at(&path, NOW).unwrap(); // no error
        assert_eq!(h.len(), 0);
        assert_eq!(h.filename(), Some(path.as_str()));
    }

    #[test]
    fn load_files_loads_in_order_and_accumulates() {
        let p1 = unique_temp_path("files1");
        let p2 = unique_temp_path("files2");
        std::fs::write(&p1, format!("{HEADER}example.com \"unlimited\"\n")).unwrap();
        std::fs::write(&p2, format!("{HEADER}example.net \"unlimited\"\n")).unwrap();

        let mut h = Hsts::new();
        h.load_files(&[p1.clone(), p2.clone()]).unwrap();
        assert_eq!(h.len(), 2);
        assert_eq!(h.entries()[0].host(), "example.com");
        assert_eq!(h.entries()[1].host(), "example.net");
        // Filename is the last one loaded.
        assert_eq!(h.filename(), Some(p2.as_str()));

        let _ = std::fs::remove_file(&p1);
        let _ = std::fs::remove_file(&p2);
    }
}
