//! HSTS (HTTP Strict Transport Security) preload list management.
//!
//! Rust rewrite of `lib/hsts.c` from curl 8.19.0-DEV. Implements RFC 6797
//! Strict-Transport-Security header parsing, hostname matching (including
//! subdomain matching), and file-compatible cache I/O with curl 8.x.
//!
//! The HSTS cache file format is defined at <https://curl.se/docs/hsts.html>.
//!
//! # File Format
//!
//! ```text
//! # Your HSTS cache. https://curl.se/docs/hsts.html
//! # This file was generated by libcurl! Edit at your own risk.
//! example.com "20241231 23:59:59"
//! .example.net "20241231 23:59:59"
//! always.example.org "unlimited"
//! ```
//!
//! A leading `.` before the hostname indicates `includeSubDomains`.

use std::collections::HashMap;
use std::fs::{self, File};
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::net::IpAddr;
use std::path::{Path, PathBuf};

use chrono::{DateTime, NaiveDateTime, Utc};

use crate::error::{CurlError, CurlResult};

// ---------------------------------------------------------------------------
// Constants — matching the C implementation's limits
// ---------------------------------------------------------------------------

/// Maximum hostname length for HSTS entries (matching C `MAX_HSTS_HOSTLEN`).
const MAX_HSTS_HOSTLEN: usize = 2048;

/// Maximum line length when reading HSTS cache files (matching C `MAX_HSTS_LINE`).
const MAX_HSTS_LINE: usize = 4095;

/// Sentinel value for entries that never expire.
///
/// In curl 8.x this corresponds to `TIME_T_MAX`. We use [`i64::MAX`] as the
/// Rust equivalent — any entry whose `expires` field equals this value is
/// serialised as `"unlimited"` in the cache file.
const HSTS_UNLIMITED: i64 = i64::MAX;

/// The literal string `"unlimited"` used in cache files for non-expiring entries.
const UNLIMITED_STR: &str = "unlimited";

/// The `strftime`-style format string used for HSTS cache file timestamps.
///
/// Matches the C format `"%d%02d%02d %02d:%02d:%02d"` applied to
/// `(tm_year+1900, tm_mon+1, tm_mday, tm_hour, tm_min, tm_sec)`.
const HSTS_DATE_FORMAT: &str = "%Y%m%d %H:%M:%S";

// ---------------------------------------------------------------------------
// HstsEntry
// ---------------------------------------------------------------------------

/// A single HSTS entry representing a hostname that must be accessed over HTTPS.
///
/// Maps to the C `struct stsentry` from `lib/hsts.h`. Each entry records the
/// host, whether subdomains should also be upgraded, and the absolute Unix
/// timestamp at which the directive expires.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HstsEntry {
    /// The hostname (lowercase, no trailing dot).
    pub hostname: String,

    /// Whether subdomains of this host should also be upgraded to HTTPS.
    ///
    /// Corresponds to the `includeSubDomains` directive in the
    /// `Strict-Transport-Security` header (RFC 6797 §6.1).
    pub include_subdomains: bool,

    /// Unix timestamp (seconds since epoch, UTC) of when this entry expires.
    ///
    /// [`i64::MAX`] means the entry never expires (serialised as `"unlimited"`
    /// in the cache file).
    pub expires: i64,
}

// ---------------------------------------------------------------------------
// HstsCache
// ---------------------------------------------------------------------------

/// HSTS cache storing known Strict-Transport-Security entries.
///
/// Maps to the C `struct hsts` from `lib/hsts.h`. Entries are stored in a
/// [`HashMap`] keyed by lowercase hostname, replacing the C linked-list
/// (`Curl_llist`) implementation for O(1) exact-match lookups.
///
/// # File Format Compatibility
///
/// The [`load_file`](HstsCache::load_file) and [`save_file`](HstsCache::save_file)
/// methods produce and consume the same cache file format as curl 8.x, ensuring
/// seamless interoperability with the C implementation.
#[derive(Debug)]
pub struct HstsCache {
    /// HSTS entries keyed by normalised (lowercase, no trailing dot) hostname.
    entries: HashMap<String, HstsEntry>,
}

impl Default for HstsCache {
    fn default() -> Self {
        Self::new()
    }
}

impl HstsCache {
    // -------------------------------------------------------------------
    // Construction
    // -------------------------------------------------------------------

    /// Creates a new, empty HSTS cache.
    ///
    /// Equivalent to `Curl_hsts_init()` in `lib/hsts.c`.
    pub fn new() -> Self {
        HstsCache {
            entries: HashMap::new(),
        }
    }

    // -------------------------------------------------------------------
    // Lookup
    // -------------------------------------------------------------------

    /// Returns `true` if the given hostname should be upgraded from HTTP to HTTPS.
    ///
    /// The lookup proceeds in two stages:
    ///
    /// 1. **Exact match** — the cache contains a non-expired entry whose
    ///    hostname equals the queried hostname (case-insensitive, trailing dots
    ///    stripped).
    /// 2. **Subdomain match** — the cache contains a non-expired entry for a
    ///    parent domain where `includeSubDomains` is set. When multiple parent
    ///    domains match, the longest (most specific) match wins.
    ///
    /// # RFC 6797 Compliance
    ///
    /// * IP addresses are never upgraded (§8.2).
    /// * Hostnames exceeding [`MAX_HSTS_HOSTLEN`] bytes are rejected.
    /// * Expired entries are silently skipped.
    pub fn should_upgrade(&self, hostname: &str) -> bool {
        // Empty or IP-literal hostnames are excluded per RFC 6797 §8.2.
        if hostname.is_empty() || is_ip_address(hostname) {
            return false;
        }

        let hostname_norm = normalize_hostname(hostname);
        if hostname_norm.is_empty() || hostname_norm.len() > MAX_HSTS_HOSTLEN {
            return false;
        }

        let now = Utc::now().timestamp();

        // Stage 1: exact match (O(1) HashMap lookup).
        if let Some(entry) = self.entries.get(&hostname_norm) {
            if entry.expires > now {
                return true;
            }
        }

        // Stage 2: subdomain tail-match — iterate all entries looking for a
        // parent domain with includeSubDomains set.  Track the longest match
        // to mirror the C implementation's "best tail match" logic.
        let mut best_match_len: usize = 0;
        let mut found = false;

        for entry in self.entries.values() {
            // Only consider non-expired entries with includeSubDomains.
            if !entry.include_subdomains || entry.expires <= now {
                continue;
            }
            let parent_len = entry.hostname.len();
            // The parent must be strictly shorter than the queried hostname.
            if parent_len >= hostname_norm.len() {
                continue;
            }
            // Check that hostname ends with ".parent".
            let offset = hostname_norm.len() - parent_len;
            if hostname_norm.as_bytes()[offset - 1] == b'.'
                && hostname_norm[offset..] == entry.hostname[..]
                && parent_len > best_match_len
            {
                best_match_len = parent_len;
                found = true;
            }
        }

        found
    }

    // -------------------------------------------------------------------
    // Header parsing
    // -------------------------------------------------------------------

    /// Parses a `Strict-Transport-Security` header value and updates the cache.
    ///
    /// The header value is expected to conform to RFC 6797 §6.1:
    ///
    /// ```text
    /// Strict-Transport-Security: max-age=<seconds>[; includeSubDomains][; preload]
    /// ```
    ///
    /// # Behaviour
    ///
    /// * `max-age=0` **removes** the entry for `hostname` (if present).
    /// * `max-age=N` (N > 0) adds or updates the entry with
    ///   `expires = now + N`.
    /// * IP-address hostnames are silently ignored (RFC 6797 §8.2).
    /// * Unknown directives (e.g. `preload`) are skipped.
    ///
    /// # Errors
    ///
    /// Returns [`CurlError::BadFunctionArgument`] when:
    /// * The `max-age` directive is absent.
    /// * The `max-age` value is not a valid non-negative integer.
    /// * Duplicate `max-age` or `includeSubDomains` directives appear.
    pub fn parse_header(&mut self, hostname: &str, header: &str) -> CurlResult<()> {
        // IP addresses are excluded per RFC 6797 §8.2.
        if is_ip_address(hostname) {
            return Ok(());
        }

        let hostname_norm = normalize_hostname(hostname);
        if hostname_norm.is_empty() {
            return Ok(());
        }

        let mut p = header.as_bytes();
        let mut max_age_value: Option<i64> = None;
        let mut got_max_age = false;
        let mut got_include = false;
        let mut include_subdomains = false;

        // Parse directives separated by semicolons.
        loop {
            skip_blanks(&mut p);
            if p.is_empty() {
                break;
            }

            if p.len() >= 7 && p[..7].eq_ignore_ascii_case(b"max-age") {
                // ---- max-age directive ----
                if got_max_age {
                    return Err(CurlError::BadFunctionArgument);
                }
                p = &p[7..];
                skip_blanks(&mut p);

                // Expect '='
                if p.is_empty() || p[0] != b'=' {
                    return Err(CurlError::BadFunctionArgument);
                }
                p = &p[1..];
                skip_blanks(&mut p);

                // Handle optional quoting of the value.
                let quoted = !p.is_empty() && p[0] == b'"';
                if quoted {
                    p = &p[1..];
                }

                let (value, rest) = parse_max_age_number(p)?;
                p = rest;

                if quoted {
                    if p.is_empty() || p[0] != b'"' {
                        return Err(CurlError::BadFunctionArgument);
                    }
                    p = &p[1..];
                }

                max_age_value = Some(value);
                got_max_age = true;
            } else if p.len() >= 17
                && p[..17].eq_ignore_ascii_case(b"includesubdomains")
            {
                // ---- includeSubDomains directive ----
                if got_include {
                    return Err(CurlError::BadFunctionArgument);
                }
                include_subdomains = true;
                p = &p[17..];
                got_include = true;
            } else {
                // ---- unknown directive — skip until ';' or end ----
                while !p.is_empty() && p[0] != b';' {
                    p = &p[1..];
                }
            }

            skip_blanks(&mut p);
            if !p.is_empty() && p[0] == b';' {
                p = &p[1..];
            }
        }

        // max-age is mandatory per RFC 6797 §6.1.
        if !got_max_age {
            return Err(CurlError::BadFunctionArgument);
        }

        let expires_seconds = max_age_value.unwrap_or(0);

        if expires_seconds == 0 {
            // max-age=0 means "remove the entry" (RFC 6797 §6.1.1).
            self.entries.remove(&hostname_norm);
            return Ok(());
        }

        // Compute absolute expiry, saturating on overflow.
        let now = Utc::now().timestamp();
        let expires = if HSTS_UNLIMITED - now < expires_seconds {
            HSTS_UNLIMITED
        } else {
            now + expires_seconds
        };

        // Update existing entry or insert a new one.
        match self.entries.get_mut(&hostname_norm) {
            Some(entry) => {
                entry.expires = expires;
                entry.include_subdomains = include_subdomains;
            }
            None => {
                self.entries.insert(
                    hostname_norm.clone(),
                    HstsEntry {
                        hostname: hostname_norm,
                        include_subdomains,
                        expires,
                    },
                );
            }
        }

        Ok(())
    }

    // -------------------------------------------------------------------
    // Manual entry management
    // -------------------------------------------------------------------

    /// Adds or updates an HSTS entry for the given hostname.
    ///
    /// If an entry for `hostname` already exists it is updated in place.
    /// Otherwise a new entry is created.
    ///
    /// # Arguments
    ///
    /// * `hostname` — The hostname (trailing dots stripped, lowered internally).
    /// * `include_subdomains` — Whether subdomains should also be upgraded.
    /// * `expires` — Unix timestamp of when this entry expires; use
    ///   [`i64::MAX`] for an entry that never expires.
    ///
    /// # Errors
    ///
    /// Returns [`CurlError::BadFunctionArgument`] if the hostname is empty or
    /// exceeds [`MAX_HSTS_HOSTLEN`] bytes after normalisation.
    pub fn add(
        &mut self,
        hostname: &str,
        include_subdomains: bool,
        expires: i64,
    ) -> CurlResult<()> {
        let hostname_norm = normalize_hostname(hostname);
        if hostname_norm.is_empty() || hostname_norm.len() > MAX_HSTS_HOSTLEN {
            return Err(CurlError::BadFunctionArgument);
        }

        match self.entries.get_mut(&hostname_norm) {
            Some(entry) => {
                entry.include_subdomains = include_subdomains;
                entry.expires = expires;
            }
            None => {
                self.entries.insert(
                    hostname_norm.clone(),
                    HstsEntry {
                        hostname: hostname_norm,
                        include_subdomains,
                        expires,
                    },
                );
            }
        }

        Ok(())
    }

    // -------------------------------------------------------------------
    // File I/O — curl 8.x compatible
    // -------------------------------------------------------------------

    /// Loads HSTS entries from a cache file in curl 8.x format.
    ///
    /// Each non-comment, non-empty line is parsed as:
    ///
    /// ```text
    /// [.]hostname "YYYYMMDD HH:MM:SS"
    /// [.]hostname "unlimited"
    /// ```
    ///
    /// * A leading `.` signals `includeSubDomains`.
    /// * Comment lines starting with `#` are ignored.
    /// * Lines exceeding [`MAX_HSTS_LINE`] are silently skipped.
    /// * Syntactically invalid lines are silently skipped (matching curl 8.x).
    ///
    /// If the file does not exist the method returns `Ok(())` — this matches
    /// the C implementation's behaviour of treating a missing file as an empty
    /// cache.
    pub fn load_file(&mut self, path: &Path) -> CurlResult<()> {
        let file = match File::open(path) {
            Ok(f) => f,
            // File does not exist — not an error, matching C behaviour.
            Err(_) => return Ok(()),
        };

        let reader = BufReader::new(file);

        for line_result in reader.lines() {
            let line = match line_result {
                Ok(l) => l,
                // I/O error while reading — stop, but do not propagate
                // (matching C behaviour: `hsts_load` only returns serious errors).
                Err(_) => break,
            };

            // Enforce maximum line length.
            if line.len() > MAX_HSTS_LINE {
                continue;
            }

            let trimmed = line.trim();

            // Skip empty lines, single-character lines, and comments.
            if trimmed.is_empty() || trimmed.len() <= 1 || trimmed.starts_with('#') {
                continue;
            }

            self.parse_cache_line(trimmed);
        }

        Ok(())
    }

    /// Saves the HSTS cache to a file in curl 8.x format.
    ///
    /// The file is first written to a temporary path (`<path>.tmp`) and then
    /// atomically renamed to the final destination, mirroring the safe-write
    /// pattern used in the C implementation (`Curl_fopen` → write → rename).
    ///
    /// Entries are sorted by hostname for deterministic output.
    ///
    /// # Errors
    ///
    /// Returns [`CurlError::WriteError`] if the file cannot be created, written,
    /// or atomically renamed.
    pub fn save_file(&self, path: &Path) -> CurlResult<()> {
        // Build the temporary file path: append ".tmp" to the original name.
        let temp_path = build_temp_path(path);

        // Write to the temporary file.
        let file = File::create(&temp_path).map_err(|_| CurlError::WriteError)?;
        let mut writer = BufWriter::new(file);

        // Header comments (identical to curl 8.x output).
        writer
            .write_all(b"# Your HSTS cache. https://curl.se/docs/hsts.html\n")
            .map_err(|_| CurlError::WriteError)?;
        writer
            .write_all(b"# This file was generated by libcurl! Edit at your own risk.\n")
            .map_err(|_| CurlError::WriteError)?;

        // Collect and sort entries by hostname for deterministic output.
        let mut sorted_entries: Vec<&HstsEntry> = self.entries.values().collect();
        sorted_entries.sort_by(|a, b| a.hostname.cmp(&b.hostname));

        for entry in sorted_entries {
            let prefix = if entry.include_subdomains { "." } else { "" };

            if entry.expires == HSTS_UNLIMITED {
                writeln!(writer, "{}{} \"{}\"", prefix, entry.hostname, UNLIMITED_STR)
                    .map_err(|_| CurlError::WriteError)?;
            } else {
                let date_str = format_hsts_date(entry.expires);
                writeln!(writer, "{}{} \"{}\"", prefix, entry.hostname, date_str)
                    .map_err(|_| CurlError::WriteError)?;
            }
        }

        // Flush all buffered data to disk.
        writer.flush().map_err(|_| CurlError::WriteError)?;
        // Explicitly drop the writer so the underlying file handle is closed
        // before the rename, which is important on Windows.
        drop(writer);

        // Atomically rename temp → target.  On failure, clean up the temp file.
        fs::rename(&temp_path, path).map_err(|_| {
            let _ = fs::remove_file(&temp_path);
            CurlError::WriteError
        })?;

        Ok(())
    }

    // -------------------------------------------------------------------
    // Bulk operations
    // -------------------------------------------------------------------

    /// Removes all entries from the cache.
    pub fn clear(&mut self) {
        self.entries.clear();
    }

    /// Returns `true` if the cache contains no entries.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    // -------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------

    /// Parses a single non-comment, non-empty line from an HSTS cache file.
    ///
    /// Expected format:
    /// ```text
    /// [.]hostname "YYYYMMDD HH:MM:SS"
    /// [.]hostname "unlimited"
    /// ```
    ///
    /// Invalid lines are silently ignored (matching `hsts_add` in `lib/hsts.c`).
    fn parse_cache_line(&mut self, line: &str) {
        // ---- Extract hostname (first whitespace-delimited word) ----
        let hostname_end = line
            .find(|c: char| c.is_ascii_whitespace())
            .unwrap_or(line.len());
        if hostname_end == 0 {
            return;
        }
        let mut hostname_str = &line[..hostname_end];
        let rest = &line[hostname_end..];

        // Leading dot indicates includeSubDomains.
        let include_subdomains = hostname_str.starts_with('.');
        if include_subdomains {
            hostname_str = &hostname_str[1..];
        }

        if hostname_str.is_empty() || hostname_str.len() > MAX_HSTS_HOSTLEN {
            return;
        }

        // ---- Extract quoted date string ----
        let rest = rest.trim_start();
        if !rest.starts_with('"') {
            return;
        }
        let inner = &rest[1..]; // skip opening quote
        let close_quote = match inner.find('"') {
            Some(pos) => pos,
            None => return, // no closing quote — malformed line
        };
        let date_str = &inner[..close_quote];

        // ---- Parse expiry timestamp ----
        let expires = if date_str == UNLIMITED_STR {
            HSTS_UNLIMITED
        } else {
            match parse_hsts_date(date_str) {
                Some(ts) => ts,
                None => return, // unparseable date — skip line
            }
        };

        let hostname_norm = hostname_str.to_ascii_lowercase();

        // Insert or update: use the largest expire time when the same hostname
        // appears more than once (matching C `hsts_add` behaviour).
        match self.entries.get_mut(&hostname_norm) {
            Some(existing) => {
                if expires > existing.expires {
                    existing.expires = expires;
                }
                // Also update include_subdomains if this line says so
                // (C behaviour: only update expiry, keep original subdomain flag
                //  unless the hostnames are case-equal — simplified here to always
                //  keep the first seen value, matching the net effect of the C code
                //  which only updates expiry for duplicate hostnames).
            }
            None => {
                self.entries.insert(
                    hostname_norm.clone(),
                    HstsEntry {
                        hostname: hostname_norm,
                        include_subdomains,
                        expires,
                    },
                );
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Free-standing helper functions
// ---------------------------------------------------------------------------

/// Normalises a hostname by stripping trailing dots and converting to lowercase.
///
/// This mirrors the C code's treatment of hostnames in `hsts_create` and
/// `Curl_hsts` where trailing dots are removed before storage and comparison.
fn normalize_hostname(hostname: &str) -> String {
    let trimmed = hostname.trim_end_matches('.');
    trimmed.to_ascii_lowercase()
}

/// Returns `true` if the given string is an IP address (IPv4 or IPv6).
///
/// Per RFC 6797 §8.2 ("explicit IP address identification of all forms is
/// excluded"), HSTS must never be applied to requests addressed by IP literal.
fn is_ip_address(hostname: &str) -> bool {
    // Handle bracketed IPv6 notation, e.g. "[::1]".
    let host = hostname
        .strip_prefix('[')
        .and_then(|h| h.strip_suffix(']'))
        .unwrap_or(hostname);
    host.parse::<IpAddr>().is_ok()
}

/// Advances the slice past any leading ASCII whitespace bytes.
fn skip_blanks(p: &mut &[u8]) {
    while !p.is_empty() && p[0].is_ascii_whitespace() {
        *p = &p[1..];
    }
}

/// Parses a non-negative decimal integer from the front of a byte slice.
///
/// Returns `(value, remaining_slice)`.  On overflow the value saturates to
/// [`i64::MAX`] (matching the C code's `CURL_OFF_T_MAX` saturation in
/// `Curl_hsts_parse`).
///
/// # Errors
///
/// Returns [`CurlError::BadFunctionArgument`] if no leading digits are found.
fn parse_max_age_number(p: &[u8]) -> CurlResult<(i64, &[u8])> {
    let mut end = 0;
    while end < p.len() && p[end].is_ascii_digit() {
        end += 1;
    }
    if end == 0 {
        return Err(CurlError::BadFunctionArgument);
    }
    // SAFETY of unwrap: the slice contains only ASCII digits which are valid UTF-8.
    let s = std::str::from_utf8(&p[..end]).map_err(|_| CurlError::BadFunctionArgument)?;
    // On overflow, saturate to i64::MAX (mirrors C STRE_OVERFLOW → CURL_OFF_T_MAX).
    let value = s.parse::<i64>().unwrap_or(i64::MAX);
    Ok((value, &p[end..]))
}

/// Formats a Unix timestamp into the HSTS cache date string `YYYYMMDD HH:MM:SS`.
///
/// If the timestamp cannot be represented as a calendar date (e.g. [`i64::MAX`]),
/// returns the string `"unlimited"`.
fn format_hsts_date(timestamp: i64) -> String {
    DateTime::from_timestamp(timestamp, 0)
        .map(|dt: DateTime<Utc>| dt.format(HSTS_DATE_FORMAT).to_string())
        .unwrap_or_else(|| UNLIMITED_STR.to_string())
}

/// Parses an HSTS cache date string `YYYYMMDD HH:MM:SS` into a Unix timestamp.
///
/// Returns `None` if the string does not match the expected format.
fn parse_hsts_date(date_str: &str) -> Option<i64> {
    NaiveDateTime::parse_from_str(date_str, HSTS_DATE_FORMAT)
        .ok()
        .map(|ndt| ndt.and_utc().timestamp())
}

/// Builds the temporary file path used during atomic save operations.
///
/// Appends `.tmp` to the file name component of `path`.
fn build_temp_path(path: &Path) -> PathBuf {
    let mut temp = PathBuf::from(path);
    let mut name = temp
        .file_name()
        .unwrap_or_default()
        .to_os_string();
    name.push(".tmp");
    temp.set_file_name(name);
    temp
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -- HstsEntry construction ------------------------------------------

    #[test]
    fn entry_fields_are_public() {
        let entry = HstsEntry {
            hostname: "example.com".into(),
            include_subdomains: true,
            expires: 1_700_000_000,
        };
        assert_eq!(entry.hostname, "example.com");
        assert!(entry.include_subdomains);
        assert_eq!(entry.expires, 1_700_000_000);
    }

    // -- HstsCache::new / is_empty / clear --------------------------------

    #[test]
    fn new_cache_is_empty() {
        let cache = HstsCache::new();
        assert!(cache.is_empty());
    }

    #[test]
    fn default_cache_is_empty() {
        let cache = HstsCache::default();
        assert!(cache.is_empty());
    }

    #[test]
    fn clear_empties_the_cache() {
        let mut cache = HstsCache::new();
        cache.add("example.com", false, HSTS_UNLIMITED).unwrap();
        assert!(!cache.is_empty());
        cache.clear();
        assert!(cache.is_empty());
    }

    // -- HstsCache::add ---------------------------------------------------

    #[test]
    fn add_and_retrieve() {
        let mut cache = HstsCache::new();
        cache.add("Example.COM", false, HSTS_UNLIMITED).unwrap();
        assert!(!cache.is_empty());
        assert!(cache.should_upgrade("example.com"));
    }

    #[test]
    fn add_strips_trailing_dot() {
        let mut cache = HstsCache::new();
        cache.add("example.com.", false, HSTS_UNLIMITED).unwrap();
        assert!(cache.should_upgrade("example.com"));
    }

    #[test]
    fn add_rejects_empty_hostname() {
        let mut cache = HstsCache::new();
        assert!(cache.add("", false, HSTS_UNLIMITED).is_err());
    }

    #[test]
    fn add_rejects_dot_only_hostname() {
        let mut cache = HstsCache::new();
        assert!(cache.add(".", false, HSTS_UNLIMITED).is_err());
    }

    #[test]
    fn add_updates_existing_entry() {
        let mut cache = HstsCache::new();
        cache.add("example.com", false, 1000).unwrap();
        cache.add("example.com", true, 2000).unwrap();
        // The entry should now have the updated values.
        let entry = cache.entries.get("example.com").unwrap();
        assert!(entry.include_subdomains);
        assert_eq!(entry.expires, 2000);
    }

    // -- HstsCache::should_upgrade ----------------------------------------

    #[test]
    fn should_upgrade_empty_hostname_returns_false() {
        let cache = HstsCache::new();
        assert!(!cache.should_upgrade(""));
    }

    #[test]
    fn should_upgrade_ip_address_returns_false() {
        let mut cache = HstsCache::new();
        cache.add("127.0.0.1", false, HSTS_UNLIMITED).unwrap();
        // Even though we added it, lookup for an IP must return false.
        assert!(!cache.should_upgrade("127.0.0.1"));
    }

    #[test]
    fn should_upgrade_ipv6_returns_false() {
        let cache = HstsCache::new();
        assert!(!cache.should_upgrade("::1"));
        assert!(!cache.should_upgrade("[::1]"));
    }

    #[test]
    fn should_upgrade_exact_match() {
        let mut cache = HstsCache::new();
        cache.add("secure.example.com", false, HSTS_UNLIMITED).unwrap();
        assert!(cache.should_upgrade("secure.example.com"));
        assert!(!cache.should_upgrade("other.example.com"));
    }

    #[test]
    fn should_upgrade_case_insensitive() {
        let mut cache = HstsCache::new();
        cache.add("Secure.Example.COM", false, HSTS_UNLIMITED).unwrap();
        assert!(cache.should_upgrade("secure.example.com"));
        assert!(cache.should_upgrade("SECURE.EXAMPLE.COM"));
    }

    #[test]
    fn should_upgrade_subdomain_match() {
        let mut cache = HstsCache::new();
        cache.add("example.com", true, HSTS_UNLIMITED).unwrap();
        assert!(cache.should_upgrade("example.com"));
        assert!(cache.should_upgrade("sub.example.com"));
        assert!(cache.should_upgrade("deep.sub.example.com"));
        // Without includeSubDomains, subdomains should not match.
        assert!(!cache.should_upgrade("notexample.com"));
    }

    #[test]
    fn should_upgrade_subdomain_disabled() {
        let mut cache = HstsCache::new();
        cache.add("example.com", false, HSTS_UNLIMITED).unwrap();
        assert!(cache.should_upgrade("example.com"));
        assert!(!cache.should_upgrade("sub.example.com"));
    }

    #[test]
    fn should_upgrade_expired_entry_skipped() {
        let mut cache = HstsCache::new();
        // Add an entry that expired in the past.
        cache.add("expired.example.com", false, 0).unwrap();
        assert!(!cache.should_upgrade("expired.example.com"));
    }

    #[test]
    fn should_upgrade_longest_subdomain_match() {
        let mut cache = HstsCache::new();
        // Both parent domains have includeSubDomains.
        cache.add("com", true, HSTS_UNLIMITED).unwrap();
        cache.add("example.com", true, HSTS_UNLIMITED).unwrap();
        // "sub.example.com" should match "example.com" (longer) not "com".
        assert!(cache.should_upgrade("sub.example.com"));
    }

    // -- HstsCache::parse_header ------------------------------------------

    #[test]
    fn parse_header_basic_max_age() {
        let mut cache = HstsCache::new();
        cache
            .parse_header("example.com", "max-age=31536000")
            .unwrap();
        assert!(cache.should_upgrade("example.com"));
    }

    #[test]
    fn parse_header_with_include_subdomains() {
        let mut cache = HstsCache::new();
        cache
            .parse_header("example.com", "max-age=31536000; includeSubDomains")
            .unwrap();
        assert!(cache.should_upgrade("example.com"));
        assert!(cache.should_upgrade("sub.example.com"));
    }

    #[test]
    fn parse_header_with_preload() {
        let mut cache = HstsCache::new();
        // "preload" is an unknown directive — should be silently skipped.
        cache
            .parse_header("example.com", "max-age=31536000; includeSubDomains; preload")
            .unwrap();
        assert!(cache.should_upgrade("example.com"));
    }

    #[test]
    fn parse_header_max_age_zero_removes_entry() {
        let mut cache = HstsCache::new();
        cache.add("example.com", false, HSTS_UNLIMITED).unwrap();
        assert!(cache.should_upgrade("example.com"));
        cache.parse_header("example.com", "max-age=0").unwrap();
        assert!(!cache.should_upgrade("example.com"));
        assert!(cache.is_empty());
    }

    #[test]
    fn parse_header_quoted_max_age() {
        let mut cache = HstsCache::new();
        cache
            .parse_header("example.com", "max-age=\"31536000\"")
            .unwrap();
        assert!(cache.should_upgrade("example.com"));
    }

    #[test]
    fn parse_header_missing_max_age_is_error() {
        let mut cache = HstsCache::new();
        let result = cache.parse_header("example.com", "includeSubDomains");
        assert!(result.is_err());
    }

    #[test]
    fn parse_header_duplicate_max_age_is_error() {
        let mut cache = HstsCache::new();
        let result = cache.parse_header("example.com", "max-age=100; max-age=200");
        assert!(result.is_err());
    }

    #[test]
    fn parse_header_duplicate_include_is_error() {
        let mut cache = HstsCache::new();
        let result = cache.parse_header(
            "example.com",
            "max-age=100; includeSubDomains; includeSubDomains",
        );
        assert!(result.is_err());
    }

    #[test]
    fn parse_header_ignores_ip_address() {
        let mut cache = HstsCache::new();
        cache.parse_header("192.168.1.1", "max-age=100").unwrap();
        assert!(cache.is_empty());
    }

    #[test]
    fn parse_header_case_insensitive_directives() {
        let mut cache = HstsCache::new();
        cache
            .parse_header("example.com", "Max-Age=100; INCLUDESUBDOMAINS")
            .unwrap();
        assert!(cache.should_upgrade("example.com"));
        assert!(cache.should_upgrade("sub.example.com"));
    }

    #[test]
    fn parse_header_updates_existing() {
        let mut cache = HstsCache::new();
        cache
            .parse_header("example.com", "max-age=100")
            .unwrap();
        cache
            .parse_header("example.com", "max-age=200; includeSubDomains")
            .unwrap();
        let entry = cache.entries.get("example.com").unwrap();
        assert!(entry.include_subdomains);
    }

    // -- File I/O ---------------------------------------------------------

    #[test]
    fn save_and_load_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("hsts_cache");

        let mut cache = HstsCache::new();
        cache.add("example.com", false, 1_893_456_000).unwrap(); // 2029-12-31 ...
        cache.add("secure.net", true, HSTS_UNLIMITED).unwrap();

        cache.save_file(&path).unwrap();

        let mut loaded = HstsCache::new();
        loaded.load_file(&path).unwrap();

        assert_eq!(loaded.entries.len(), 2);
        assert!(loaded.should_upgrade("example.com"));
        assert!(loaded.should_upgrade("secure.net"));
        assert!(loaded.should_upgrade("sub.secure.net"));
    }

    #[test]
    fn save_file_format_matches_curl() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("hsts_cache");

        let mut cache = HstsCache::new();
        // Use a known timestamp: 2024-06-15 12:00:00 UTC = 1718452800
        cache.add("example.com", false, 1_718_452_800).unwrap();
        cache.add("secure.net", true, HSTS_UNLIMITED).unwrap();

        cache.save_file(&path).unwrap();

        let contents = std::fs::read_to_string(&path).unwrap();
        assert!(contents.starts_with("# Your HSTS cache. https://curl.se/docs/hsts.html\n"));
        assert!(contents.contains("# This file was generated by libcurl! Edit at your own risk.\n"));
        // Check entry format — hostname then quoted date.
        assert!(contents.contains("example.com \"20240615 12:00:00\"\n"));
        assert!(contents.contains(".secure.net \"unlimited\"\n"));
    }

    #[test]
    fn load_file_skips_comments_and_blanks() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("hsts_cache");

        let mut f = File::create(&path).unwrap();
        writeln!(f, "# This is a comment").unwrap();
        writeln!(f, "").unwrap();
        writeln!(f, "example.com \"20301231 23:59:59\"").unwrap();
        writeln!(f, "# Another comment").unwrap();
        writeln!(f, ".secure.net \"unlimited\"").unwrap();
        drop(f);

        let mut cache = HstsCache::new();
        cache.load_file(&path).unwrap();

        assert_eq!(cache.entries.len(), 2);
        assert!(cache.should_upgrade("example.com"));
        assert!(cache.should_upgrade("sub.secure.net"));
    }

    #[test]
    fn load_nonexistent_file_is_ok() {
        let mut cache = HstsCache::new();
        let result = cache.load_file(Path::new("/tmp/nonexistent_hsts_file_xyz"));
        assert!(result.is_ok());
        assert!(cache.is_empty());
    }

    #[test]
    fn load_file_skips_invalid_lines() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("hsts_cache");

        let mut f = File::create(&path).unwrap();
        writeln!(f, "example.com \"20301231 23:59:59\"").unwrap();
        writeln!(f, "this-is-invalid").unwrap(); // no date
        writeln!(f, "also-bad unquoted-date").unwrap(); // unquoted
        writeln!(f, "good.example.org \"unlimited\"").unwrap();
        drop(f);

        let mut cache = HstsCache::new();
        cache.load_file(&path).unwrap();

        assert_eq!(cache.entries.len(), 2);
        assert!(cache.should_upgrade("example.com"));
        assert!(cache.should_upgrade("good.example.org"));
    }

    #[test]
    fn load_duplicate_hostname_keeps_largest_expiry() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("hsts_cache");

        let mut f = File::create(&path).unwrap();
        writeln!(f, "example.com \"20250101 00:00:00\"").unwrap();
        writeln!(f, "example.com \"20301231 23:59:59\"").unwrap();
        drop(f);

        let mut cache = HstsCache::new();
        cache.load_file(&path).unwrap();

        let entry = cache.entries.get("example.com").unwrap();
        // The second (larger) expiry should be kept.
        let expected = parse_hsts_date("20301231 23:59:59").unwrap();
        assert_eq!(entry.expires, expected);
    }

    // -- Helper function tests --------------------------------------------

    #[test]
    fn normalize_hostname_strips_dots_and_lowercases() {
        assert_eq!(normalize_hostname("Example.COM."), "example.com");
        assert_eq!(normalize_hostname("HELLO..."), "hello");
        assert_eq!(normalize_hostname(""), "");
        assert_eq!(normalize_hostname("."), "");
    }

    #[test]
    fn is_ip_address_detects_ipv4() {
        assert!(is_ip_address("127.0.0.1"));
        assert!(is_ip_address("192.168.0.1"));
        assert!(is_ip_address("0.0.0.0"));
    }

    #[test]
    fn is_ip_address_detects_ipv6() {
        assert!(is_ip_address("::1"));
        assert!(is_ip_address("[::1]"));
        assert!(is_ip_address("2001:db8::1"));
    }

    #[test]
    fn is_ip_address_rejects_hostnames() {
        assert!(!is_ip_address("example.com"));
        assert!(!is_ip_address("localhost"));
        assert!(!is_ip_address("my-host.local"));
    }

    #[test]
    fn format_and_parse_date_round_trip() {
        let ts: i64 = 1_718_452_800; // 2024-06-15 12:00:00 UTC
        let formatted = format_hsts_date(ts);
        assert_eq!(formatted, "20240615 12:00:00");
        let parsed = parse_hsts_date(&formatted).unwrap();
        assert_eq!(parsed, ts);
    }

    #[test]
    fn format_hsts_date_unlimited_fallback() {
        // i64::MAX cannot be represented as a calendar date.
        let s = format_hsts_date(HSTS_UNLIMITED);
        assert_eq!(s, UNLIMITED_STR);
    }

    #[test]
    fn parse_max_age_number_basic() {
        let (val, rest) = parse_max_age_number(b"12345abc").unwrap();
        assert_eq!(val, 12345);
        assert_eq!(rest, b"abc");
    }

    #[test]
    fn parse_max_age_number_overflow_saturates() {
        // A number larger than i64::MAX should saturate.
        let huge = b"99999999999999999999999";
        let (val, _) = parse_max_age_number(huge).unwrap();
        assert_eq!(val, i64::MAX);
    }

    #[test]
    fn parse_max_age_number_no_digits_is_error() {
        let result = parse_max_age_number(b"abc");
        assert!(result.is_err());
    }

    #[test]
    fn build_temp_path_appends_tmp() {
        let p = build_temp_path(Path::new("/some/dir/hsts.cache"));
        assert_eq!(p, PathBuf::from("/some/dir/hsts.cache.tmp"));
    }
}
