// -----------------------------------------------------------------------
// curl-rs/src/callbacks/progress.rs — Progress/Xferinfo Callback
//
// Rust rewrite of `src/tool_cb_prg.c` and `src/tool_cb_prg.h` from
// curl 8.19.0-DEV.  Implements the CURLOPT_XFERINFOFUNCTION callback
// for progress bar display, including:
//
//   - Hash-bar percentage rendering for transfers with known total sizes
//   - Sine-wave spinner animation for transfers with unknown totals
//   - 10 Hz (100 ms) redraw rate cap to avoid excessive terminal output
//   - Resume offset handling for resumed transfers (`-C`/`--continue-at`)
//
// The 200-entry sine lookup table and animation logic are ported
// exactly from the C implementation to produce byte-for-byte identical
// stderr output.
//
// # Safety
//
// This module contains **zero** `unsafe` blocks.
//
// SPDX-License-Identifier: curl
// -----------------------------------------------------------------------

use std::io::Write;
use std::time::{Duration, Instant};

use crate::config::OperationConfig;
use crate::stderr::tool_stderr;
use crate::terminal::get_terminal_columns;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum progress bar width in characters.
///
/// Matches the C constant `MAX_BARLENGTH` (400) exactly.
const MAX_BARLENGTH: i32 = 400;

/// Minimum progress bar width in characters.
///
/// Matches the C constant `MIN_BARLENGTH` (20) exactly.
const MIN_BARLENGTH: i32 = 20;

/// Minimum interval between progress bar redraws (100 ms = 10 Hz).
const REDRAW_INTERVAL: Duration = Duration::from_millis(100);

// ---------------------------------------------------------------------------
// Sine Lookup Table — 200 entries, exact copy from C source
//
// Generated by the Perl formula:
//   sin($i / 200 * 2 * pi) * 500000 + 500000   for $i in 1..200
//
// Values range from 0 to 999999 and represent a normalised sine wave
// used to animate the spinner '#' highlights when the transfer total
// is unknown.
// ---------------------------------------------------------------------------

#[rustfmt::skip]
static SINUS: [i32; 200] = [
    515704, 531394, 547052, 562664, 578214, 593687, 609068, 624341, 639491,
    654504, 669364, 684057, 698568, 712883, 726989, 740870, 754513, 767906,
    781034, 793885, 806445, 818704, 830647, 842265, 853545, 864476, 875047,
    885248, 895069, 904500, 913532, 922156, 930363, 938145, 945495, 952406,
    958870, 964881, 970434, 975522, 980141, 984286, 987954, 991139, 993840,
    996054, 997778, 999011, 999752, 999999, 999754, 999014, 997783, 996060,
    993848, 991148, 987964, 984298, 980154, 975536, 970449, 964898, 958888,
    952426, 945516, 938168, 930386, 922180, 913558, 904527, 895097, 885277,
    875077, 864507, 853577, 842299, 830682, 818739, 806482, 793922, 781072,
    767945, 754553, 740910, 727030, 712925, 698610, 684100, 669407, 654548,
    639536, 624386, 609113, 593733, 578260, 562710, 547098, 531440, 515751,
    500046, 484341, 468651, 452993, 437381, 421830, 406357, 390976, 375703,
    360552, 345539, 330679, 315985, 301474, 287158, 273052, 259170, 245525,
    232132, 219003, 206152, 193590, 181331, 169386, 157768, 146487, 135555,
    124983, 114781, 104959,  95526,  86493,  77868,  69660,  61876,  54525,
     47613,  41147,  35135,  29581,  24491,  19871,  15724,  12056,   8868,
      6166,   3951,   2225,    990,    248,      0,    244,    982,   2212,
      3933,   6144,   8842,  12025,  15690,  19832,  24448,  29534,  35084,
     41092,  47554,  54462,  61809,  69589,  77794,  86415,  95445, 104873,
    114692, 124891, 135460, 146389, 157667, 169282, 181224, 193480, 206039,
    218888, 232015, 245406, 259048, 272928, 287032, 301346, 315856, 330548,
    345407, 360419, 375568, 390841, 406221, 421693, 437243, 452854, 468513,
    484202, 499907,
];

// ---------------------------------------------------------------------------
// StderrWriter — Write adapter for the global tool_stderr() stream
//
// Wraps the global `Mutex<ToolStderr>` behind the `std::io::Write` trait
// so that `ProgressData.out` can be a `Box<dyn Write>`.  Each `write`
// and `flush` call acquires the mutex, performs the operation, and
// releases it, ensuring thread safety.
// ---------------------------------------------------------------------------

/// A [`Write`] adapter that delegates all output to the global stderr
/// handle returned by [`tool_stderr()`].
///
/// Acquiring the lock on every `write` call is acceptable because the
/// progress callback fires at most 10 times per second.
struct StderrWriter;

impl Write for StderrWriter {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        match tool_stderr().lock() {
            Ok(mut guard) => {
                guard.stream.write_all(buf)?;
                Ok(buf.len())
            }
            Err(_) => Err(std::io::Error::other("stderr mutex poisoned")),
        }
    }

    fn flush(&mut self) -> std::io::Result<()> {
        match tool_stderr().lock() {
            Ok(mut guard) => guard.stream.flush(),
            Err(_) => Err(std::io::Error::other("stderr mutex poisoned")),
        }
    }
}

// ---------------------------------------------------------------------------
// ProgressData
// ---------------------------------------------------------------------------

/// Per-transfer progress bar state.
///
/// This is the Rust equivalent of the C `struct ProgressData` from
/// `src/tool_cb_prg.h`.  One instance is allocated per active transfer
/// and tracks all mutable state required to render the progress bar or
/// spinner animation.
///
/// # Fields
///
/// - `calls` — Number of times the callback has been invoked.
/// - `prev` — Previous transfer byte count (for change detection).
/// - `prevtime` — Timestamp of the last redraw (for 10 Hz rate cap).
/// - `width` — Current terminal width in columns (clamped to
///   [`MIN_BARLENGTH`]–[`MAX_BARLENGTH`]).
/// - `out` — Output stream (stderr by default).
/// - `initial_size` — Resume offset added to totals/progress.
/// - `tick` — Spinner animation phase index (0–199).
/// - `bar` — Spinner anchor horizontal position.
/// - `barmove` — Spinner anchor direction (+1 = right, −1 = left).
pub struct ProgressData {
    /// Number of callback invocations for this transfer.
    pub calls: i32,
    /// Previous transfer byte-offset (for detecting stalled progress).
    pub prev: i64,
    /// Monotonic timestamp of the last progress bar redraw.
    pub prevtime: Instant,
    /// Terminal width in columns, clamped to `[MIN_BARLENGTH, MAX_BARLENGTH]`.
    pub width: i32,
    /// Output stream for progress bar rendering (stderr wrapper).
    pub out: Box<dyn Write>,
    /// Resume-from byte offset (from `--continue-at`).
    pub initial_size: i64,
    /// Spinner sine-table phase index (0–199, wrapping).
    pub tick: u32,
    /// Spinner anchor horizontal position within the bar.
    pub bar: i32,
    /// Spinner anchor movement direction (+1 = rightward, −1 = leftward).
    pub barmove: i32,
}

// ---------------------------------------------------------------------------
// fly — Spinner animation for unknown-total transfers
// ---------------------------------------------------------------------------

/// Renders one frame of the spinner animation when the transfer total
/// is unknown.
///
/// Builds a carriage-return line of `bar.width` spaces, overlays the
/// `"-=O=-"` anchor at position `bar.bar`, and places four '#'
/// highlights at sine-wave-derived positions.  Writes the complete
/// frame to `bar.out`, then advances the animation state.
///
/// This function is a direct port of the C `fly()` function from
/// `tool_cb_prg.c` and produces identical output.
///
/// # Arguments
///
/// * `bar`   — Mutable progress state.
/// * `moved` — Whether the transfer byte count changed since the last
///   invocation (controls whether the anchor position advances).
fn fly(bar: &mut ProgressData, moved: bool) {
    let width = bar.width as usize;

    // check = width - 2: range for sine-derived positions
    let check = bar.width - 2;

    // Build frame buffer: '\r' + `width` spaces
    // Total buffer length = 1 (CR) + width
    let buf_len = 1 + width;
    let mut buf = vec![b' '; buf_len];
    buf[0] = b'\r';

    // Place the "-=O=-" anchor at buf[bar.bar + 1]
    let anchor = b"-=O=-";
    let anchor_start = (bar.bar as usize) + 1;
    for (i, &ch) in anchor.iter().enumerate() {
        let pos = anchor_start + i;
        if pos < buf_len {
            buf[pos] = ch;
        }
    }

    // Place '#' highlights at 4 phase-offset sine positions.
    // C formula: pos = sinus[(tick + offset) % 200] / (1000000 / check) + 1
    if check > 0 {
        let divisor = 1_000_000 / check;
        if divisor > 0 {
            for &offset in &[0u32, 5, 10, 15] {
                let idx = ((bar.tick + offset) % 200) as usize;
                let pos = (SINUS[idx] / divisor + 1) as usize;
                if pos < buf_len {
                    buf[pos] = b'#';
                }
            }
        }
    }

    // Write the composed frame to the output stream.
    let _ = bar.out.write_all(&buf);

    // Advance the animation tick by 2 per frame (mod 200).
    bar.tick += 2;
    if bar.tick >= 200 {
        bar.tick -= 200;
    }

    // Move the anchor position if the transfer made progress.
    if moved {
        bar.bar += bar.barmove;
    }

    // Bounce the anchor at the bar boundaries.
    if bar.bar >= (bar.width - 6) {
        bar.barmove = -1;
        bar.bar = bar.width - 6;
    } else if bar.bar < 0 {
        bar.barmove = 1;
        bar.bar = 0;
    }
}

// ---------------------------------------------------------------------------
// update_width — Re-query terminal width
// ---------------------------------------------------------------------------

/// Queries the current terminal width and updates `bar.width`, clamping
/// the result to `[MIN_BARLENGTH, MAX_BARLENGTH]`.
///
/// Direct port of the C `update_width()` function.
fn update_width(bar: &mut ProgressData) {
    let cols = get_terminal_columns() as i32;
    if cols > MAX_BARLENGTH {
        bar.width = MAX_BARLENGTH;
    } else if cols > MIN_BARLENGTH {
        bar.width = cols;
    } else {
        bar.width = MIN_BARLENGTH;
    }
}

// ---------------------------------------------------------------------------
// progressbarinit — Initialise ProgressData for a new transfer
// ---------------------------------------------------------------------------

/// Creates and initialises a [`ProgressData`] for a new transfer.
///
/// Rust equivalent of the C `progressbarinit(bar, config)` function.
/// All fields start at their zero/default state, with the following
/// overrides matching curl 8.x behaviour:
///
/// - `initial_size` is set to `config.resume_from` when
///   `config.use_resume` is `true`.
/// - `tick` starts at 150 (mid-cycle in the sine table).
/// - `barmove` starts at 1 (rightward animation).
/// - `width` is set by querying the terminal.
/// - `out` is wired to the global `tool_stderr` stream.
///
/// # Arguments
///
/// * `config` — The per-operation configuration (provides resume offset).
pub fn progressbarinit(config: &OperationConfig) -> ProgressData {
    let mut bar = ProgressData {
        calls: 0,
        prev: 0,
        prevtime: Instant::now(),
        width: MIN_BARLENGTH, // will be overwritten by update_width
        out: Box::new(StderrWriter),
        initial_size: 0,
        tick: 150,
        barmove: 1,
        bar: 0,
    };

    // Pass the resume-from value through so the progress function can
    // display progress towards the total file, not just the remaining
    // part.
    if config.use_resume {
        bar.initial_size = config.resume_from;
    }

    update_width(&mut bar);

    bar
}

// ---------------------------------------------------------------------------
// tool_progress_cb — CURLOPT_XFERINFOFUNCTION callback
// ---------------------------------------------------------------------------

/// Progress/xferinfo callback for the curl CLI tool.
///
/// This function is the Rust equivalent of the C `tool_progress_cb()`
/// from `tool_cb_prg.c`.  It is registered as the
/// `CURLOPT_XFERINFOFUNCTION` callback and called by the transfer
/// engine on each progress update.
///
/// # Behaviour
///
/// 1. Computes `total` and `point` by adding the resume offset
///    (`initial_size`) to the raw download+upload counters, using
///    saturating arithmetic to avoid overflow.
/// 2. Enforces a 10 Hz (100 ms) redraw rate cap to prevent excessive
///    terminal output.
/// 3. When the total is unknown (`total == 0`), renders a spinner
///    animation via [`fly()`].
/// 4. When the total is known (`total > 0`), renders a hash-bar with
///    percentage display, matching the curl 8.x output format exactly:
///    `\r{hashes…}{spaces…} {percent:5.1}%`
/// 5. Clears `config.readbusy` when set (the caller is responsible for
///    unpausing the transfer, since the curl handle is not available
///    in this scope).
///
/// # Arguments
///
/// * `bar`     — Mutable progress bar state for this transfer.
/// * `config`  — Mutable per-operation configuration (for readbusy).
/// * `dltotal` — Expected total download size reported by the server.
/// * `dlnow`   — Bytes downloaded so far.
/// * `ultotal` — Expected total upload size.
/// * `ulnow`   — Bytes uploaded so far.
///
/// # Returns
///
/// Always returns `0` (continue transfer).  A non-zero return would
/// abort the transfer, which this callback never does.
pub fn tool_progress_cb(
    bar: &mut ProgressData,
    config: &mut OperationConfig,
    dltotal: i64,
    dlnow: i64,
    ultotal: i64,
    ulnow: i64,
) -> i32 {
    let now = Instant::now();

    // ------------------------------------------------------------------
    // Calculate expected transfer size.
    //
    // `initial_size` can be negative when indicating that we are
    // expecting to get the filesize from the remote.
    // ------------------------------------------------------------------
    let total: i64;
    let point: i64;

    if bar.initial_size < 0 {
        // Negative initial_size: waiting for remote to supply file size.
        if dltotal != 0 || ultotal != 0 {
            total = dltotal.saturating_add(ultotal);
        } else {
            total = i64::MAX;
        }
    } else {
        let combined_total = dltotal.saturating_add(ultotal);
        if (i64::MAX - bar.initial_size) < combined_total {
            total = i64::MAX;
        } else {
            total = combined_total.saturating_add(bar.initial_size);
        }
    }

    // ------------------------------------------------------------------
    // Calculate the current progress.
    // ------------------------------------------------------------------
    if bar.initial_size < 0 {
        if dltotal != 0 || ultotal != 0 {
            point = dlnow.saturating_add(ulnow);
        } else {
            point = i64::MAX;
        }
    } else {
        let combined_now = dlnow.saturating_add(ulnow);
        if (i64::MAX - bar.initial_size) < combined_now {
            point = i64::MAX;
        } else {
            point = combined_now.saturating_add(bar.initial_size);
        }
    }

    // ------------------------------------------------------------------
    // Rate limiting — enforce 10 Hz redraw cap after the first call.
    // ------------------------------------------------------------------
    if bar.calls != 0 {
        // After the first call...
        if total != 0 {
            // We know the total data to transfer.
            if bar.prev == point {
                // Progress did not change since last invocation.
                return 0;
            } else if now.duration_since(bar.prevtime) < REDRAW_INTERVAL
                && point < total
            {
                // Limit progress-bar updating to 10 Hz except at 100%.
                return 0;
            }
        } else {
            // Total is unknown.
            if now.duration_since(bar.prevtime) < REDRAW_INTERVAL {
                // Limit spinner updating to 10 Hz.
                return 0;
            }
            update_width(bar);
            fly(bar, point != bar.prev);
        }
    }

    // Simply count invocations.
    bar.calls += 1;

    update_width(bar);

    // ------------------------------------------------------------------
    // Render the percentage hash-bar when total > 0 and progress changed.
    // ------------------------------------------------------------------
    if total > 0 && point != bar.prev {
        // If we've received more than the expected total, adjust.
        let effective_total = if point > total { point } else { total };

        let frac = (point as f64) / (effective_total as f64);
        let percent = frac * 100.0;
        let barwidth = (bar.width - 7) as usize;

        let mut num = ((barwidth as f64) * frac) as usize;
        if num > MAX_BARLENGTH as usize {
            num = MAX_BARLENGTH as usize;
        }

        // Build the hash string (left-justified in a field of barwidth).
        let hashes: String = "#".repeat(num);

        // Format matching curl 8.x: \r%-{barwidth}s %5.1f%%
        //   - '\r'
        //   - left-justified hash+space field of barwidth chars
        //   - one space
        //   - 5-wide percentage with 1 decimal place
        //   - literal '%'
        let line = format!(
            "\r{:<barwidth$} {:5.1}%",
            hashes,
            percent,
            barwidth = barwidth,
        );
        let _ = bar.out.write_all(line.as_bytes());
    }

    // Flush the output stream to ensure the bar is visible.
    let _ = bar.out.flush();

    // Record the latest progress point and timestamp.
    bar.prev = point;
    bar.prevtime = now;

    // Handle readbusy flag: clear it so the caller knows to unpause
    // the transfer.  The curl_easy_pause(CURLPAUSE_CONT) call is the
    // responsibility of the caller (operate.rs), which has access to
    // the transfer handle.
    if config.readbusy {
        config.readbusy = false;
    }

    0
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    /// Verify the sine table has exactly 200 entries.
    #[test]
    fn sinus_table_length() {
        assert_eq!(SINUS.len(), 200);
    }

    /// Verify key sine table boundary values match the C source.
    #[test]
    fn sinus_table_key_values() {
        // First entry
        assert_eq!(SINUS[0], 515704);
        // Peak (index 49, value 999999)
        assert_eq!(SINUS[49], 999999);
        // Zero crossing (index 149, value 0)
        assert_eq!(SINUS[149], 0);
        // Midpoint (index 99, value 500046)
        assert_eq!(SINUS[99], 500046);
        // Last entry
        assert_eq!(SINUS[199], 499907);
    }

    /// Verify constants match the C source.
    #[test]
    fn constants_match_c() {
        assert_eq!(MAX_BARLENGTH, 400);
        assert_eq!(MIN_BARLENGTH, 20);
    }

    /// Verify progressbarinit sets correct default values.
    #[test]
    fn init_defaults() {
        let config = OperationConfig::new();
        let bar = progressbarinit(&config);

        assert_eq!(bar.calls, 0);
        assert_eq!(bar.prev, 0);
        assert_eq!(bar.initial_size, 0);
        assert_eq!(bar.tick, 150);
        assert_eq!(bar.barmove, 1);
        assert_eq!(bar.bar, 0);
        assert!(bar.width >= MIN_BARLENGTH);
        assert!(bar.width <= MAX_BARLENGTH);
    }

    /// Verify progressbarinit copies resume_from when use_resume is set.
    #[test]
    fn init_with_resume() {
        let mut config = OperationConfig::new();
        config.use_resume = true;
        config.resume_from = 12345;

        let bar = progressbarinit(&config);
        assert_eq!(bar.initial_size, 12345);
    }

    /// Verify progressbarinit does NOT copy resume_from when use_resume
    /// is false.
    #[test]
    fn init_without_resume() {
        let mut config = OperationConfig::new();
        config.use_resume = false;
        config.resume_from = 12345;

        let bar = progressbarinit(&config);
        assert_eq!(bar.initial_size, 0);
    }

    /// Verify the fly function writes output and advances state.
    #[test]
    fn fly_advances_state() {
        let buf: Vec<u8> = Vec::new();
        let cursor = Cursor::new(buf);
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 40,
            out: Box::new(cursor),
            initial_size: 0,
            tick: 150,
            barmove: 1,
            bar: 0,
        };

        let initial_tick = bar.tick;
        fly(&mut bar, true);

        // tick should advance by 2
        assert_eq!(bar.tick, (initial_tick + 2) % 200);
        // bar should advance by barmove (1)
        assert_eq!(bar.bar, 1);
    }

    /// Verify the fly function bounces the anchor at the right boundary.
    #[test]
    fn fly_bounce_right() {
        let buf: Vec<u8> = Vec::new();
        let cursor = Cursor::new(buf);
        let width = 40;
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width,
            out: Box::new(cursor),
            initial_size: 0,
            tick: 0,
            barmove: 1,
            bar: width - 7, // one step from the right boundary
        };

        fly(&mut bar, true);

        // After moving right to width-6, direction should reverse
        assert_eq!(bar.bar, width - 6);
        assert_eq!(bar.barmove, -1);
    }

    /// Verify the fly function bounces the anchor at the left boundary.
    #[test]
    fn fly_bounce_left() {
        let buf: Vec<u8> = Vec::new();
        let cursor = Cursor::new(buf);
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 40,
            out: Box::new(cursor),
            initial_size: 0,
            tick: 0,
            barmove: -1,
            bar: 0, // at the left boundary
        };

        fly(&mut bar, true);

        // After attempting to move left past 0, direction should reverse
        assert_eq!(bar.bar, 0);
        assert_eq!(bar.barmove, 1);
    }

    /// Verify update_width clamps to MAX_BARLENGTH.
    #[test]
    fn update_width_clamps() {
        let buf: Vec<u8> = Vec::new();
        let cursor = Cursor::new(buf);
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 0,
            out: Box::new(cursor),
            initial_size: 0,
            tick: 0,
            barmove: 1,
            bar: 0,
        };

        update_width(&mut bar);

        assert!(bar.width >= MIN_BARLENGTH);
        assert!(bar.width <= MAX_BARLENGTH);
    }

    /// Verify tool_progress_cb first call always renders (no rate limit).
    #[test]
    fn progress_cb_first_call() {
        let buf: Vec<u8> = Vec::new();
        let cursor = Cursor::new(buf);
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 40,
            out: Box::new(cursor),
            initial_size: 0,
            tick: 150,
            barmove: 1,
            bar: 0,
        };
        let mut config = OperationConfig::new();

        let result = tool_progress_cb(&mut bar, &mut config, 100, 50, 0, 0);

        assert_eq!(result, 0);
        assert_eq!(bar.calls, 1);
    }

    /// Verify tool_progress_cb clears readbusy.
    #[test]
    fn progress_cb_clears_readbusy() {
        let buf: Vec<u8> = Vec::new();
        let cursor = Cursor::new(buf);
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 40,
            out: Box::new(cursor),
            initial_size: 0,
            tick: 150,
            barmove: 1,
            bar: 0,
        };
        let mut config = OperationConfig::new();
        config.readbusy = true;

        let _ = tool_progress_cb(&mut bar, &mut config, 100, 50, 0, 0);

        assert!(!config.readbusy);
    }

    /// Verify overflow saturation: adding initial_size to very large
    /// totals saturates at i64::MAX instead of wrapping.
    #[test]
    fn progress_cb_overflow_saturation() {
        let buf: Vec<u8> = Vec::new();
        let cursor = Cursor::new(buf);
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 40,
            out: Box::new(cursor),
            initial_size: i64::MAX - 10,
            tick: 150,
            barmove: 1,
            bar: 0,
        };
        let mut config = OperationConfig::new();

        // dltotal + initial_size would overflow; should saturate
        let result = tool_progress_cb(&mut bar, &mut config, 100, 50, 0, 0);
        assert_eq!(result, 0);
        // prev should be set to i64::MAX (saturated)
        assert_eq!(bar.prev, i64::MAX);
    }

    /// Verify negative initial_size path (expecting remote file size).
    #[test]
    fn progress_cb_negative_initial_size() {
        let buf: Vec<u8> = Vec::new();
        let cursor = Cursor::new(buf);
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 40,
            out: Box::new(cursor),
            initial_size: -1,
            tick: 150,
            barmove: 1,
            bar: 0,
        };
        let mut config = OperationConfig::new();

        let result = tool_progress_cb(&mut bar, &mut config, 100, 50, 0, 0);
        assert_eq!(result, 0);
        // With negative initial_size and nonzero dltotal: point = dlnow + ulnow
        assert_eq!(bar.prev, 50);
    }

    /// Verify that the percentage bar callback tracks state correctly
    /// at 50% completion.
    #[test]
    fn percentage_bar_state_at_50_percent() {
        let buf = std::sync::Arc::new(std::sync::Mutex::new(Vec::<u8>::new()));
        let writer = SharedBufWriter(buf.clone());
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 40,
            out: Box::new(writer),
            initial_size: 0,
            tick: 150,
            barmove: 1,
            bar: 0,
        };
        let mut config = OperationConfig::new();

        // 50% of 100 bytes downloaded
        tool_progress_cb(&mut bar, &mut config, 100, 50, 0, 0);

        assert_eq!(bar.calls, 1);
        assert_eq!(bar.prev, 50);

        // Verify output was written and contains expected elements
        let output = buf.lock().unwrap();
        let output_str = String::from_utf8_lossy(&output);
        // Should start with carriage return
        assert!(output_str.starts_with('\r'), "output should start with \\r");
        // Should contain hash marks
        assert!(output_str.contains('#'), "output should contain '#' hashes");
        // Should contain percentage
        assert!(output_str.contains('%'), "output should contain '%'");
        // Should contain "50.0"
        assert!(
            output_str.contains("50.0"),
            "output should contain 50.0 percent, got: {:?}",
            output_str
        );
    }

    /// Verify 100% completion bar rendering.
    #[test]
    fn percentage_bar_at_100_percent() {
        let buf = std::sync::Arc::new(std::sync::Mutex::new(Vec::<u8>::new()));
        let writer = SharedBufWriter(buf.clone());
        let mut bar = ProgressData {
            calls: 0,
            prev: 0,
            prevtime: Instant::now(),
            width: 40,
            out: Box::new(writer),
            initial_size: 0,
            tick: 150,
            barmove: 1,
            bar: 0,
        };
        let mut config = OperationConfig::new();

        // 100% complete
        tool_progress_cb(&mut bar, &mut config, 200, 200, 0, 0);

        let output = buf.lock().unwrap();
        let output_str = String::from_utf8_lossy(&output);
        assert!(output_str.contains("100.0"), "output should show 100.0%");
    }

    /// A Write adapter that writes into a shared Vec for test inspection.
    struct SharedBufWriter(std::sync::Arc<std::sync::Mutex<Vec<u8>>>);

    impl Write for SharedBufWriter {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            let mut data = self.0.lock().unwrap();
            data.extend_from_slice(buf);
            Ok(buf.len())
        }
        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }
}
